act_code: '81627'
requisite: Решение Кармакшинского районного маслихата Кызылординской области от 14 июля 2014 года № 203. Зарегистрировано Департаментом юстиции Кызылординской области 28 июля 2014 года № 4735. Утратило силу решением Кармакшинского районного маслихата Кызылординской области от 23 октября 2018 года № 205
title:
  rus: Об утверждении тарифа на вызов твердых бытовых отходов
  kaz: Тұрмыстық қатты қалдықтарды әкету тарифін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-07-14
approved_by:
- '161005000002'
version_date:
  kaz: 2014-07-14
  rus: 2014-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/81627/kaz/14.07.2014
  rus: https://zan.gov.kz/client/#!/doc/81627/rus/14.07.2014
