act_code: '57020'
requisite: Решение от 24.12.2010 №290, Маслихат Сырдарьинского района
title:
  rus: Біржолғы талон құнын белгілеу турал
  kaz: Біржолғы талон құнын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '161007000002'
version_date:
  kaz: 2010-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/57020/kaz/24.12.2010
