act_code: '125455'
requisite: Решение акима сельского округа Оркендеу Казалинского района Кызылординской области от 18 октября 2018 года № 21. Зарегистрировано Департаментом юстиции Кызылординской области 25 октября 2018 года № 6479
title:
  rus: О присвоении наименовании и переименований улиц
  kaz: Көшеге атау беру және қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-10-18
approved_by:
- '161004012002'
version_date:
  kaz: 2018-10-18
  rus: 2018-10-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/125455/kaz/18.10.2018
  rus: https://zan.gov.kz/client/#!/doc/125455/rus/18.10.2018
