act_code: '48328'
requisite: Қызылорда облысы Жаңақорған аудандық мәслихатының 2009 жылғы 25 қыркүйектегі N 163 шешімі. Қызылорда облысының Әділет департаменті Жаңақорған аудандық Әділет басқармасында 2009 жылы 30 қазанда N 10-7-83 тіркелді. Күші жойылды - Қызылорда облысы Жаңақорған аудандық мәслихатының 2012 жылғы 12 маусымдағы N 53 Шешімімен
title:
  rus: Жаңақорған ауданының аумағында иттер мен мысықтарды ұстау Ережелерін бекіту туралы
  kaz: Жаңақорған ауданының аумағында иттер мен мысықтарды ұстау Ережелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-09-25
approved_by:
- '161009000002'
version_date:
  kaz: 2009-09-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/48328/kaz/25.09.2009
