act_code: '28900'
requisite: Решение от 30.06.2006 №301, Маслихат Кызылординской области
title:
  rus: Әлеуметтік мәні бар ауданаралық (қалааралық) және ішкі темір жол қатынастарын айқындау туралы
  kaz: Әлеуметтік мәні бар ауданаралық (қалааралық) және ішкі темір жол қатынастарын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-06-30
approved_by:
- '161000000002'
version_date:
  kaz: 2006-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/28900/kaz/30.06.2006
