act_code: '81637'
requisite: Решение Кармакшинского районного маслихата Кызылординской области от 30 июня 2014 года N 188. Зарегистрировано Департаментом юстиции Кызылординской области 28 июня 2014 года N 4736. Утратило силу решением Кармакшинского районного маслихата Кызылординской области от 23.12.2015 № 315.
title:
  rus: Об утверждении правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсету, оның мөлшерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-06-30
approved_by:
- '161005000002'
version_date:
  kaz: 2015-03-03
  rus: 2015-03-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/81637/kaz/03.03.2015
  rus: https://zan.gov.kz/client/#!/doc/81637/rus/03.03.2015
caused_by:
  code: '87794'
  requisite: Решение от 03.03.2015 №242, Маслихат Кармакшинского района
  title:
    rus: О внесении изменений и дополнений в решение Кармакшинского районного маслихата от 30 июня 2014 года № 188 «Об утверждении правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: «Әлеуметтік көмек көрсету, оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидаларын бекіту туралы» Қармақшы аудандық мәслихатының 2014 жылғы 30 маусымдағы № 188 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/87794/rus
