act_code: '91864'
requisite: Решение акима поселка Жанакорган Жанакорганского района Кызылординской области от 14 июля 2015 года № 931. Зарегистрировано Департаментом юстиции Кызылординской области 17 июля 2015 года № 5061. Утратило силу решением акима поселка Жанакорган Жанакорганского района Кызылординской области от 30 сентября 2015 года № 86
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-07-14
approved_by:
- '161009001001'
version_date:
  kaz: 2015-07-14
  rus: 2015-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/91864/kaz/14.07.2015
  rus: https://zan.gov.kz/client/#!/doc/91864/rus/14.07.2015
