act_code: '214345'
requisite: Решение акима сельского округа Жанадария Жалагашского района Кызылординской области от 15 сентября 2025 года № 4
title:
  rus: О переименовании улицы «Тұрғын үй-91» в селе Жанадария в улицу «Құмқала»
  kaz: Жаңадария ауылындағы «Тұрғын үй-91» көшесін «Құмқала» атымен қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-15
approved_by:
- '161006014002'
version_date:
  kaz: 2025-09-15
  rus: 2025-09-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/214345/kaz/15.09.2025
  rus: https://zan.gov.kz/client/#!/doc/214345/rus/15.09.2025
