act_code: '50005'
requisite: Решение от 15.12.2009 №07, Акимат Казалинского района
title:
  rus: Он жеті жасқа толатын азаматтарды әскерге шақыру учаскесіне тіркеу туралы
  kaz: Он жеті жасқа толатын азаматтарды әскерге шақыру учаскесіне тіркеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-15
approved_by:
- '161004000001'
version_date:
  kaz: 2009-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/50005/kaz/15.12.2009
