act_code: '94789'
requisite: Решение Казалинского районного маслихата Кызылординской области от 23 сентября 2015 года № 349. Зарегистрировано департаментом юстиции Кызылординской области 22 октября 2015 года № 5190
title:
  rus: Об утверждении положения о награждении Почетной грамотой Казалинского района
  kaz: Қазалы ауданының Құрмет грамотасымен наградтау туралы ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-09-23
approved_by:
- '161004000002'
version_date:
  kaz: 2022-09-07
  rus: 2022-09-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/94789/kaz/07.09.2022
  rus: https://zan.gov.kz/client/#!/doc/94789/rus/07.09.2022
caused_by:
  code: '171453'
  requisite: Решение Казалинского районного маслихата Кызылординской области от 7 сентября 2022 года № 267. Зарегистрировано в Министерстве юстиции Республики Казахстан 9 сентября 2022 года № 29491
  title:
    rus: О внесении изменения в решение Казалинского районного маслихата от 23 сентября 2015 года № 349 «Об утверждении положения о награждении Почетной грамотой Казалинского района»
    kaz: Қазалы аудандық мәслихатының 2015 жылғы 23 қыркүйектегі №349 «Қазалы ауданының Құрмет грамотасымен наградтау туралы ережесін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/171453/rus
