act_code: '94789'
requisite: Решение Казалинского районного маслихата Кызылординской области от 23 сентября 2015 года № 349. Зарегистрировано департаментом юстиции Кызылординской области 22 октября 2015 года № 5190
title:
  rus: Об утверждении положения о награждении Почетной грамотой Казалинского района
  kaz: Қазалы ауданының Құрмет грамотасымен наградтау туралы ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-09-23
approved_by:
- '161004000002'
version_date:
  kaz: 2015-09-23
  rus: 2015-09-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/94789/kaz/23.09.2015
  rus: https://zan.gov.kz/client/#!/doc/94789/rus/23.09.2015
