act_code: '98443'
requisite: Решение Жалагашского районного маслихата Кызылординской области от 23 декабря 2015 года № 49-7. Зарегистрировано Департаментом юстиции Кызылординской области 26 января 2016 года № 5326
title:
  rus: Об утверждении Положения о награждении Почетной грамотой Жалагашского района
  kaz: Жалағаш ауданының Құрмет грамотасымен наградтау туралы Ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-23
approved_by:
- '161006000002'
version_date:
  kaz: 2023-12-27
  rus: 2023-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/98443/kaz/27.12.2023
  rus: https://zan.gov.kz/client/#!/doc/98443/rus/27.12.2023
caused_by:
  code: '191920'
  requisite: Решение Жалагашского районного маслихата Кызылординской области от 27 декабря 2023 года № 13-4. Зарегистрировано Департаментом юстиции Кызылординской области 8 января 2024 года № 8486-11
  title:
    rus: О внесении изменений в решение Жалагашского районного маслихата от 23 декабря 2015 года № 49-7 «Об утверждении Положения о награждении Почетной грамотой Жалагашского района»
    kaz: «Жалағаш ауданының Құрмет грамотасымен наградтау туралы Ережесін бекіту туралы» Жалағаш аудандық мәслихатының 2015 жылғы 23 желтоқсандағы № 49-7 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/191920/rus
