act_code: '114592'
requisite: Решение Жалагашского районного маслихата Кызылординской области от 24 августа 2017 года № 15-1. Зарегистрировано Департаментом юстиции Кызылординской области 8 сентября 2017 года № 5957. Утратило силу решением Жалагашского районного маслихата Кызылординской области от 13 апреля 2020 года № 55-1
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсету, оның мөлшерлерін  белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-08-24
approved_by:
- '161006000002'
version_date:
  kaz: 2019-12-27
  rus: 2019-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/114592/kaz/27.12.2019
  rus: https://zan.gov.kz/client/#!/doc/114592/rus/27.12.2019
caused_by:
  code: '138884'
  requisite: Решение Жалагашского районного маслихата Кызылординской области от 27 декабря 2019 года № 51-17. Зарегистрировано Департаментом юстиции Кызылординской области 9 января 2020 года № 7209. Утратило силу решением Жалагашского районного маслихата Кызылординской области от 13 апреля 2020 года № 55-1
  title:
    rus: О внесении изменения в решение Жалагашского районного маслихата от 24 августа 20017 года №15-1 “Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан”
    kaz: Әлеуметтік көмек көрсету, оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау Қағидаларын бекіту туралы” Жалағаш аудандық мәслихатының 2017 жылғы 24 тамыздағы №15-1 шешіміне өзгеріс енгізу туралы”
  link: https://zan.gov.kz/client/#!/doc/138884/rus
