act_code: '15586'
requisite: Қызылорда қалалық әкiмиятының 2003 жылғы 19 наурыздағы N 2842 шешімі. Қызылорда облыстық Әдiлет басқармасында 2003 жылғы 25 наурызда N 3163 тiркелдi. Күші жойылды - Қызылорда қаласы әкімінің 2012 жылғы 05 желтоқсандағы N 533 Шешімімен
title:
  rus: 2003 жыл "Ауыл жылын" жоғары деңгейде өткізу үшін "Наурыз шапағаты" аясында көркейту-көгалдандыру және санитарлық тазалық жұмыстарының екі айлығын ұйымдастыру туралы
  kaz: 2003 жыл "Ауыл жылын" жоғары деңгейде өткізу үшін "Наурыз шапағаты" аясында көркейту-көгалдандыру және санитарлық тазалық жұмыстарының екі айлығын ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-03-19
approved_by:
- '161002000001'
version_date:
  kaz: 2003-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/15586/kaz/19.03.2003
