act_code: '221231'
requisite: Решение Кызылординского городского маслихата от 19 декабря 2025 года № 314-45/1
title:
  rus: О утверждении бюджета города Кызылорда на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған Қызылорда қаласының бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-19
approved_by:
- '161002000002'
version_date:
  kaz: 2026-01-30
  rus: 2026-01-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/221231/kaz/30.01.2026
  rus: https://zan.gov.kz/client/#!/doc/221231/rus/30.01.2026
caused_by:
  code: '222087'
  requisite: Решение Кызылординского городского маслихата от 30 января 2026 года № 344-48/1
  title:
    rus: О внесении изменений и дополнений в решение Кызылординского городского маслихата от 19 декабря 2025 года № 314-45/1 «Об утверждении бюджета города Кызылорда на 2026-2028 годы»
    kaz: «2026-2028 жылдарға арналған Қызылорда қаласының бюджетін бекіту туралы» Қызылорда қалалық мәслихатының 2025 жылғы 19 желтоқсандағы № 314-45/1 шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/222087/rus
