act_code: '164136'
requisite: Решение Жанакорганского районного маслихата Кызылординской области от 30 декабря 2021 года № 173
title:
  rus: О бюджете сельского округа Каратобе на 2022-2024 годы
  kaz: Қаратөбе ауылдық округінің 2022-2024 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '161009000002'
version_date:
  kaz: 2022-08-11
  rus: 2022-08-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/164136/kaz/11.08.2022
  rus: https://zan.gov.kz/client/#!/doc/164136/rus/11.08.2022
caused_by:
  code: '170916'
  requisite: Решение Жанакорганского районного маслихата Кызылординской области от 11 августа 2022 года № 267
  title:
    rus: О внесении изменений в решение Жанакорганского районного маслихата от 30 декабря 2021 года №173 «О бюджете сельского округа Каратобе на 2022-2024 годы»
    kaz: «Қаратөбе ауылдық округінің 2022-2024 жылдарға арналған бюджеті туралы» Жаңақорған аудандық мәслихатының 2021 жылғы 30 желтоқсандағы №173 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/170916/rus
