act_code: '132886'
requisite: Решение Кызылординского областного маслихата от 18 июня 2019 года № 325. Зарегистрировано Департаментом юстиции Кызылординской области 21 июня 2019 года № 6832. Утратило силу решением Кызылординского областного маслихата от 29 марта 2024 года № 87
title:
  rus: Об утверждении целевых показателей качества окружающей среды Кызылординской области
  kaz: Қызылорда облысының қоршаған орта сапасының нысаналы көрсеткіштерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-06-18
approved_by:
- '161000000002'
version_date:
  kaz: 2019-06-18
  rus: 2019-06-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/132886/kaz/18.06.2019
  rus: https://zan.gov.kz/client/#!/doc/132886/rus/18.06.2019
