act_code: '163044'
requisite: Решение Жанакорганского районного маслихата Кызылординской области от 27 декабря 2021 года № 148. Зарегистрировано в Министерстве юстиции Республики Казахстан 28 декабря 2021 года № 26163
title:
  rus: «О районном бюджете на 2022-2024 годы»
  kaz: «2022-2024 жылдарға арналған аудандық бюджет туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-27
approved_by:
- '161009000002'
version_date:
  kaz: 2021-12-27
  rus: 2021-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/163044/kaz/27.12.2021
  rus: https://zan.gov.kz/client/#!/doc/163044/rus/27.12.2021
