act_code: '96574'
requisite: Решение Кызылординского областного маслихата от 10 декабря 2015 года № 325. Зарегистрировано Департаментом юстиции Кызылординской области 22 декабря 2015 года № 5269
title:
  rus: Об областном бюджете на 2016-2018 годы
  kaz: 2016-2018 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-10
approved_by:
- '161000000002'
version_date:
  kaz: 2016-07-13
  rus: 2016-07-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/96574/kaz/13.07.2016
  rus: https://zan.gov.kz/client/#!/doc/96574/rus/13.07.2016
caused_by:
  code: '104607'
  requisite: Решение Кызылординского областного маслихата от 13 июля 2016 года № 38. Зарегистрировано Департаментом юстиции Кызылординской области 18 июля 2016 года № 5563
  title:
    rus: О внесении изменений и дополнений в решение Кызылординского областного маслихата от 10 декабря 2015 года № 325 "Об областном бюджете на 2016-2018 годы"
    kaz: '"2016-2018 жылдарға арналған облыстық бюджет туралы" Қызылорда облыстық мәслихатының 2015 жылғы 10 желтоқсандағы № 325 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/104607/rus
