act_code: '128085'
requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 26 декабря 2018 года № 268. Зарегистрировано Департаментом юстиции Кызылординской области 28 декабря 2018 года № 6607
title:
  rus: О бюджете поселка Теренозек на 2019-2021 годы
  kaz: Тереңөзек кентінің 2019–2021 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-26
approved_by:
- '161007000002'
version_date:
  kaz: 2019-11-19
  rus: 2019-11-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/128085/kaz/19.11.2019
  rus: https://zan.gov.kz/client/#!/doc/128085/rus/19.11.2019
caused_by:
  code: '136293'
  requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 19 ноября 2019 года № 351. Зарегистрировано Департаментом юстиции Кызылординской области 21 ноября 2019 года № 6976
  title:
    rus: О внесении изменений в решение Сырдарьинского районного маслихата от 26 декабря 2018 года №268 «О бюджете поселка Теренозек на 2019-2021 годы»
    kaz: «Тереңөзек кентінің 2019–2021 жылдарға арналған бюджеті туралы» Сырдария аудандық мәслихатының 2018 жылғы 26 желтоқсандағы №268 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/136293/rus
