act_code: '7980'
requisite: Решение от 28.02.2000 №164, Аким Кызылординской области
title:
  rus: Облыс кәсіпорындары мен ұйымдарының қаржылық жағдайына талдау жүргізу туралы
  kaz: Облыс кәсіпорындары мен ұйымдарының қаржылық жағдайына талдау жүргізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-02-28
approved_by:
- '161000000003'
version_date:
  kaz: 2000-02-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/7980/kaz/28.02.2000
