act_code: '188915'
requisite: Решение Шиелийского районного маслихата Кызылординской области от 14 ноября 2023 года № 7/5. Зарегистрировано Департаментом юстиции Кызылординской области 22 ноября 2023 года № 8468-11
title:
  rus: Об утверждении правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан Шиелийского района
  kaz: Шиелі ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-11-14
approved_by:
- '161008000002'
version_date:
  kaz: 2023-11-14
  rus: 2023-11-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/188915/kaz/14.11.2023
  rus: https://zan.gov.kz/client/#!/doc/188915/rus/14.11.2023
