act_code: '79234'
requisite: Решение Жалагашского районного маслихата Кызылординской области от 09 апреля 2014 года N 30-6. Зарегистрировано Департаментом юстиции Кызылординской области 29 апреля 2014 года за N 4645. Утратило силу решением Жалагашского районного маслихата Кызылординской области от 23.12.2015 № 49-8.
title:
  rus: Об установлении повышенных на двадцать пять процентов окладов и тарифных ставок специалистам в области здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, являющимся гражданскими служащими и работающим в сельской местности
  kaz: Азаматтық қызметші болып табылатын және ауылдық жерде жұмыс iстейтiн  денсаулық сақтау, әлеуметтiк қамсыздандыру, бiлiм беру, мәдениет, спорт және ветеринария саласындағы мамандарға жиырма бес пайызға жоғарылатылған лауазымдық айлықақылар мен тарифтiк ставкалар белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-09
approved_by:
- '161006000002'
version_date:
  kaz: 2014-04-09
  rus: 2014-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/79234/kaz/09.04.2014
  rus: https://zan.gov.kz/client/#!/doc/79234/rus/09.04.2014
