act_code: '56586'
requisite: Решение от 10.12.2010 №69, Акимат Жалагашского района
title:
  rus: Азаматтарды аудандық шақыру учаскесіне тіркеуді ұйымдастыру туралы
  kaz: Азаматтарды аудандық шақыру учаскесіне тіркеуді ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-10
approved_by:
- '161006000001'
version_date:
  kaz: 2010-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/56586/kaz/10.12.2010
