act_code: '39879'
requisite: Қызылорда облысы Cырдария аудандық мәслихатының 2008 жылғы 24 сәуірдегі N 80 шешімі. Қызылорда облысының Әділет департаменті Сырдария аудандық Әділет басқармасында 2008 жылғы 2 маусымда N 10-8-67 тіркелді. Күші жойылды - Қызылорда облысы Cырдария аудандық мәслихатының 2009 жылғы 10 шілдедегі  N 168 шешімімен
title:
  rus: '"Тереңөзек кентінде үй жануарларын күтіп ұстаудың Қағидасын бекіту туралы"'
  kaz: '"Тереңөзек кентінде үй жануарларын күтіп ұстаудың Қағидасын бекіту туралы"'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-04-24
approved_by:
- '161007000002'
version_date:
  kaz: 2008-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/39879/kaz/24.04.2008
