act_code: '96506'
requisite: Решение акима сельского округа Кожамберди Жанакорганского района Кызылординской области от 18 ноября 2015 года N 94. Зарегистрировано Департаментом юстиции Кызылординской области 10 декабря 2015 года N 5255
title:
  rus: О присвоении наименования улице в селе Кожамберди
  kaz: Қожамберді ауылындағы көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-11-18
approved_by:
- '161009024001'
version_date:
  kaz: 2015-11-18
  rus: 2015-11-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/96506/kaz/18.11.2015
  rus: https://zan.gov.kz/client/#!/doc/96506/rus/18.11.2015
