act_code: '204746'
requisite: Решение Жанакорганского районного маслихата Кызылординской области от 20 декабря 2024 года № 297
title:
  rus: «О районном бюджете на 2025-2027 годы»
  kaz: «2025-2027 жылдарға арналған аудандық бюджет туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-20
approved_by:
- '161009000002'
version_date:
  kaz: 2024-12-20
  rus: 2024-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/204746/kaz/20.12.2024
  rus: https://zan.gov.kz/client/#!/doc/204746/rus/20.12.2024
