act_code: '150736'
requisite: Решение Жалагашского районного маслихата Кызылординской области от 23 декабря 2020 года № 69-1. Зарегистрировано Департаментом юстиции Кызылординской области 28 декабря 2020 года № 7958
title:
  rus: О районном бюджете на 2021-2023 годы
  kaz: 2021 – 2023 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-23
approved_by:
- '161006000002'
version_date:
  kaz: 2021-09-03
  rus: 2021-09-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/150736/kaz/03.09.2021
  rus: https://zan.gov.kz/client/#!/doc/150736/rus/03.09.2021
caused_by:
  code: '188893'
  requisite: Решение Жалагашского районного маслихата Кызылординской области от 3 сентября 2021 года № 8-2. Зарегистрировано в Министерстве юстиции Республики Казахстан 17 сентября 2021 года № 24398
  title:
    rus: О внесении изменений в решение Жалагашского районного маслихата от 23 декабря 2020 года №69-1 «О районном бюджете на 2021 – 2023 годы»
    kaz: «2021 – 2023 жылдарға арналған аудандық бюджет туралы» Жалағаш аудандық мәслихатының 2020 жылғы 23 желтоқсандағы №69-1 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/188893/rus
