act_code: '9229'
requisite: Решение от 03.02.2001 №414, Аким Кызылординской области
title:
  rus: Қызылорда облысының 2001-2002 жылдарға арналған экономикалық қауiпсiздiк бағдарламасы туралы
  kaz: Қызылорда облысының 2001-2002 жылдарға арналған экономикалық қауiпсiздiк бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-02-03
approved_by:
- '161000000003'
version_date:
  kaz: 2001-02-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/9229/kaz/03.02.2001
