act_code: '49714'
requisite: Решение от 24.12.2009 №146, Маслихат Кармакшинского района
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-24
approved_by:
- '161005000002'
version_date:
  kaz: 2010-09-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/49714/kaz/07.09.2010
caused_by:
  code: '54513'
  requisite: Решение от 07.09.2010 №199, Маслихат Кармакшинского района
  title:
    rus: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Қармақшы аудандық мәслихатының 2009 жылғы 24 желтоқсандағы кезекті 20 сессиясының N 146 шешіміне өзгерістер енгізу туралы'
    kaz: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Қармақшы аудандық мәслихатының 2009 жылғы 24 желтоқсандағы кезекті 20 сессиясының N 146 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/54513/rus
