act_code: '206737'
requisite: Решение Жанакорганского районного маслихата Кызылординской области от 25 декабря 2024 года № 326
title:
  rus: О бюджете сельского округа Суттикудик на 2025-2027 годы
  kaz: Сүттіқұдық ауылдық округінің 2025-2027 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '161009000002'
version_date:
  kaz: 2025-04-25
  rus: 2025-04-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/206737/kaz/25.04.2025
  rus: https://zan.gov.kz/client/#!/doc/206737/rus/25.04.2025
caused_by:
  code: '210390'
  requisite: Решение Жанакорганского районного маслихата Кызылординской области от 25 апреля 2025 года № 364
  title:
    rus: О внесении изменений в решение маслихата Жанакорганского района от 25 декабря 2024 года №326 О бюджете сельского округа Суттикудык на 2025-2027 годы
    kaz: Сүттіқұдық ауылдық округінің 2025-2027 жылдарға арналған бюджеті туралы Жаңақорған ауданы мәслихатының 2024 жылғы 25 желтоқсандағы №326 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/210390/rus
