act_code: '43291'
requisite: Қызылорда облысы Қазалы аудандық мәслихатының 2008 жылғы 23 желтоқсандағы N 100 шешімі. Қызылорда облысының Әділет департаменті Қазалы аудандық Әділет басқармасында 2008 жылы 31 желтоқсанда N 10-4-87 тіркелді. Қолданылу мерзімінің аяқталуына байланысты күші жойылды - (Қызылорда облысы Қазалы аудандық мәслихатының 2010 жылғы 07 мамырдағы N 253 хаты)
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-23
approved_by:
- '161004000002'
version_date:
  kaz: 2009-01-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/43291/kaz/31.01.2009
caused_by:
  code: '44355'
  requisite: Решение от 31.01.2009 №114, Маслихат Казалинского района
  title:
    rus: '"2009 жылға арналған аудандық бюджет туралы" Қазалы аудандық Мәслихатының 2008 жылғы 23 желтоқсандағы ХІІ сессиясының N 100 шешіміне өзгерістер мен толықтырулар енгізу туралы'
    kaz: '"2009 жылға арналған аудандық бюджет туралы" Қазалы аудандық Мәслихатының 2008 жылғы 23 желтоқсандағы ХІІ сессиясының N 100 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/44355/rus
