act_code: '206186'
requisite: Решение Казалинского районного маслихата Кызылординской области от 27 декабря 2024 года № 354
title:
  rus: О бюджете поселка Айтеке би на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Әйтеке би кентінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '161004000002'
version_date:
  kaz: 2025-03-05
  rus: 2025-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/206186/kaz/05.03.2025
  rus: https://zan.gov.kz/client/#!/doc/206186/rus/05.03.2025
caused_by:
  code: '208100'
  requisite: Решение Казалинского районного маслихата Кызылординской области от 5 марта 2025 года № 384
  title:
    rus: О внесении изменения в решение Казалинского районного маслихата Кызылординской области от 27 декабря 2024 года №354 «О бюджете поселка Айтеке би на 2025-2027 годы»
    kaz: Қызылорда облысы Қазалы аудандық мәслихатының 2024 жылғы 27 желтоқсандағы №354 «2025-2027 жылдарға арналған Әйтеке би кентінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/208100/rus
