act_code: '151738'
requisite: Решение Шиелийского районного маслихата Кызылординской области от 29 декабря 2020 года № 65/14. Зарегистрировано Департаментом юстиции Кызылординской области 5 января 2021 года № 8035
title:
  rus: О бюджете сельского округа Тартогай на 2021-2023 годы
  kaz: Тартоғай ауылдық округінің 2021-2023 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-29
approved_by:
- '161008000002'
version_date:
  kaz: 2021-09-08
  rus: 2021-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/151738/kaz/08.09.2021
  rus: https://zan.gov.kz/client/#!/doc/151738/rus/08.09.2021
caused_by:
  code: '158533'
  requisite: Решение Шиелийского районного маслихата Кызылординской области от 8 сентября 2021 года № 11/14
  title:
    rus: О внесении изменений в решение Шиелийского районного маслихата «О бюджете сельского округа Тартогай на 2021-2023 годы» от 29 декабря 2020 года №65/14
    kaz: Шиелі аудандық мәслихатының 2020 жылғы 29 желтоқсандағы «Тартогай ауылдық округінің 2021-2023 жылдарға арналған бюджеті туралы» №65/14 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/158533/rus
