act_code: '214045'
requisite: Решение акима сельского округа Акжарма города Кызылорда Кызылординской области от 09 сентября 2025 года № 223
title:
  rus: О присвоении наименований улице села Баймұрат батыр сельского округа Акжарма
  kaz: Ақжарма ауылдық округінің Баймұрат батыр ауылындағы көшеге атау  беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-09
approved_by:
- '161002005002'
version_date:
  kaz: 2025-09-09
  rus: 2025-09-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/214045/kaz/09.09.2025
  rus: https://zan.gov.kz/client/#!/doc/214045/rus/09.09.2025
