act_code: '136448'
requisite: Решение акима поселка Жосалы Кармакшинского района Кызылординской области от 25 ноября 2019 года № 663. Зарегистрировано Департаментом юстиции Кызылординской области 26 ноября 2019 года № 6987
title:
  rus: О присвоении наименовании и переименовании улиц
  kaz: Көшелерге атау беру және қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-11-25
approved_by:
- '161005001001'
version_date:
  kaz: 2019-11-25
  rus: 2019-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/136448/kaz/25.11.2019
  rus: https://zan.gov.kz/client/#!/doc/136448/rus/25.11.2019
