act_code: '176019'
requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 22 декабря 2022 года № 185
title:
  rus: Решение Сырдарьинского районного маслихата от 22 декабря 2022 года №185 «О бюджетах поселка и сельских округов Сырдарьинского района  на 2023 – 2025 годы»
  kaz: «Сырдария ауданының кент және ауылдық округтерінің 2023 – 2025 жылдарға арналған бюджеттері туралы» Сырдария аудандық мәслихатының 2022 жылғы 22 желтоқсандағы №185 шешімі
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-22
approved_by:
- '161007000002'
version_date:
  kaz: 2023-05-23
  rus: 2023-05-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/176019/kaz/23.05.2023
  rus: https://zan.gov.kz/client/#!/doc/176019/rus/23.05.2023
caused_by:
  code: '182481'
  requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 23 мая 2023 года № 34
  title:
    rus: Решение Сырдарьинского районного маслихата от 23 мая 2023 года №34 «О внесении изменений в решение Сырдарьинского районного маслихата от 22 декабря 2022 года №185 «О бюджетах поселка и сельских округов Сырдарьинского района на 2023-2025 годы»
    kaz: «Сырдария ауданының кент және ауылдық округтерінің 2023–2025 жылдарға арналған бюджеттері туралы» Сырдария аудандық мәслихатының 2022 жылғы 22 желтоқсандағы №185 шешіміне өзгерістер енгізу туралы» Сырдария аудандық мәслихатының 2023 жылғы 23 мамырдағы №34 шешімі
  link: https://zan.gov.kz/client/#!/doc/182481/rus
