act_code: '128372'
requisite: Решение Шиелийского районного маслихата Кызылординской области от 28 декабря 2018 года № 34/20. Зарегистрировано Департаментом юстиции Кызылординской области 29 декабря 2018 года № 6631
title:
  rus: О бюджете сельского округа Сулутобе на 2019-2021 годы
  kaz: Сұлутөбе ауылдық округінің 2019-2021 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-28
approved_by:
- '161008000002'
version_date:
  kaz: 2019-11-06
  rus: 2019-11-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/128372/kaz/06.11.2019
  rus: https://zan.gov.kz/client/#!/doc/128372/rus/06.11.2019
caused_by:
  code: '135854'
  requisite: Решение Шиелийского районного маслихата Кызылординской области от 6 ноября 2019 года № 45/7. Зарегистрировано Департаментом юстиции Кызылординской области 7 ноября 2019 года № 6959
  title:
    rus: О внесении изменений в решение Шиелийского районного маслихата от 28 декабря 2018 года №34/20 «О бюджете сельского округа Сулутобе на 2019-2021 годы»
    kaz: «Сұлутөбе ауылдық округінің 2019-2021 жылдарға арналған бюджеті туралы» Шиелі аудандық мәслихатының 2018 жылғы 28 желтоқсандағы №34/20 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/135854/rus
