act_code: '48077'
requisite: Қызылорда облысы Жалағаш аудандық мәслихатының 2009 жылғы 24 қыркүйектегі N 20-3 шешімі. Қызылорда облысының Әділет департаменті Жалағаш ауданының Әділет басқармасында 2009 жылы 09 қазанда N 10-6-127 тіркелді. Күші жойылды - Қызылорда облысы Жалағаш аудандық мәслихатының 2012 жылғы 26 қыркүйектегі N 11-6 шешімімен
title:
  rus: Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік әлеуметтік қамсыздандыру, мәдениет, спорт ұйымдарының мамандарына және ауылдық жерде жұмыс істейтін мемлекеттік денсаулық сақтау, білім беру мамандарына отын сатып алуға жұмсалатын шығынды өтеу үшін өтемақы төлеу Нұсқаулығын бекіту туралы
  kaz: Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік әлеуметтік қамсыздандыру, мәдениет, спорт ұйымдарының мамандарына және ауылдық жерде жұмыс істейтін мемлекеттік денсаулық сақтау, білім беру мамандарына отын сатып алуға жұмсалатын шығынды өтеу үшін өтемақы төлеу Нұсқаулығын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-09-24
approved_by:
- '161006000002'
version_date:
  kaz: 2011-08-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/48077/kaz/31.08.2011
caused_by:
  code: '60620'
  requisite: Решение Жалагашского районного маслихата Кызылординской области от 31 августа 2011 года № 45-3. Зарегистрировано Департаментом юстиции Кызылординской области 22 сентября 2011 года № 10-6-193. Утратило силу - Решением Жалагашского районного маслихата Кызылординской области от 26 сентября 2012 года № 11-6
  title:
    rus: О внесении изменений в решение Жалагашского районного маслихата от 24 сентября 2009 года N 20-3 "Об утверждении Инструкции выплаты компенсации на возмещение расходов на приобретение топлива специалистам государственных организаций здравоохранения, образования, социального обеспечения, культуры и спорта, проживающим и работающим в сельских населенных пунктах"
    kaz: '"Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет және спорт мамандарына отын сатып алуға жұмсалатын шығынды өтеу үшін өтемақы төлеу Нұсқаулығын бекіту туралы" Жалағаш аудандық мәслихатының 2009 жылғы 24 қыркүйектегі N 20-3 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/60620/rus
