act_code: '48077'
requisite: Қызылорда облысы Жалағаш аудандық мәслихатының 2009 жылғы 24 қыркүйектегі N 20-3 шешімі. Қызылорда облысының Әділет департаменті Жалағаш ауданының Әділет басқармасында 2009 жылы 09 қазанда N 10-6-127 тіркелді. Күші жойылды - Қызылорда облысы Жалағаш аудандық мәслихатының 2012 жылғы 26 қыркүйектегі N 11-6 шешімімен
title:
  rus: Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік әлеуметтік қамсыздандыру, мәдениет, спорт ұйымдарының мамандарына және ауылдық жерде жұмыс істейтін мемлекеттік денсаулық сақтау, білім беру мамандарына отын сатып алуға жұмсалатын шығынды өтеу үшін өтемақы төлеу Нұсқаулығын бекіту туралы
  kaz: Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік әлеуметтік қамсыздандыру, мәдениет, спорт ұйымдарының мамандарына және ауылдық жерде жұмыс істейтін мемлекеттік денсаулық сақтау, білім беру мамандарына отын сатып алуға жұмсалатын шығынды өтеу үшін өтемақы төлеу Нұсқаулығын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-09-24
approved_by:
- '161006000002'
version_date:
  kaz: 2009-09-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/48077/kaz/24.09.2009
