act_code: '85629'
requisite: Решение от 18.12.2014 №37/1, Маслихат Кызылординской области
title:
  rus: '"О городском бюджете на 2015-2017 годы"'
  kaz: '"2015-2017 жылдарға арналған қалалық бюджет туралы "'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-18
approved_by:
- '161000000002'
version_date:
  kaz: 2014-12-18
  rus: 2014-12-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/85629/kaz/18.12.2014
  rus: https://zan.gov.kz/client/#!/doc/85629/rus/18.12.2014
