act_code: '49496'
requisite: Решение от 21.11.2009 №161, Маслихат Казалинского района
title:
  rus: Қазалы ауданы елді мекендерінің аумағын көріктендіру Ережесін бекіту туралы
  kaz: Қазалы ауданы елді мекендерінің аумағын көріктендіру Ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-11-21
approved_by:
- '161004000002'
version_date:
  kaz: 2009-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/49496/kaz/21.11.2009
