act_code: '9489'
requisite: Решение от 05.02.2000 №148, Аким Кызылординской области
title:
  rus: Облыста 2000 жылы шегіртке зиянкестерімен күресу шаралары туралы
  kaz: Облыста 2000 жылы шегіртке зиянкестерімен күресу шаралары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-02-05
approved_by:
- '161000000003'
version_date:
  kaz: 2000-02-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/9489/kaz/05.02.2000
