act_code: '118091'
requisite: Решение Казалинского районного маслихата Кызылординской области от 22 декабря 2017 года № 150. Зарегистрировано Департаментом юстиции Кызылординской области 9 января 2018 года № 6129. Утратило силу решением Казалинского районного маслихата Кызылординской области от 29 апреля 2021 года № 47
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсету, оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-22
approved_by:
- '161004000002'
version_date:
  kaz: 2019-01-14
  rus: 2019-01-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/118091/kaz/14.01.2019
  rus: https://zan.gov.kz/client/#!/doc/118091/rus/14.01.2019
caused_by:
  code: '128773'
  requisite: Решение Казалинского районного маслихата Кызылординской области от 14 января 2019 года № 260. Зарегистрировано Департаментом юстиции Кызылординской области 15 января 2019 года № 6653. Утратило силу решением Казалинского районного маслихата Кызылординской области от 29 апреля 2021 года № 47
  title:
    rus: О внесении изменений в решение Казалинского районного маслихата от 22 декабря 2017 года № 150 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: «Әлеуметтік көмек көрсету, оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау Қағидаларын бекіту туралы» Қазалы аудандық мәслихатының 2017 жылғы                                 22 желтоқсандағы № 150 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/128773/rus
