act_code: '90903'
requisite: Решение от 05.06.2015 №03, Акимат аульного округа Басыкара
title:
  rus: О переименовании некоторых улиц села Басыкара
  kaz: Басықара ауылындағы кейбір көшелерді қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-06-05
approved_by:
- '161004007001'
version_date:
  kaz: 2015-06-05
  rus: 2015-06-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/90903/kaz/05.06.2015
  rus: https://zan.gov.kz/client/#!/doc/90903/rus/05.06.2015
