act_code: '72339'
requisite: Решение Шиелийского районного маслихата Кызылординской области от 09 апреля 2013 года N 16/5. Зарегистрировано Департаментом юстиции Кызылординской области 03 мая 2013 года за N 4440. Утратило силу решением Шиелийского районного маслихата Кызылординской области от 20 июня 2013 года N 18/4
title:
  rus: Об оказании единовременной материальной помощи
  kaz: Біржолғы материалдық көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-04-09
approved_by:
- '161008000002'
version_date:
  kaz: 2013-04-09
  rus: 2013-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/72339/kaz/09.04.2013
  rus: https://zan.gov.kz/client/#!/doc/72339/rus/09.04.2013
