act_code: '163446'
requisite: Решение Аральского районного маслихата Кызылординской области от 29 декабря 2021 года № 186
title:
  rus: О бюджете сельского округа Аралкум на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Аралқұм ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-29
approved_by:
- '161003000002'
version_date:
  kaz: 2022-09-09
  rus: 2022-09-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/163446/kaz/09.09.2022
  rus: https://zan.gov.kz/client/#!/doc/163446/rus/09.09.2022
caused_by:
  code: '171845'
  requisite: Решение Аральского районного маслихата Кызылординской области от 9 сентября 2022 года № 286
  title:
    rus: О внесении изменений в решение Аральского районного маслихата Кызылординской области от 29 декабря 2021 года №186 «О бюджете сельского округа Аралкум на 2022-2024 годы»
    kaz: Қызылорда облысы Арал аудандық мәслихатының 2021 жылғы 29 желтоқсандағы №186 «2022-2024 жылдарға арналған Аралқұм ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/171845/rus
