act_code: '58750'
requisite: Решение акима кента Айтеке би Казалинского района Кызылординской области от 1 апреля 2011 года № 169. Зарегистрировано Управлением юстиции Казалинского района Кызылординской области 10 мая 2011 года за № 10-4-150
title:
  rus: О переименовании переулка улицы В.Счастнова в переулка Тастайбекова Мешитбая
  kaz: В.Счастнов көшесінің тұйығын Мешітбай Тастайбеков тұйығына өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-04-01
approved_by:
- '161004001001'
version_date:
  kaz: 2011-04-01
  rus: 2011-04-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/58750/kaz/01.04.2011
  rus: https://zan.gov.kz/client/#!/doc/58750/rus/01.04.2011
