act_code: '51457'
requisite: Қызылорда облысы Жалағаш аудандық мәслихатының 2010 жылғы 03 наурыздағы N 27-2 шешімі. Қызылорда облысының Әділет департаменті Жалағаш ауданының әділет басқармасында 2010 жылы 19 наурызда N 10-6-142 тіркелді. Күші жойылды - Қызылорда облысы Жалағаш аудандық мәслихатының 2012 жылғы 15 маусымдағы N 7-3 шешімімен
title:
  rus: Аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын үй көмегін көрсету Қағидасын бекіту туралы
  kaz: Аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын үй көмегін көрсету Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-03
approved_by:
- '161006000002'
version_date:
  kaz: 2011-09-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/51457/kaz/05.09.2011
caused_by:
  code: '60642'
  requisite: Решение Жалагашского районного маслихата Кызылординской области от 5 сентября 2011 года № 46-3. Зарегистрировано Департаментом юстиции Кызылординской области 28 сентября 2011 года за № 10-6-195. Утратило силу решением Жалагашского районного маслихата Кызылординской области от 15 июня 2012 года № 7-3
  title:
    rus: О внесении изменении в решение Жалагашского районного маслихата от 3 марта 2010 года N 27-2 "Об утверждении правил оказания жилищной помощи малообеспеченным семьям (гражданам)"
    kaz: '"Аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын үй көмегін көрсету Қағидасын бекіту туралы" Жалағаш аудандық мәслихатының 2010 жылғы 3 наурыздағы N 27-2 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/60642/rus
