act_code: '51457'
requisite: Қызылорда облысы Жалағаш аудандық мәслихатының 2010 жылғы 03 наурыздағы N 27-2 шешімі. Қызылорда облысының Әділет департаменті Жалағаш ауданының әділет басқармасында 2010 жылы 19 наурызда N 10-6-142 тіркелді. Күші жойылды - Қызылорда облысы Жалағаш аудандық мәслихатының 2012 жылғы 15 маусымдағы N 7-3 шешімімен
title:
  rus: Аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын үй көмегін көрсету Қағидасын бекіту туралы
  kaz: Аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын үй көмегін көрсету Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-03
approved_by:
- '161006000002'
version_date:
  kaz: 2010-03-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/51457/kaz/03.03.2010
