act_code: '152073'
requisite: Решение Аральского районного маслихата Кызылординской области от 31 декабря 2020 года № 458. Зарегистрировано Департаментом юстиции Кызылординской области 6 января 2021 года № 8105
title:
  rus: О бюджете поселка Саксаульск на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Сексеуіл кентінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-31
approved_by:
- '161003000002'
version_date:
  kaz: 2020-12-31
  rus: 2020-12-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/152073/kaz/31.12.2020
  rus: https://zan.gov.kz/client/#!/doc/152073/rus/31.12.2020
