act_code: '52363'
requisite: Қызылорда облысы Жаңақорған аудандық мәслихатының 2010 жылғы 09 сәуірдегі N 220 шешімі. Қызылорда облысының Әділет департаменті Жаңақорған ауданының Әділет басқармасында 2010 жылы 07 мамырда N 10-7-98 тіркелді. Күші жойылды - Қызылорда облысы Жаңақорған аудандық мәслихатының 2010 жылғы 24 желтоқсандағы N 281 шешімімен
title:
  rus: Біржолғы талон құнын белгілеу туралы
  kaz: Біржолғы талон құнын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-09
approved_by:
- '161009000002'
version_date:
  kaz: 2010-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/52363/kaz/09.04.2010
