act_code: '138702'
requisite: Решение Кармакшинского районного маслихата Кызылординской области от 27 декабря 2019 года № 289. Зарегистрировано Департаментом юстиции Кызылординской области 5 января 2020 года № 7179
title:
  rus: О бюджете сельского округа Жанажол на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Жаңажол ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-27
approved_by:
- '161005000002'
version_date:
  kaz: 2019-12-27
  rus: 2019-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/138702/kaz/27.12.2019
  rus: https://zan.gov.kz/client/#!/doc/138702/rus/27.12.2019
