act_code: '79639'
requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 10 апреля 2014 года № 222. Зарегистрировано Департаментом юстиции Кызылординской области 6 мая 2014 года № 4658. Утратило силу решением Сырдарьинского районного маслихата Кызылординской области от 27 декабря 2023 года № 78
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества Сырдарьинского района
  kaz: Сырдария ауданының бөлек жергілікті қоғамдастық жиындарын өткізудің Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-10
approved_by:
- '161007000002'
version_date:
  kaz: 2014-04-10
  rus: 2014-04-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/79639/kaz/10.04.2014
  rus: https://zan.gov.kz/client/#!/doc/79639/rus/10.04.2014
