act_code: '12109'
requisite: Решение от 20.03.2002 №84, Маслихат Кызылординской области
title:
  rus: Қызылорда облысында 2003-2007 жылдарға арналған кедейшiлiкпен күрес жөнiндегi аймақтық бағдарлама тұжырымдамасы туралы
  kaz: Қызылорда облысында 2003-2007 жылдарға арналған кедейшiлiкпен күрес жөнiндегi аймақтық бағдарлама тұжырымдамасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-03-20
approved_by:
- '161000000002'
version_date:
  kaz: 2002-03-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/12109/kaz/20.03.2002
