act_code: '214622'
requisite: Решение акима поселка Торетам Кармакшинского района Кызылординской области от 15 сентября 2025 года N 248
title:
  rus: О присвоении наименования улице поселка Торетам
  kaz: Төретам кентінің көшесіне  атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-15
approved_by:
- '161005002001'
version_date:
  kaz: 2025-09-15
  rus: 2025-09-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/214622/kaz/15.09.2025
  rus: https://zan.gov.kz/client/#!/doc/214622/rus/15.09.2025
