act_code: '58626'
requisite: Решение акима Тункерисского аульного округа Шиелийского района Кызылординской области от 14 апреля 2011 года № 16. Зарегистрировано Управлением юстиции Шиелийского района Кызылординской области 26 апреля 2011 года за № 10-9-201
title:
  rus: О предоставлении имени Кемелбека Макулбекова улице без названия в ауле Шеген Кодаманова
  kaz: Шеген Қодаманов ауылындағы атауы жоқ көшеге Кемелбек Мақұлбековтің есімін беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-04-14
approved_by:
- '161008022001'
version_date:
  kaz: 2011-04-14
  rus: 2011-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/58626/kaz/14.04.2011
  rus: https://zan.gov.kz/client/#!/doc/58626/rus/14.04.2011
