act_code: '181133'
requisite: Решение Кызылординского городского маслихата от 21 декабря 2022 года № 198-28/2
title:
  rus: О городском бюджете на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-21
approved_by:
- '161002000002'
version_date:
  kaz: 2023-04-28
  rus: 2023-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/181133/kaz/28.04.2023
  rus: https://zan.gov.kz/client/#!/doc/181133/rus/28.04.2023
caused_by:
  code: '180801'
  requisite: Решение Кызылординского городского маслихата от 28 апреля 2023 года № 9-2/1
  title:
    rus: О внесении изменений в решение Кызылординского городского маслихата от 21 декабря 2022 года №198-28/2 «О городском бюджете на 2023-2025 годы»
    kaz: Қызылорда қалалық мәслихатының 2022 жылғы 21 желтоқсандағы №198-28/2 «2023-2025 жылдарға арналған қалалық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/180801/rus
