act_code: '69731'
requisite: Решение Шиелийского районного маслихата Кызылординской области от 21 декабря 2012 года № 11/2. Зарегистрировано Департаментом юстиции Кызылординской области 08 января 2013 года за № 4383. Утратило силу решением Шиелийского районного маслихата Кызылординской области от 21 февраля 2014 года № 26/9
title:
  rus: О бюджете на 2013-2015 годы Шиелийского района
  kaz: Шиелі ауданының 2013-2015 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-21
approved_by:
- '161008000002'
version_date:
  rus: 2013-12-05
source:
  rus: https://zan.gov.kz/client/#!/doc/69731/rus/05.12.2013
caused_by:
  code: '75813'
  requisite: Решение Шиелийского районного маслихата Кызылординской области от 5 декабря 2013 года N 24/2. Зарегистрировано Департаментом юстиции Кызылординской области 10 декабря 2013 года за N 4554. Утратило силу решением Шиелийского районного маслихата Кызылординской области от 21 февраля 2014 года N 26/9
  title:
    rus: О внесении изменений в решение районного маслихата от 21 декабря 2012 года N 11/2 "О бюджете Шиелийского района на 2013-2015 годы"
    kaz: '"Шиелі ауданының 2013-2015 жылдарға арналған бюджеті туралы" аудандық мәслихаттың 2012 жылғы 21 желтоқсандағы N 11/2 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/75813/rus
