act_code: '113230'
requisite: Решение акима Сырдарьинского района Кызылординской области от 12 июня 2017 года № 7. Зарегистрировано Департаментом юстиции Кызылординской области 1 июля 2017 года № 5894. Утратило силу решением акима Сырдарьинского района Кызылординской области от 8 ноября 2018 года № 8
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-06-12
approved_by:
- '161007000003'
version_date:
  kaz: 2017-06-12
  rus: 2017-06-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/113230/kaz/12.06.2017
  rus: https://zan.gov.kz/client/#!/doc/113230/rus/12.06.2017
