act_code: '183175'
requisite: Решение акима сельского округа Теликоль Шиелийского района Кызылординской области от 13 июня 2023 года № 03-1/8. Зарегистрировано Департаментом юстиции Кызылординской области 19 июня 2023 года № 8426-11
title:
  rus: О присвоении наименовании безымянным улицам села А.Тажибаева сельского округа Теликоль
  kaz: Телікөл ауылдық округі Ә.Тәжібаев ауылының атауы жоқ көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-06-13
approved_by:
- '161008021002'
version_date:
  kaz: 2023-06-13
  rus: 2023-06-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/183175/kaz/13.06.2023
  rus: https://zan.gov.kz/client/#!/doc/183175/rus/13.06.2023
