act_code: '49501'
requisite: Решение от 22.12.2009 №25/2, Маслихат г. Кызылорды
title:
  rus: 2010-2012 жылдарға арналған қалалық бюджет туралы
  kaz: 2010-2012 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-22
approved_by:
- '161002000002'
version_date:
  kaz: 2009-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/49501/kaz/22.12.2009
