act_code: '126316'
requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 19 ноября 2018 года № 244. Зарегистрировано Департаментом юстиции Кызылординской области 27 ноября 2018 года № 6537. Утратило силу решением Сырдарьинского районного маслихата Кызылординской области от 20 декабря 2018 года № 260
title:
  rus: Об утверждении порядка и размера оказания социальной поддержки по приобретению топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Сырдарьинского района
  kaz: Сырдария ауданының ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына отын сатып алу бойынша әлеуметтік қолдау көрсетудің тәртібі мен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-19
approved_by:
- '161007000002'
version_date:
  kaz: 2018-11-19
  rus: 2018-11-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/126316/kaz/19.11.2018
  rus: https://zan.gov.kz/client/#!/doc/126316/rus/19.11.2018
