act_code: '43714'
requisite: Решение от 23.12.2008 №109, Маслихат Казалинского района
title:
  rus: Базарларда, сауда қатарлары мен белгіленген орындарда тауар сатуға және түрлі кәсіпкерлік қызметпен айналысатын тұлғаларға құқық беретін бір жолғы талондардың құнын белгілеу туралы
  kaz: Базарларда, сауда қатарлары мен белгіленген орындарда тауар сатуға және түрлі кәсіпкерлік қызметпен айналысатын тұлғаларға құқық беретін бір жолғы талондардың құнын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-23
approved_by:
- '161004000002'
version_date:
  kaz: 2008-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/43714/kaz/23.12.2008
