act_code: '139486'
requisite: Решение акима поселка Жанакорган Жанакорганского района Кызылординской области от 5 февраля 2020 года № 988. Зарегистрировано Департаментом юстиции Кызылординской области 6 февраля 2020 года № 7238
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-02-05
approved_by:
- '161009001001'
version_date:
  kaz: 2020-02-05
  rus: 2020-02-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/139486/kaz/05.02.2020
  rus: https://zan.gov.kz/client/#!/doc/139486/rus/05.02.2020
