act_code: '214106'
requisite: Решение акима сельского округа Кызылжарма города Кызылорда Кызылординской области от 04 сентября 2025 года N 142
title:
  rus: О наименовании улиц в сельском округе Кызылжарма
  kaz: Қызылжарма ауылдық округі бойынша көше атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-04
approved_by:
- '161002001002'
version_date:
  kaz: 2025-09-04
  rus: 2025-09-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/214106/kaz/04.09.2025
  rus: https://zan.gov.kz/client/#!/doc/214106/rus/04.09.2025
