act_code: '122744'
requisite: Решение Шиелийского районного маслихата Кызылординской области от 31 мая 2018 года № 24/7. Зарегистрировано Департаментом юстиции Кызылординской области 18 июня 2018 года № 6328
title:
  rus: Об утверждении Регламента собрания местного сообщества сельского округа Бестам Шиелийского района
  kaz: Шиелі ауданы Бестам ауылдық округінің жергілікті қоғамдастық жиналысының Регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-05-31
approved_by:
- '161008000002'
version_date:
  kaz: 2023-11-23
  rus: 2023-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/122744/kaz/23.11.2023
  rus: https://zan.gov.kz/client/#!/doc/122744/rus/23.11.2023
caused_by:
  code: '189691'
  requisite: Решение Шиелийского районного маслихата Кызылординской области от 23 ноября 2023 года № 8/24
  title:
    rus: О внесении изменений в решение Шиелийского районного маслихата от 31 мая 2018 года №24/7 «Об утверждении Регламента собрания местного сообщества сельского округа Бестам Шиелийского района»
    kaz: «Шиелі ауданы Бестам ауылдық округінің жергілікті қоғамдастық жиналысының Регламентін бекіту туралы» Шиелі аудандық мәслихатының 2018 жылғы 31 мамырдағы № 24/7 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/189691/rus
