act_code: '97154'
requisite: Решение Кармакшинского районного маслихата Кызылординской области от 23 декабря 2015 года № 308. Зарегистрировано Департаментом юстиции Кызылординской области 30 декабря 2015 года № 5279
title:
  rus: О районном бюджете на 2016-2018 годы
  kaz: 2016-2018 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-23
approved_by:
- '161005000002'
version_date:
  kaz: 2016-04-12
  rus: 2016-04-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/97154/kaz/12.04.2016
  rus: https://zan.gov.kz/client/#!/doc/97154/rus/12.04.2016
caused_by:
  code: '101543'
  requisite: Решение Кармакшинского районного маслихата Кызылординской области от 12 апреля 2016 года № 9. Зарегистрировано Департаментом юстиции Кызылординской области 19 апреля 2016 года № 5475
  title:
    rus: О внесении изменений и дополнений в решение Кармакшинского районного маслихата от 23 декабря 2015 года № 308 "О районном бюджете на 2016-2018 годы"
    kaz: '"2016-2018 жылдарға арналған аудандық бюджет туралы" Қармақшы аудандық мәслихатының 2015 жылғы 23 желтоқсандағы № 308 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/101543/rus
