act_code: '122348'
requisite: Решение Аральского районного маслихата Кызылординской области от 23 мая 2018 года № 157. Зарегистрировано Департаментом юстиции Кызылординской области 5 июня 2018 года № 6309
title:
  rus: Об утверждении Регламента собрания местного сообщества Камыстыбасского сельского округа Аральского района
  kaz: Арал ауданы Қамыстыбас ауылдық округінің жергiлiктi қоғамдастық жиналысының регламентiн бекiту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-05-23
approved_by:
- '161003000002'
version_date:
  kaz: 2021-07-22
  rus: 2021-07-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/122348/kaz/22.07.2021
  rus: https://zan.gov.kz/client/#!/doc/122348/rus/22.07.2021
caused_by:
  code: '157298'
  requisite: Решение Аральского районного маслихата Кызылординской области от 22 июля 2021 года № 87
  title:
    rus: «О внесении изменений в решение Аральского районного маслихата от 23 мая 2018 года №157 «Об утверждении Регламента собрания местного сообщества сельского округа Камыстыбас Аральского района»
    kaz: «Арал ауданы Қамыстыбас ауылдық округінің жергілікті қоғамдастық жиналысының Регламентін бекіту туралы» Арал аудандық мәслихатының 2018 жылғы 23 мамырдағы №157 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/157298/rus
