act_code: '62151'
requisite: Решение Жанакорганского районного маслихата Кызылординской области от 20 декабря 2011 года № 385. Зарегистрировано Департаментом юстиции Кызылординской области 23 декабря 2011 года за № 10-7-147. Утратило силу в связи с истечением срока применения - (письмо Жанакорганского районного маслихата Кызылординской области от 31 января 2013 года № 24)
title:
  rus: О районном бюджете на 2012-2014 годы
  kaz: 2012-2014 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-20
approved_by:
- '161009000002'
version_date:
  kaz: 2011-12-20
  rus: 2011-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/62151/kaz/20.12.2011
  rus: https://zan.gov.kz/client/#!/doc/62151/rus/20.12.2011
