act_code: '44265'
requisite: Решение от 25.12.2008 №18, Акимат Сырдарьинского района
title:
  rus: Сырдария ауданы бойынша азаматтарды шақыру учаскесіне тіркеуді ұйымдастыру туралы
  kaz: Сырдария ауданы бойынша азаматтарды шақыру учаскесіне тіркеуді ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-25
approved_by:
- '161007000001'
version_date:
  kaz: 2008-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/44265/kaz/25.12.2008
