act_code: '49366'
requisite: Решение от 24.11.2009 №30, Акимат Жанакорганского района
title:
  rus: Аудан көлемінде 1993 жылы туылғандарды және бұрын тіркеуден өтпеген азаматтарды аудандық шақыру учаскесіне тіркеуге алу жұмыстарын жүргізу туралы
  kaz: Аудан көлемінде 1993 жылы туылғандарды және бұрын тіркеуден өтпеген азаматтарды аудандық шақыру учаскесіне тіркеуге алу жұмыстарын жүргізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-11-24
approved_by:
- '161009000001'
version_date:
  kaz: 2009-11-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/49366/kaz/24.11.2009
