act_code: '192359'
requisite: Решение Кармакшинского районного маслихата Кызылординской области от 25 декабря 2023 года № 112
title:
  rus: О бюджете сельского округа Дауылколь на 2024-2026 годы
  kaz: 2024-2026 жылдарға арналған Дауылкөл ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-25
approved_by:
- '161005000002'
version_date:
  kaz: 2024-05-24
  rus: 2024-05-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/192359/kaz/24.05.2024
  rus: https://zan.gov.kz/client/#!/doc/192359/rus/24.05.2024
caused_by:
  code: '197472'
  requisite: Решение Кармакшинского районного маслихата Кызылординской области от 24 мая 2024 года № 175
  title:
    rus: О внесении изменений и дополнений в решение Кармакшинского районного маслихата Кызылординской области «О бюджете сельского округа Дауылколь на 2024-2026 годы» от 25 декабря 2023 года №112
    kaz: Қызылорда облысы Қармақшы аудандық мәслихатының 2023 жылғы 25 желтоқсандағы №112 «2024-2026 жылдарға арналған Дауылкөл ауылдық округінің бюджеті туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/197472/rus
