act_code: '37152'
requisite: Қызылорда облысы Жаңақорған ауданы әкімінің 2007 жылғы 28 желтоқсандағы № 38 шешімі. Қызылорда облысының Әділет басқармасында 2007 жылғы 29 желтоқсанда № 10-7-51 болып тіркелді
title:
  rus: Аудан көлемінде 1991 жылы туылғандарды және бұрын тіркеуден өтпеген азаматтарды аудандық қорғаныс істері жөніндегі бөліміне тіркеуге алу жұмыстарын жүргізу туралы
  kaz: Аудан көлемінде 1991 жылы туылғандарды және бұрын тіркеуден өтпеген азаматтарды аудандық қорғаныс істері жөніндегі бөліміне тіркеуге алу жұмыстарын жүргізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-28
approved_by:
- '161009000003'
version_date:
  kaz: 2007-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/37152/kaz/28.12.2007
