act_code: '46294'
requisite: Решение от 04.05.2009 №134, Маслихат Жанакорганского района
title:
  rus: Ауылдық елді мекендерде жұмыс істейтін және тұратын әлеуметтік сала мамандарына әлеуметтік көмек беру нұсқаулығын бекіту туралы
  kaz: Ауылдық елді мекендерде жұмыс істейтін және тұратын әлеуметтік сала мамандарына әлеуметтік көмек беру нұсқаулығын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-05-04
approved_by:
- '161009000002'
version_date:
  kaz: 2009-05-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/46294/kaz/04.05.2009
