act_code: '163453'
requisite: Решение Аральского районного маслихата Кызылординской области от 29 декабря 2021 года № 188
title:
  rus: О бюджете сельского округа Аманоткель на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Аманөткел ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-29
approved_by:
- '161003000002'
version_date:
  kaz: 2022-09-09
  rus: 2022-09-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/163453/kaz/09.09.2022
  rus: https://zan.gov.kz/client/#!/doc/163453/rus/09.09.2022
caused_by:
  code: '171837'
  requisite: Решение Аральского районного маслихата Кызылординской области от 9 сентября 2022 года № 288
  title:
    rus: О внесении изменений в решение Аральского районного маслихата Кызылординской области от 29 декабря 2021 года № 188 «О бюджете сельского округа Аманоткель на 2022-2024 годы»
    kaz: Қызылорда облысы Арал аудандық мәслихатының 2021 жылғы 29 желтоқсандағы № 188 «2022-2024 жылдарға арналған Аманөткел ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/171837/rus
