act_code: '57662'
requisite: Решение Кызылординского городского маслихата от 25 февраля 2011 года N 40/2-1. Зарегистрировано Департаментом юстиции Кызылординской области 11 марта 2011 года за N 10-1-170. Утратило силу решением Кызылординского городского маслихата от 16 июля 2013 года N 19/2
title:
  rus: О дополнительном регламентировании порядка проведения мирных собраний, митингов, шествий, пикетов и демонстраций
  kaz: Бейбіт жиналыстар, митингілер, шерулер, пикеттер және демонстрациялар өткізу тәртібін қосымша реттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-02-25
approved_by:
- '161002000002'
version_date:
  kaz: 2011-02-25
  rus: 2011-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/57662/kaz/25.02.2011
  rus: https://zan.gov.kz/client/#!/doc/57662/rus/25.02.2011
