act_code: '54852'
requisite: Решение от 09.09.2010 №26, Акимат аульного округа Сулутобе
title:
  rus: Сұлутөбе ауылдық округіне қарасты Бірлестік ауылындағы атауы жоқ көшеге Нәнсай атын беру туралы
  kaz: Сұлутөбе ауылдық округіне қарасты Бірлестік ауылындағы атауы жоқ көшеге Нәнсай атын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-09
approved_by:
- '161008015001'
version_date:
  kaz: 2010-09-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/54852/kaz/09.09.2010
