act_code: '206193'
requisite: Решение Казалинского районного маслихата Кызылординской области от 27 декабря 2024 года № 357
title:
  rus: О бюджете сельского округа Алга на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Алға ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '161004000002'
version_date:
  kaz: 2024-12-27
  rus: 2024-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/206193/kaz/27.12.2024
  rus: https://zan.gov.kz/client/#!/doc/206193/rus/27.12.2024
