act_code: '37167'
requisite: Қызылорда облысы Жалағаш аудандық мәслихатының 2007 жылғы 19 желтоқсандағы № 4-7 шешімі. Қызылорда облысының Әділет басқармасында 2008 жылғы 4 қаңтарда № 10-6-80 болып тіркелді
title:
  rus: Аудан бойынша сыртқы (көрнекті) жарнама обьектілерін елді мекендерде орналастырғаны үшін төленетін төлемақы мөлшерін бекіту туралы
  kaz: Аудан бойынша сыртқы (көрнекті) жарнама обьектілерін елді мекендерде орналастырғаны үшін төленетін төлемақы мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-19
approved_by:
- '161006000002'
version_date:
  kaz: 2007-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/37167/kaz/19.12.2007
