act_code: '8352'
requisite: Решение от 01.07.2000 №253, Аким Кызылординской области
title:
  rus: Облыстағы заңгерлік қызмет пен құқықтық оқудың жайы туралы
  kaz: Облыстағы заңгерлік қызмет пен құқықтық оқудың жайы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-06-30
approved_by:
- '161000000003'
version_date:
  kaz: 2000-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/8352/kaz/30.06.2000
