act_code: '50225'
requisite: Решение от 25.12.2009 №38, Акимат аульного округа Аксу
title:
  rus: Ақсу ауылдық округіндегі көшенің атауын өзгерту туралы
  kaz: Ақсу ауылдық округіндегі көшенің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '161006013001'
version_date:
  kaz: 2009-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/50225/kaz/25.12.2009
