act_code: '51574'
requisite: Қызылорда облысы Шиелі аудандық мәслихатының 2010 жылғы 26 наурыздағы N 29/2 шешімі. Қызылорда облысының Әділет департаменті Шиелі ауданының әділет басқармасында 2010 жылы 01 сәуірде N 10-9-111 тіркелді. Күші жойылды - Қызылорда облысы Шиелі аудандық мәслихатының 2013 жылғы 04 қаңтардағы N 12/2 шешімімен
title:
  rus: Бір жолғы талон құнын белгілеу туралы
  kaz: Бір жолғы талон құнын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-26
approved_by:
- '161008000002'
version_date:
  kaz: 2010-03-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/51574/kaz/26.03.2010
