act_code: '52654'
requisite: Решение от 05.05.2010 №295, Акимат Жалагашского района
title:
  rus: Жалағаш кентіндегі М. Горький көшесін қайта атау туралы
  kaz: Жалағаш кентіндегі М. Горький көшесін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-05-05
approved_by:
- '161006000001'
version_date:
  kaz: 2010-05-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/52654/kaz/05.05.2010
