act_code: '56520'
requisite: Решение от 02.12.2010 №36, Акимат аульного округа ІІІ Интернационал
title:
  rus: ІІІ Интернационал ауылындағы көшелердің атауын өзгерту туралы
  kaz: ІІІ Интернационал ауылындағы көшелердің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-02
approved_by:
- '161005010001'
version_date:
  kaz: 2010-12-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/56520/kaz/02.12.2010
