act_code: '162789'
requisite: Решение Кармакшинского районного маслихата Кызылординской области от 23 декабря 2021 года № 125
title:
  rus: О бюджете сельского округа Куандария на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Қуандария ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-23
approved_by:
- '161005000002'
version_date:
  kaz: 2022-08-17
  rus: 2022-08-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/162789/kaz/17.08.2022
  rus: https://zan.gov.kz/client/#!/doc/162789/rus/17.08.2022
caused_by:
  code: '170792'
  requisite: Решение Кармакшинского районного маслихата Кызылординской области от 17 августа 2022 года № 215
  title:
    rus: О внесении изменений в решение Кармакшинского районного маслихата Кызылординской области от 23 декабря 2021 года №125 «О бюджете сельского округа Куандария на 2022-2024 годы»
    kaz: Қызылорда облысы Қармақшы аудандық мәслихатының 2021 жылғы 23 желтоқсандағы №125 «2022-2024 жылдарға арналған Қуандария ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/170792/rus
