act_code: '163728'
requisite: Решение Шиелийского районного маслихата Кызылординской области от 30 декабря 2021 года № 18/14
title:
  rus: О бюджете сельского округа Тартогай на 2022-2024 годы
  kaz: Тартоғай ауылдық округінің 2022-2024 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '161008000002'
version_date:
  kaz: 2022-04-08
  rus: 2022-04-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/163728/kaz/08.04.2022
  rus: https://zan.gov.kz/client/#!/doc/163728/rus/08.04.2022
caused_by:
  code: '166461'
  requisite: Решение Шиелийского районного маслихата Кызылординской области от 8 апреля 2022 года № 21/14
  title:
    rus: О внесении изменений в решение Шиелийского районного маслихата «О бюджете сельского округа Тартогай на 2022-2024 годы» от 30 декабря 2021 года № 18/14
    kaz: Шиелі аудандық мәслихатының 2021 жылғы 30 желтоқсандағы «Тартоғай ауылдық округінің 2022-2024 жылдарға арналған бюджеті туралы» № 18/14 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/166461/rus
