act_code: '43537'
requisite: Решение от 24.12.2008 №100, Маслихат Жанакорганского района
title:
  rus: Жаңақорған кентінің жерлерін аймақтарға бөлу жобасын (схемасын) және базалық ставкасының түзету коэффициенттерін бекіту туралы
  kaz: Жаңақорған кентінің жерлерін аймақтарға бөлу жобасын (схемасын) және базалық ставкасының түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-24
approved_by:
- '161009000002'
version_date:
  kaz: 2008-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/43537/kaz/24.12.2008
