act_code: '151757'
requisite: Решение Шиелийского районного маслихата Кызылординской области от 29 декабря 2020 года № 65/17. Зарегистрировано Департаментом юстиции Кызылординской области 5 января 2021 года № 8038
title:
  rus: О бюджете сельского округа Жулек на 2021-2023 годы
  kaz: Жөлек ауылдық округінің 2021-2023 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-29
approved_by:
- '161008000002'
version_date:
  kaz: 2021-07-23
  rus: 2021-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/151757/kaz/23.07.2021
  rus: https://zan.gov.kz/client/#!/doc/151757/rus/23.07.2021
caused_by:
  code: '157358'
  requisite: Решение Шиелийского районного маслихата Кызылординской области от 23 июля 2021 года № 9/19
  title:
    rus: О внесении изменения в решение Шиелийского районного маслихата от 29 декабря 2020 года №65/17 «О бюджете сельского округа Жулек на 2021-2023 годы»
    kaz: Шиелі аудандық мәслихатының 2020 жылғы 29 желтоқсандағы №65/17 «Жөлек ауылдық округінің 2021-2023 жылдарға арналған бюджеті туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/157358/rus
