act_code: '49832'
requisite: Решение от 24.12.2009 №24/3, Маслихат Шиелийского района
title:
  rus: Шиелі ауданының 2010-2012 жылдарға арналған бюджеті туралы
  kaz: Шиелі ауданының 2010-2012 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-24
approved_by:
- '161008000002'
version_date:
  kaz: 2009-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/49832/kaz/24.12.2009
