act_code: '214003'
requisite: Решение акима сельского округа Кердели Шиелийского района Кызылординской области от 08 сентября 2025 года № 04-9/289
title:
  rus: Кызылординская область, Шиелийский район, сельский округ Кердели о присвоении наименований безымянным кварталам села Н.Бекежанов
  kaz: Қызылорда облысы, Шиелі ауданы, Керделі ауылдық округі Н.Бекежанов ауылындағы атауы жоқ көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-08
approved_by:
- '161008020002'
version_date:
  kaz: 2025-09-08
  rus: 2025-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/214003/kaz/08.09.2025
  rus: https://zan.gov.kz/client/#!/doc/214003/rus/08.09.2025
