act_code: '56587'
requisite: Қызылорда облысы Жалағаш аудандық мәслихатының 2010 жылғы 24 желтоқсандағы N 37-1 шешімі. Қызылорда облысының Әділет департаменті Жалағаш аудандық әділет басқармасында 2011 жылы 10 қаңтарда N 10-6-175 тіркелді. Шешімнің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды (Қызылорда облысы Жалағаш аудандық мәслихатының 2012 жылғы 14 мамырдағы N 117 хаты)
title:
  rus: '"2011-2013 жылдарға арналған аудан бюджеті туралы"'
  kaz: '"2011-2013 жылдарға арналған аудан бюджеті туралы"'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '161006000002'
version_date:
  kaz: 2011-07-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/56587/kaz/12.07.2011
caused_by:
  code: '59759'
  requisite: Решение Жалагашского районного маслихата Кызылординской области от 12 июля 2011 года № 44-2. Зарегистрировано Департаментом юстиции Кызылординской области 21 июля 2011 года за № 10-6-189. Утратило силу в связи с истечением срока действия (письмо Жалагашского районного маслихата Кызылординской области от 14 мая 2012 года N 117)
  title:
    rus: О внесении изменений и дополнений в решение Жалагашского районного маслихата от 24 декабря 2010 года N 37-1 "О бюджете района на 2011-2013 годы"
    kaz: '"2011-2013 жылдарға арналған аудан бюджеті туралы" Жалағаш аудандық мәслихатының 2010 жылғы 24 желтоқсандағы N 37-1 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/59759/rus
