act_code: '56587'
requisite: Қызылорда облысы Жалағаш аудандық мәслихатының 2010 жылғы 24 желтоқсандағы N 37-1 шешімі. Қызылорда облысының Әділет департаменті Жалағаш аудандық әділет басқармасында 2011 жылы 10 қаңтарда N 10-6-175 тіркелді. Шешімнің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды (Қызылорда облысы Жалағаш аудандық мәслихатының 2012 жылғы 14 мамырдағы N 117 хаты)
title:
  rus: '"2011-2013 жылдарға арналған аудан бюджеті туралы"'
  kaz: '"2011-2013 жылдарға арналған аудан бюджеті туралы"'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '161006000002'
version_date:
  kaz: 2011-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/56587/kaz/27.04.2011
caused_by:
  code: '58548'
  requisite: Решение маслихата Костанайской области от 23 апреля 2011 года № 387. Зарегистрировано Департаментом юстиции Костанайской области 25 апреля 2011 года № 3758
  title:
    rus: О внесении изменений в решение маслихата от 13 декабря 2010 года № 357 "Об областном бюджете Костанайской области на 2011-2013 годы"
    kaz: Мәслихаттың 2010 жылғы 13 желтоқсандағы № 357 "Қостанай облысының 2011-2013 жылдарға арналған облыстық бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/58548/rus
