act_code: '50265'
requisite: Решение от 09.12.2009 №789, Аким поселка Шиели
title:
  rus: Шиелі кенті, "Көкшоқы" мөлтек ауданында орналасқан көшеге Әбілқасым Палымбетовтің есімін беру туралы
  kaz: Шиелі кенті, "Көкшоқы" мөлтек ауданында орналасқан көшеге Әбілқасым Палымбетовтің есімін беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-09
approved_by:
- '161008023001'
version_date:
  kaz: 2010-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/50265/kaz/28.12.2010
caused_by:
  code: '57089'
  requisite: Решение от 28.12.2010 №1105, Аким поселка Шиели
  title:
    rus: Шиелі кенті әкімінің 2009 жылғы 09 желтоқсандағы "Шиелі кенті "Көкшоқы" мөлтек ауданында орналасқан көшеге Әбілқасым Палымбетовтың есімін беру туралы" N 789 шешіміне өзгерістер енгізу туралы
    kaz: Шиелі кенті әкімінің 2009 жылғы 09 желтоқсандағы "Шиелі кенті "Көкшоқы" мөлтек ауданында орналасқан көшеге Әбілқасым Палымбетовтың есімін беру туралы" N 789 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/57089/rus
