act_code: '60478'
requisite: Решение акимата поселка Белкуль города Кызылорда от 10 августа 2011 года № 226. Зарегистрировано управлением юстиции города Кызылорда департамента юстиции Кызылординской области 8 сентября 2011 года за № 10-1-186
title:
  rus: О наименовании улиц и переулка поселка Белкуль и населенном пункте Бирказан
  kaz: Белкөл кенті және Бірқазан елді мекеніндегі көшелер мен тұйыққа атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-08-10
approved_by:
- '161002008001'
version_date:
  kaz: 2011-08-10
  rus: 2011-08-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/60478/kaz/10.08.2011
  rus: https://zan.gov.kz/client/#!/doc/60478/rus/10.08.2011
