act_code: '15569'
requisite: "Қызылорда қалалық әкімінің 2002 жылғы 25 желтоқсандағы N 2759 шешімі. \r\nҚызылорда облысының Әдiлет басқармасында 2003 жылғы 28 қаңтарда N 2869 тiркелдi. Күші жойылды - Қызылорда қаласы әкімінің 2012 жылғы 05 желтоқсандағы N 533 Шешімімен"
title:
  rus: Қоғамдық жұмыстарды ұйымдастыру тәртібін бекіту туралы
  kaz: Қоғамдық жұмыстарды ұйымдастыру тәртібін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-12-25
approved_by:
- '161002000001'
version_date:
  kaz: 2002-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/15569/kaz/25.12.2002
