act_code: '134148'
requisite: Решение Кармакшинского районного маслихата Кызылординской области от 14 августа 2019 года № 256. Зарегистрировано Департаментом юстиции Кызылординской области 16 августа 2019 года № 6892
title:
  rus: Об утверждении порядка и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах, а также педагогическим работникам сферы образования, работающим в сельской местности Кармакшинского района
  kaz: Қармақшы ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтiк қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына, сонымен қатар ауылдық жерде жұмыс істейтін білім беру саласының педагог қызметкерлеріне бюджет қаражаты есебiнен коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету тәртібін және мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-08-14
approved_by:
- '161005000002'
version_date:
  kaz: 2024-02-23
  rus: 2024-02-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/134148/kaz/23.02.2024
  rus: https://zan.gov.kz/client/#!/doc/134148/rus/23.02.2024
caused_by:
  code: '193879'
  requisite: Решение Кармакшинского районного маслихата Кызылординской области от 23 февраля 2024 года № 128. Зарегистрировано Департаментом юстиции Кызылординской области 28 февраля 2024 года № 8495-11
  title:
    rus: О внесении изменений в решение Кармакшинского районного маслихата от 14 августа 2019 года № 256 «Об утверждении порядка и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах, а также педагогическим работникам образования, работающим в сельской местности»
    kaz: «Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтiк қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына, сонымен қатар ауылдық жерде жұмыс істейтін білім беру саласының педагог қызметкерлеріне бюджет қаражаты есебiнен коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету тәртібін және мөлшерін бекіту туралы» Қармақшы аудандық мәслихатының 2019 жылғы 14 тамыздағы № 256 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/193879/rus
