act_code: '78098'
requisite: Решение Кызылординского городского маслихата от 18 февраля 2014 года N 26/2. Зарегистрировано Департаментом юстиции Кызылординской области 20 марта 2014 года N 4621. Утратило силу решением Кызылординского городского маслихата от 27 ноября 2014 года N 36/4
title:
  rus: Об утверждении правил проведения раздельных сходов местного сообщества
  kaz: Бөлек жергілікті қоғамдастық жиындарын өткізудің қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-02-18
approved_by:
- '161002000002'
version_date:
  kaz: 2014-02-18
  rus: 2014-02-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/78098/kaz/18.02.2014
  rus: https://zan.gov.kz/client/#!/doc/78098/rus/18.02.2014
