act_code: '40892'
requisite: Қызылорда облысы Жаңақорған аудандық мәслихатының 2008 жылғы 24 маусымдағы кезекті VI сессиясының N 64 шешімі. Қызылорда облысының Әділет департаменті Жаңақорған аудандық Әділет басқармасында 2008 жылы 30 шілдеде N 10-7-59 тіркелді. Қолданылу мерзімінің аяқталуына байланысты күші жойылды -  (Қызылорда облысы Жаңақорған аудандық мәслихатының 2012 жылғы 05 маусымдағы N 119 хатымен)
title:
  rus: Аз қамтамасыз етілген азаматтарға тұрғын үйді ұстауға және коммуналдық қызметтің ақысын төлеуге арналған тұрғын үй көмегін беру Қағидасы мен коммуналдық шығындар мөлшерінің нормаларын бекіту туралы
  kaz: Аз қамтамасыз етілген азаматтарға тұрғын үйді ұстауға және коммуналдық қызметтің ақысын төлеуге арналған тұрғын үй көмегін беру Қағидасы мен коммуналдық шығындар мөлшерінің нормаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-06-24
approved_by:
- '161009000002'
version_date:
  kaz: 2008-06-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/40892/kaz/24.06.2008
