act_code: '137986'
requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 27 декабря 2019 года № 373. Зарегистрировано Департаментом юстиции Кызылординской области 30 декабря 2019 года № 7081
title:
  rus: О бюджете сельского округа Ширкейли на 2020-2022 годы
  kaz: 2020–2022 жылдарға арналған Шіркейлі ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-27
approved_by:
- '161007000002'
version_date:
  kaz: 2019-12-27
  rus: 2019-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/137986/kaz/27.12.2019
  rus: https://zan.gov.kz/client/#!/doc/137986/rus/27.12.2019
