act_code: '54064'
requisite: Қызылорда облысы Шиелі аудандық мәслихатының 2010 жылғы 13 шілдедегі N 34/3 шешімі. Қызылорда облысының Әділет департаменті Шиелі ауданының Әділет басқармасында 2010 жылы 18 тамызда N 10-9-127 тіркелді. Күші жойылды - Қызылорда облысы Шиелі аудандық мәслихатының 2012 жылғы 15 қарашадағы N 9/6 Шешімімен
title:
  rus: Шиелі ауданы ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет және спорт ұйымдарының мамандарына отын сатып алу үшін әлеуметтік көмек көрсету туралы
  kaz: Шиелі ауданы ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет және спорт ұйымдарының мамандарына отын сатып алу үшін әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-13
approved_by:
- '161008000002'
version_date:
  kaz: 2010-07-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/54064/kaz/13.07.2010
