act_code: '56230'
requisite: Решение от 17.11.2010 №1071, Аким поселка Шиели
title:
  rus: Шиелі кентінің Шығыс беткейінен жаңадан ашылған мөлтек ауданға "Шұғыла" атауын беру туралы
  kaz: Шиелі кентінің Шығыс беткейінен жаңадан ашылған мөлтек ауданға "Шұғыла" атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-17
approved_by:
- '161008023001'
version_date:
  kaz: 2010-11-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/56230/kaz/17.11.2010
