act_code: '128320'
requisite: Решение Шиелийского районного маслихата Кызылординской области от 28 декабря 2018 года № 34/12. Зарегистрировано Департаментом юстиции Кызылординской области 28 декабря 2018 года № 6619
title:
  rus: О бюджете сельского округа Алмалы на 2019-2021 годы
  kaz: Алмалы ауылдық округінің 2019–2021 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-28
approved_by:
- '161008000002'
version_date:
  kaz: 2019-03-19
  rus: 2019-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/128320/kaz/19.03.2019
  rus: https://zan.gov.kz/client/#!/doc/128320/rus/19.03.2019
caused_by:
  code: '130013'
  requisite: Решение Шиелийского районного маслихата Кызылординской области от 19 марта 2019 года № 38/4. Зарегистрировано Департаментом юстиции Кызылординской области 20 марта 2019 года № 6741
  title:
    rus: О внесении изменений в решение Шиелийского районного маслихата от 28 декабря 2018 года №34/12 «О бюджете сельского округа Алмалы на 2019-2021 годы»
    kaz: «2019-2021 жылдарға арналған Алмалы ауылдық округінің бюджеті туралы» Шиелі аудандық мәслихатының 2018 жылғы 28 желтоқсандағы №34/12 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/130013/rus
