act_code: '137973'
requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 27 декабря 2019 года № 374. Зарегистрировано Департаментом юстиции Кызылординской области 30 декабря 2019 года № 7078
title:
  rus: О бюджете сельского округа Сакен Сейфуллин на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Сәкен Сейфуллин ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-27
approved_by:
- '161007000002'
version_date:
  kaz: 2020-11-17
  rus: 2020-11-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/137973/kaz/17.11.2020
  rus: https://zan.gov.kz/client/#!/doc/137973/rus/17.11.2020
caused_by:
  code: '148796'
  requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 17 ноября 2020 года № 449. Зарегистрировано Департаментом юстиции Кызылординской области 20 ноября 2020 года № 7792
  title:
    rus: О внесении изменений в решение Сырдарьинского районного маслихата от 27 декабря 2019 года № 374 «О бюджете сельского округа Сакен Сейфуллина на 2020-2022 годы»
    kaz: «2020 – 2022 жылдарға арналған Сәкен Сейфуллин ауылдық округінің бюджеті туралы» Сырдария аудандық мәслихатының 2019 жылғы 27 желтоқсандағы № 374 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/148796/rus
