act_code: '137973'
requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 27 декабря 2019 года № 374. Зарегистрировано Департаментом юстиции Кызылординской области 30 декабря 2019 года № 7078
title:
  rus: О бюджете сельского округа Сакен Сейфуллин на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Сәкен Сейфуллин ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-27
approved_by:
- '161007000002'
version_date:
  kaz: 2020-03-18
  rus: 2020-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/137973/kaz/18.03.2020
  rus: https://zan.gov.kz/client/#!/doc/137973/rus/18.03.2020
caused_by:
  code: '140834'
  requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 18 марта 2020 года № 396. Зарегистрировано Департаментом юстиции Кызылординской области 19 марта 2020 года № 7316
  title:
    rus: О внесении изменений в решение Сырдарьинского районного маслихата от 27 декабря 2019 года №374 «О бюджете сельского округа Сакен Сейфуллина на 2020-2022 годы»
    kaz: «2020–2022 жылдарға арналған Сәкен Сейфуллин ауылдық округінің бюджеті туралы» Сырдария аудандық мәслихаттың 2019 жылғы 27 желтоқсандағы №374 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/140834/rus
