act_code: '144556'
requisite: Решение Шиелийского районного маслихата Кызылординской области от 25 июня 2020 года № 55/3. Зарегистрировано Департаментом юстиции Кызылординской области 2 июля 2020 года № 7558
title:
  rus: Об определении специализированных мест для организации и проведения мирных собраний, порядка их использования и норм их предельной заполняемости, требований к материально-техническому и организационному обеспечению специализированных мест, а также границ прилегающих территорий, в которых запрещено проведение пикетирования
  kaz: Бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, олардың пайдалану тәртібі мен шекті толу нормаларын, материалдық – техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптарды, сондай-ақ пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекараларын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-25
approved_by:
- '161008000002'
version_date:
  kaz: 2024-08-02
  rus: 2024-08-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/144556/kaz/02.08.2024
  rus: https://zan.gov.kz/client/#!/doc/144556/rus/02.08.2024
caused_by:
  code: '199586'
  requisite: Решение Шиелийского районного маслихата Кызылординской области от 2 августа 2024 года № 18/4. Зарегистрировано Департаментом юстиции Кызылординской области 8 августа 2024 года № 8545-11
  title:
    rus: О внесении изменений в решение Шиелийского районного маслихата от 25 июня 2020 года № 55/3 «Об определении специализированных мест для организации и проведения мирных собраний, порядка их использования и норм их предельной заполняемости, требований к материально-техническому и организационному обеспечению специализированных мест, а также границ прилегающих территорий, в которых запрещено проведение пикетирования»
    kaz: «Бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, олардың пайдалану тәртібі мен шекті толу нормаларын, материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптарды, сондай-ақ пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекараларын айқындау туралы» Шиелі аудандық мәслихатының 2020 жылғы 25 маусымдағы № 55/3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/199586/rus
