act_code: '39877'
requisite: Решение от 14.05.2008 №301, Акимат аульного округа Кыркенсе
title:
  rus: '"Көше атауларын өзгерту туралы"'
  kaz: '"Көше атауларын өзгерту туралы"'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-05-14
approved_by:
- '161009007001'
version_date:
  kaz: 2008-05-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/39877/kaz/14.05.2008
