act_code: '62519'
requisite: Решение Кармакшинского районного маслихата Кызылординской области от 20 декабря 2011 года № 310. Зарегистрировано Департаментом юстиции Кызылординской области 30 декабря 2011 года за № 10-5-173. Прекращено действие по истечении срока действия (письмо Кармакшинского районного маслихата Кызылординской области от 30 января 2013 года № 12)
title:
  rus: О районном бюджете на 2012-2014 годы
  kaz: 2012-2014 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-20
approved_by:
- '161005000002'
version_date:
  kaz: 2012-03-14
  rus: 2012-03-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/62519/kaz/14.03.2012
  rus: https://zan.gov.kz/client/#!/doc/62519/rus/14.03.2012
caused_by:
  code: '64204'
  requisite: Решение Кармакшинского районного маслихата Кызылординской области от 14 марта 2012 года № 15. Зарегистрировано Департаментом юстиции Кызылординской области 27 марта 2012 года № 10-5-177
  title:
    rus: О внесении изменений и дополнений в решение очередной 47-сессии Кармакшинского районного маслихата от 20 декабря 2011 года N 310 "О районном бюджете на 2012-2014 годы"
    kaz: '"2012-2014 жылдарға арналған аудандық бюджет туралы" Қармақшы аудандық мәслихатының 2011 жылғы 20 желтоқсандағы кезекті 47-сессиясының N 310 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/64204/rus
