act_code: '125038'
requisite: Решение акима сельского округа Кердели Шиелийского района Кызылординской области от 27 сентября 2018 года № 134. Зарегистрировано Департаментом юстиции Кызылординской области 8 октября 2018 года № 6450
title:
  rus: О присвоении наименования улице
  kaz: Көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-09-27
approved_by:
- '161008020002'
version_date:
  kaz: 2018-09-27
  rus: 2018-09-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/125038/kaz/27.09.2018
  rus: https://zan.gov.kz/client/#!/doc/125038/rus/27.09.2018
