act_code: '123231'
requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 15 июня 2018 года № 212. Зарегистрировано Департаментом юстиции Кызылординской области 3 июля 2018 года № 6354. Утратило силу решением Сырдарьинского районного маслихата Кызылординской области от 25 июля 2022 года № 152
title:
  rus: О повышении базовых ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения
  kaz: Пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының базалық мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-06-15
approved_by:
- '161007000002'
version_date:
  kaz: 2018-06-15
  rus: 2018-06-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/123231/kaz/15.06.2018
  rus: https://zan.gov.kz/client/#!/doc/123231/rus/15.06.2018
