act_code: '163975'
requisite: Решение Жалагашского районного маслихата Кызылординской области от 29 декабря 2021 года № 13-13
title:
  rus: О бюджете сельского округа Мырзабай ахун на 2022-2024 годы
  kaz: 2022 – 2024 жылдарға арналған Мырзабай ахун ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-29
approved_by:
- '161006000002'
version_date:
  kaz: 2022-04-14
  rus: 2022-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/163975/kaz/14.04.2022
  rus: https://zan.gov.kz/client/#!/doc/163975/rus/14.04.2022
caused_by:
  code: '166774'
  requisite: Решение Жалагашского районного маслихата Кызылординской области от 14 апреля 2022 года № 17-3
  title:
    rus: О внесении изменений в решение Жалагашского районного маслихата от 29 декабря 2021 года №13-13 «О бюджете сельского округа Мырзабай ахун на 2022-2024 годы»
    kaz: «2022 – 2024 жылдарға арналған Мырзабай ахун ауылдық округінің бюджеті туралы» Жалағаш аудандық мәслихатының 2021 жылғы 29 желтоқсандағы №13-13 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/166774/rus
