act_code: '94856'
requisite: Решение Жалагашского районного маслихата Кызылординской области от 23 сентября 2015 года № 46-4. Зарегистрировано Департаментом юстиции Кызылординской области 22 октября 2015 года № 5189. Утратило силу решением Жалагашского районного маслихата Кызылординской области от 1.8.2016 № 5-3.
title:
  rus: О возмещении затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану
  kaz: Мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарды өндіру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-09-23
approved_by:
- '161006000002'
version_date:
  kaz: 2015-09-23
  rus: 2015-09-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/94856/kaz/23.09.2015
  rus: https://zan.gov.kz/client/#!/doc/94856/rus/23.09.2015
