act_code: '164177'
requisite: Решение Жанакорганского районного маслихата Кызылординской области от 30 декабря 2021 года № 176
title:
  rus: О бюджете сельского округа Косуйенки на 2022-2024 годы
  kaz: Қосүйеңкі ауылдық округінің 2022-2024 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '161009000002'
version_date:
  kaz: 2022-04-18
  rus: 2022-04-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/164177/kaz/18.04.2022
  rus: https://zan.gov.kz/client/#!/doc/164177/rus/18.04.2022
caused_by:
  code: '167554'
  requisite: Решение Жанакорганского районного маслихата Кызылординской области от 18 апреля 2022 года № 217
  title:
    rus: О внесении изменений в решение Жанакорганского районного маслихата «О бюджете сельского округа Косуйенки на 2022-2024 годы» от 30 декабря 2021 года №176
    kaz: «Қосүйеңкі ауылдық округінің 2022-2024 жылдарға арналған бюджеті туралы» Жаңақорған аудандық мәслихатының 2021 жылғы 30 желтоқсандағы №176 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/167554/rus
