act_code: '53561'
requisite: Қызылорда облысы Жалағаш аудандық мәслихатының 2010 жылғы 16 маусымдағы № 31-4 шешімі. Қызылорда облысының Әділет департаменті Жалағаш ауданының әділет басқармасында 2010 жылы 15 шілдеде № 10-6-162 болып тіркелді
title:
  rus: Жалағаш ауданы бойынша салық салу мақсатында жерлерді аймақтарға бөлу жобасын (схемасын) және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффиценттерін бекіту туралы
  kaz: Жалағаш ауданы бойынша салық салу мақсатында жерлерді аймақтарға бөлу жобасын (схемасын) және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффиценттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-16
approved_by:
- '161006000002'
version_date:
  kaz: 2010-06-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/53561/kaz/16.06.2010
