act_code: '192762'
requisite: Решение Жанакорганского районного маслихата Кызылординской области от 29 декабря 2023 года № 145
title:
  rus: «О бюджете поселке Жанакорган на 2024-2026 годы»
  kaz: «Жаңақорған кентінің 2024-2026 жылдарға арналған бюджет туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-29
approved_by:
- '161009000002'
version_date:
  kaz: 2024-04-11
  rus: 2024-04-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/192762/kaz/11.04.2024
  rus: https://zan.gov.kz/client/#!/doc/192762/rus/11.04.2024
caused_by:
  code: '196058'
  requisite: Решение Жанакорганского районного маслихата Кызылординской области от 11 апреля 2024 года № 183
  title:
    rus: О внесении изменений в решение маслихата Жанакорганского района от 29 декабря 2023 года №145 «О бюджете поселке Жанакорган на 2024-2026 годы»
    kaz: «Жаңақорған кентінің 2024-2026 жылдарға арналған бюджет туралы» Жаңақорған ауданы маслихатының 2023 жылғы 29 желтоқсандағы №145 шешімініне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/196058/rus
