act_code: '125458'
requisite: Решение акима сельского округа Сарыкол Казалинского района Кызылординской области от 18 октября 2018 года № 12. Зарегистрировано Департаментом юстиции Кызылординской области 25 октября 2018 года № 6478
title:
  rus: О присвоении наименовании улице
  kaz: Көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-10-18
approved_by:
- '161004014002'
version_date:
  kaz: 2018-10-18
  rus: 2018-10-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/125458/kaz/18.10.2018
  rus: https://zan.gov.kz/client/#!/doc/125458/rus/18.10.2018
