act_code: '164068'
requisite: Решение Жанакорганского районного маслихата Кызылординской области от 30 декабря 2021 года № 161
title:
  rus: О бюджете поселка Шалхия на 2022-2024 годы
  kaz: Шалқия кентінің 2022-2024 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '161009000002'
version_date:
  kaz: 2022-08-11
  rus: 2022-08-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/164068/kaz/11.08.2022
  rus: https://zan.gov.kz/client/#!/doc/164068/rus/11.08.2022
caused_by:
  code: '170909'
  requisite: Решение Жанакорганского районного маслихата Кызылординской области от 11 августа 2022 года № 262
  title:
    rus: О внесении изменений в решение Жанакорганского районного маслихата от 30 декабря 2021 года №161 «О бюджете поселок Шалхия на 2022-2024 годы»
    kaz: Шалқия кентінің «2022-2024 жылдарға арналған бюджеті туралы» Жаңақорған аудандық мәслихатының 2021 жылғы 30 желтоқсандағы №161 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/170909/rus
