act_code: '143852'
requisite: Решение Жанакорганского районного маслихата Кызылординской области от 10 июня 2020 года № 464. Зарегистрировано Департаментом юстиции Кызылординской области 15 июня 2020 года № 7517
title:
  rus: Об установлении повышенных должностных окладов и тарифных ставок
  kaz: Жоғарылатылған лауазымдық айлықақылар мен тарифтiк мөлшерлемелер белгiлеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-10
approved_by:
- '161009000002'
version_date:
  kaz: 2020-06-10
  rus: 2020-06-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/143852/kaz/10.06.2020
  rus: https://zan.gov.kz/client/#!/doc/143852/rus/10.06.2020
