act_code: '55160'
requisite: Решение от 22.09.2010 №203, Маслихат Кармакшинского района
title:
  rus: 2010 жылға арналған  арнаулы салық режимінде жұмыс жасайтын кәсіпкерлердің бір салық салу объектісінен алынатын және аудан көлеміндегі қолданылатын жер салығы үшін алынатын алым мөлшерін бекіту туралы
  kaz: 2010 жылға арналған  арнаулы салық режимінде жұмыс жасайтын кәсіпкерлердің бір салық салу объектісінен алынатын және аудан көлеміндегі қолданылатын жер салығы үшін алынатын алым мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-22
approved_by:
- '161005000002'
version_date:
  kaz: 2010-09-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/55160/kaz/22.09.2010
