act_code: '219986'
requisite: Решение Казалинского районного маслихата Кызылординской области от 11 декабря 2025 года № 487
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Казалинского районного маслихата»
  kaz: «Қазалы аудандық мәслихат аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың Әдістемесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-11
approved_by:
- '161004000002'
version_date:
  kaz: 2025-12-11
  rus: 2025-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/219986/kaz/11.12.2025
  rus: https://zan.gov.kz/client/#!/doc/219986/rus/11.12.2025
