act_code: '54369'
requisite: Решение от 20.08.2010 №07, Акимат Аральского района
title:
  rus: Қызылжар ауылындағы көшелерге атау беру туралы
  kaz: Қызылжар ауылындағы көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-08-20
approved_by:
- '161003000001'
version_date:
  kaz: 2010-08-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/54369/kaz/20.08.2010
