act_code: '48215'
requisite: Қызылорда облысы Жалағаш ауданы мәслихатының 2009 жылғы 24 қыркүйектегі N 20-4 шешімі. Қызылорда облысының Әділет департаменті Жалағаш аудандық Әділет басқармасында 2009 жылғы 22 қазанда N 10-6-129 тіркелді. Күші жойылды - Қызылорда облысы Жалағаш аудандық мәслихатының 2011 жылғы 20 маусымдағы N 43-4 шешімімен
title:
  rus: Жалағаш ауданы аумағында иттер мен мысықтарды ұстау Нұсқаулығын бекіту туралы
  kaz: Жалағаш ауданы аумағында иттер мен мысықтарды ұстау Нұсқаулығын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-09-24
approved_by:
- '161006000002'
version_date:
  kaz: 2010-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/48215/kaz/31.03.2010
caused_by:
  code: '51662'
  requisite: Решение от 31.03.2010 №28-3, Маслихат Жалагашского района
  title:
    rus: Жалағаш аудандық мәслихатының кейбір шешімдеріне өзгерістер мен толықтырулар енгізу туралы
    kaz: Жалағаш аудандық мәслихатының кейбір шешімдеріне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/51662/rus
