act_code: '128335'
requisite: Решение Жанакорганского районного маслихата Кызылординской области от 27 декабря 2018 года № 300. Зарегистрировано Департаментом юстиции Кызылординской области 29 декабря 2018 года № 6632
title:
  rus: О бюджетах поселков и сельских округов на 2019-2021 года
  kaz: Кент және ауылдық округтердің 2019-2021 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-27
approved_by:
- '161009000002'
version_date:
  kaz: 2018-12-27
  rus: 2018-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/128335/kaz/27.12.2018
  rus: https://zan.gov.kz/client/#!/doc/128335/rus/27.12.2018
