act_code: '138110'
requisite: Решение Казалинского районного маслихата Кызылординской области от 26 декабря 2019 года № 364. Зарегистрировано Департаментом юстиции Кызылординской области 30 декабря 2019 года № 7103
title:
  rus: О бюджете сельского округа Майдакол на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Майдакөл ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-26
approved_by:
- '161004000002'
version_date:
  kaz: 2020-05-18
  rus: 2020-05-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/138110/kaz/18.05.2020
  rus: https://zan.gov.kz/client/#!/doc/138110/rus/18.05.2020
caused_by:
  code: '143152'
  requisite: Решение Казалинского районного маслихата Кызылординской области от 18 мая 2020 года № 418. Зарегистрировано Департаментом юстиции Кызылординской области 20 мая 2020 года № 7443
  title:
    rus: О внесении изменений и дополнений в решение Казалинского районного маслихата от 26 декабря 2019 года №364 «О бюджете сельского округа Майдакол на 2020-2022 годы»
    kaz: «2020-2022 жылдарға арналған Майдакөл ауылдық округінің бюджеті туралы» Қазалы аудандық мәслихатының 2019 жылғы 26 желтоқсандағы №364 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/143152/rus
