act_code: '42259'
requisite: Шиелі кенті әкімінің 2008 жылғы 24 қыркүйектегі N 202 шешімі. Шиелі аудандық Әділет басқармасының 2008 жылы 05 қарашада N 10-9-66 тіркелді.
title:
  rus: Шиелі кенті "Береке" мөлтек ауданында орналасқан атау берілмеген көшеге Өмірхан Жәрімбетовтің есімін беру туралы
  kaz: Шиелі кенті "Береке" мөлтек ауданында орналасқан атау берілмеген көшеге Өмірхан Жәрімбетовтің есімін беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-09-24
approved_by:
- '161008023001'
version_date:
  kaz: 2008-09-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/42259/kaz/24.09.2008
