act_code: '206710'
requisite: Решение Жанакорганского районного маслихата Кызылординской области от 25 декабря 2024 года № 320
title:
  rus: О бюджете сельского округа Кыраш на 2025-2027 годы
  kaz: Қыраш ауылдық округінің 2025-2027 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '161009000002'
version_date:
  kaz: 2025-07-16
  rus: 2025-07-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/206710/kaz/16.07.2025
  rus: https://zan.gov.kz/client/#!/doc/206710/rus/16.07.2025
caused_by:
  code: '212820'
  requisite: Решение Жанакорганского районного маслихата Кызылординской области от 16 июля 2025 года № 390
  title:
    rus: О внесении изменений в решение маслихата Жанакорганского района от 25 декабря 2024 года № 320 «О бюджете сельского округа Кыраш на 2025-2027 годы
    kaz: Кыраш ауылдық округінің 2025-2027 жылдарға арналған бюджеті туралы Жаңақорған аудандық мәслихатының 2024 жылғы 25 желтоқсандағы № 320 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/212820/rus
