act_code: '152032'
requisite: Решение Жанакорганского районного маслихата Кызылординской области от 30 декабря 2020 года № 594. Зарегистрировано Департаментом юстиции Кызылординской области 6 января 2021 года № 8087
title:
  rus: О бюджете сельского округа Жайылма на 2021-2023 годы
  kaz: Жайылма ауылдық округінің 2021-2023 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-30
approved_by:
- '161009000002'
version_date:
  kaz: 2021-03-25
  rus: 2021-03-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/152032/kaz/25.03.2021
  rus: https://zan.gov.kz/client/#!/doc/152032/rus/25.03.2021
caused_by:
  code: '154393'
  requisite: Решение Жанакорганского районного маслихата Кызылординской области от 25 марта 2021 года № 26. Зарегистрировано Департаментом юстиции Кызылординской области 2 апреля 2021 года № 8270
  title:
    rus: О внесении изменений в решение Жанакорганского районного маслихата от 30 декабря 2020 года №594 «О бюджете сельского округа Жайылма на 2021-2023 годы»
    kaz: «Жайылма ауылдық округінің 2021-2023 жылдарға арналған бюджеті туралы» Жаңақорған аудандық мәслихатының 2020 жылғы 30 желтоқсандағы №594 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/154393/rus
