act_code: '136657'
requisite: Решение Кармакшинского районного маслихата Кызылординской области от 3 декабря 2019 года № 272. Зарегистрировано Департаментом юстиции Кызылординской области 4 декабря 2019 года № 7002
title:
  rus: Об установлении повышенных должностных окладов и тарифных ставок
  kaz: Жоғарылатылған лауазымдық айлықақылар мен тарифтiк мөлшерлемелер белгiлеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-03
approved_by:
- '161005000002'
version_date:
  kaz: 2022-02-23
  rus: 2022-02-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/136657/kaz/23.02.2022
  rus: https://zan.gov.kz/client/#!/doc/136657/rus/23.02.2022
caused_by:
  code: '164971'
  requisite: Решение Кармакшинского районного маслихата Кызылординской области от 23 февраля 2022 года № 134. Зарегистрирован в Министерстве юстиции Республики Казахстан 2 марта 2022 года № 27004
  title:
    rus: О внесении изменения в решение Кармакшинского районного маслихата от 3 декабря 2019 года №272 «Об установлении повышенных должностных окладов и тарифных ставок»
    kaz: Қармақшы аудандық мәслихатының 2019 жылғы 3 желтоқсандағы №272 «Жоғарылатылған лауазымдық айлықақылар мен тарифтiк мөлшерлемелер белгiлеу туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/164971/rus
