act_code: '28521'
requisite: Қызылорда облысы Қармақшы ауданы ІІІ Интернационал ауылдық округінің әкімінің 2006 жылғы 13 наурыздағы № 16 шешімі. Қызылорда облысының Әділет басқармасында 2006 жылғы 5 сәуірде  № 10-5-46 болып тіркелді
title:
  rus: Ауылда көркейту, көгалдандыру және санитарлық тазалықтың 2 айлығын өткізу туралы
  kaz: Ауылда көркейту, көгалдандыру және санитарлық тазалықтың 2 айлығын өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-03-13
approved_by:
- '161005010002'
version_date:
  kaz: 2006-03-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/28521/kaz/13.03.2006
