act_code: '27993'
requisite: Решение от 20.04.2006 №282, Маслихат Кызылординской области
title:
  rus: Қызылорда облысының аумағында құрылыс салу Ережесін бекіту туралы
  kaz: Қызылорда облысының аумағында құрылыс салу Ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-04-20
approved_by:
- '161000000002'
version_date:
  kaz: 2010-07-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/27993/kaz/08.07.2010
caused_by:
  code: '54036'
  requisite: Қызылорда облыстық мәслихатының 2010 жылғы 8 шілдедегі N 240 шешімі. Қызылорда облыстық Әділет департаментінде 2010 жылғы 13 тамызда N 4254 тіркелді. Күші жойылды - Қызылорда облыстық мәслихатының 2013 жылғы 10 шілдедегі N 123 шешімімен
  title:
    rus: '"Қызылорда облысының аумағында құрылыс салу Ережесін бекіту туралы" Қызылорда облыстық мәслихатының 2006 жылғы 20 сәуірдегі N 282 шешіміне өзгеріс енгізу туралы'
    kaz: '"Қызылорда облысының аумағында құрылыс салу Ережесін бекіту туралы" Қызылорда облыстық мәслихатының 2006 жылғы 20 сәуірдегі N 282 шешіміне өзгеріс енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/54036/rus
