act_code: '38401'
requisite: Қызылорда облысы Қазалы аудандық мәслихатының 2008 жылғы 11 ақпандағы N 39 шешімі. Қызылорда облысының Әділет департаменті Қазалы аудандық Әділет басқармасында 2008 жылғы 17 наурызда N 10-4-79 тіркелді. Күші жойылды - Қызылорда облысы Қазалы аудандық мәслихатының 2011 жылғы 04 наурыздағы N 272 шешімімен
title:
  rus: Қазалы ауданы аумағында кәсіпкерліктің кейбір түрлерімен айналысатын салық төлемгерлері үшін салық салу объектісінен алынатын тіркелген жиынтық салығының объектілеріне салынатын ставкасының мөлшерін бекіту жайлы
  kaz: Қазалы ауданы аумағында кәсіпкерліктің кейбір түрлерімен айналысатын салық төлемгерлері үшін салық салу объектісінен алынатын тіркелген жиынтық салығының объектілеріне салынатын ставкасының мөлшерін бекіту жайлы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-02-11
approved_by:
- '161004000002'
version_date:
  kaz: 2008-02-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/38401/kaz/11.02.2008
