act_code: '31603'
requisite: Решение Кызылординского областного маслихата от 12 декабря 2006 года № 324. Зарегистрировано Департаментом юстиции Кызылординской области 9 января 2007 года № 4169
title:
  rus: Қызылорда облысы бойынша түбірімен босатылатын ағаш төлемақысы ставкаларын бекіту туралы
  kaz: Қызылорда облысы бойынша түбірімен босатылатын ағаш төлемақысы ставкаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-12
approved_by:
- '161000000002'
version_date:
  kaz: 2006-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/31603/kaz/12.12.2006
