act_code: '44636'
requisite: Решение от 29.01.2009 №14/5, Маслихат Шиелийского района
title:
  rus: Шиелі ауданының аумағындағы кәсіпкерліктің кейбір түрлерімен айналысатын салық төлемгері үшін салық салынатын әрбір объектіге алынатын бір айға салық көлемінің тіркелген салығының ставкасының мөлшерін белгілеу жайлы
  kaz: Шиелі ауданының аумағындағы кәсіпкерліктің кейбір түрлерімен айналысатын салық төлемгері үшін салық салынатын әрбір объектіге алынатын бір айға салық көлемінің тіркелген салығының ставкасының мөлшерін белгілеу жайлы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-29
approved_by:
- '161008000002'
version_date:
  kaz: 2009-01-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/44636/kaz/29.01.2009
