act_code: '205428'
requisite: Решение Кызылординского городского маслихата от 24 декабря 2024 года № 230-33/2
title:
  rus: Об утверждении бюджета поселка Белкуль на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Белкөл кентінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-24
approved_by:
- '161002000002'
version_date:
  kaz: 2025-06-04
  rus: 2025-06-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/205428/kaz/04.06.2025
  rus: https://zan.gov.kz/client/#!/doc/205428/rus/04.06.2025
caused_by:
  code: '211271'
  requisite: Решение Кызылординского городского маслихата от 4 июня 2025 года № 276-39/2
  title:
    rus: О внесении изменений в решение Кызылординского городского маслихата от 24 декабря 2024 года №230-33/2 «Об утверждении бюджета поселка Белкуль на 2025-2027 годы»
    kaz: «2025-2027 жылдарға арналған Белкөл кентінің бюджетін бекіту туралы» Қызылорда қалалық мәслихатының 2024 жылғы 24 желтоқсандағы №230-33/2 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/211271/rus
