act_code: '205428'
requisite: Решение Кызылординского городского маслихата от 24 декабря 2024 года № 230-33/2
title:
  rus: Об утверждении бюджета поселка Белкуль на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Белкөл кентінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-24
approved_by:
- '161002000002'
version_date:
  kaz: 2025-03-06
  rus: 2025-03-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/205428/kaz/06.03.2025
  rus: https://zan.gov.kz/client/#!/doc/205428/rus/06.03.2025
caused_by:
  code: '208297'
  requisite: Решение Кызылординского городского маслихата от 6 марта 2025 года № 246-35/2
  title:
    rus: О внесении изменений в решение Кызылординского городского маслихата от 24 декабря 2024 года №230-33/2 «Об утверждении бюджета поселка Белкуль на 2025-2027 годы»
    kaz: «2025-2027 жылдарға арналған Белкөл кентінің бюджетін бекіту туралы» Қызылорда қалалық мәслихатының 2024 жылғы 24 желтоқсандағы №230-33/2 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/208297/rus
