act_code: '181767'
requisite: Решение Кармакшинского районного маслихата Кызылординской области от 12 мая 2023 года № 47
title:
  rus: Об утверждении методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Кармакшинского районного маслихата»
  kaz: «Қармақшы аудандық мәслихат аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-05-12
approved_by:
- '161005000002'
version_date:
  kaz: 2025-05-16
  rus: 2025-05-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/181767/kaz/16.05.2025
  rus: https://zan.gov.kz/client/#!/doc/181767/rus/16.05.2025
caused_by:
  code: '210670'
  requisite: Решение Кармакшинского районного маслихата Кызылординской области от 16 мая 2025 года № 285
  title:
    rus: О внесении изменения в решение Кармакшинского районного маслихата от 12 мая 2023 года № 47 «Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Кармакшинского районного маслихата»
    kaz: «Қармақшы аудандық мәслихат аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау Әдістемесін бекіту туралы Қармақшы аудандық мәслихатының 2023 жылғы 12 мамырдағы № 47 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/210670/rus
