act_code: '177782'
requisite: Решение акима Аманоткельского сельского округа Аральского района Кызылординской области от 29 декабря 2022 года № 27-ш. Зарегистрировано в Министерстве юстиции Республики Казахстан 4 января 2023 года № 31554
title:
  rus: О присвоении наименования безымянной улице села Аманоткель Аманоткельского сельского округа Аральского района Кызылординской области
  kaz: Қызылорда облысы Арал ауданы Аманөткел ауылдық округінің Аманөткел ауылының атаусыз көшесіне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-29
approved_by:
- '161003002002'
version_date:
  kaz: 2022-12-29
  rus: 2022-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/177782/kaz/29.12.2022
  rus: https://zan.gov.kz/client/#!/doc/177782/rus/29.12.2022
