act_code: '125902'
requisite: Решение акима Сырдарьинского района Кызылординской области от 8 ноября 2018 года № 8. Зарегистрировано Департаментом юстиции Кызылординской области 8 ноября 2018 года № 6505
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-08
approved_by:
- '161007000003'
version_date:
  kaz: 2018-11-08
  rus: 2018-11-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/125902/kaz/08.11.2018
  rus: https://zan.gov.kz/client/#!/doc/125902/rus/08.11.2018
