act_code: '40312'
requisite: Қызылорда облысы Қазалы аудандық мәслихатының 2006 жылғы 22 желтоқсандағы № 227 шешімі. Қызылорда облысының Әділет басқармасында 2007 жылғы 9 қаңтарда № 10-4-56 болып тіркелді
title:
  rus: Базарларда, сауда қатарлары мен белгіленген орындарда тауар сатуға және түрлі кәсіпкерлік қызметпен айналысатын азаматтарға қүқық беретін бір жолғы талонның бағасын белгілеу туралы
  kaz: Базарларда, сауда қатарлары мен белгіленген орындарда тауар сатуға және түрлі кәсіпкерлік қызметпен айналысатын азаматтарға қүқық беретін бір жолғы талонның бағасын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-22
approved_by:
- '161004000002'
version_date:
  kaz: 2006-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/40312/kaz/22.12.2006
