act_code: '205606'
requisite: Решение Казалинского районного маслихата Кызылординской области от 27 декабря 2024 года № 355
title:
  rus: О бюджете города Казалинск на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Қазалы қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '161004000002'
version_date:
  kaz: 2025-06-10
  rus: 2025-06-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/205606/kaz/10.06.2025
  rus: https://zan.gov.kz/client/#!/doc/205606/rus/10.06.2025
caused_by:
  code: '211577'
  requisite: Решение Казалинского районного маслихата Кызылординской области от 10 июня 2025 года № 420
  title:
    rus: О внесении изменений в решение Казалинского районного маслихата Кызылординской области от 27 декабря 2024 года №355 «О бюджете города Казалинск на 2025-2027 годы»
    kaz: Қызылорда облысының Қазалы аудандық мәслихатының 2024 жылғы 27 желтоқсандағы №355 «2025-2027 жылдарға арналған Қазалы қаласының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/211577/rus
