act_code: '137917'
requisite: Решение Кызылординского городского маслихата от 25 декабря 2019 года № 290-54/8. Зарегистрировано Департаментом юстиции Кызылординской области 30 декабря 2019 года № 7067
title:
  rus: О бюджете сельского округа Косшынырау на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Қосшыңырау ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-25
approved_by:
- '161002000002'
version_date:
  kaz: 2020-12-14
  rus: 2020-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/137917/kaz/14.12.2020
  rus: https://zan.gov.kz/client/#!/doc/137917/rus/14.12.2020
caused_by:
  code: '150216'
  requisite: Решение Кызылординского городского маслихата от 14 декабря 2020 года № 413-72/10. Зарегистрировано Департаментом юстиции Кызылординской области 15 декабря 2020 года № 7930
  title:
    rus: О внесении изменений в решение Кызылординского городского маслихата от 25 декабря 2019 года №290-54/8 «О бюджете сельского округа Косшынырау 2020-2022 годы»
    kaz: «2020-2022 жылдарға арналған Қосшыңырау ауылдық округінің бюджеті туралы» Қызылорда қалалық мәслихатының 2019 жылғы 25 желтоқсандағы №290-54/8 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/150216/rus
