act_code: '121507'
requisite: Решение Казалинского районного маслихата Кызылординской области от 10 апреля 2018 года № 188. Зарегистрировано Департаментом юстиции Кызылординской области 27 апреля 2018 года № 6278
title:
  rus: О повышении ставок земельного налога
  kaz: Жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-04-10
approved_by:
- '161004000002'
version_date:
  kaz: 2018-04-10
  rus: 2018-04-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/121507/kaz/10.04.2018
  rus: https://zan.gov.kz/client/#!/doc/121507/rus/10.04.2018
