act_code: '93856'
requisite: Решение Казалинского районного маслихата Кызылординской области от 21 августа 2015 года № 343. Зарегистрировано Департаментом юстиции Кызылординской области 11 сентября 2015 года № 5129. Утратило силу решением Казалинского районного маслихата Кызылординской области от 10 апреля 2018 года № 189
title:
  rus: О повышении базовых ставок земельного налога
  kaz: Жер салығының базалық мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-08-21
approved_by:
- '161004000002'
version_date:
  kaz: 2015-08-21
  rus: 2015-08-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/93856/kaz/21.08.2015
  rus: https://zan.gov.kz/client/#!/doc/93856/rus/21.08.2015
