act_code: '168669'
requisite: Решение Кызылординского городского маслихата от 29 декабря 2021 года № 101-16/4
title:
  rus: О бюджете сельского округа Аксуат на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Ақсуат ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-29
approved_by:
- '161002000002'
version_date:
  kaz: 2021-12-29
  rus: 2021-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/168669/kaz/29.12.2021
  rus: https://zan.gov.kz/client/#!/doc/168669/rus/29.12.2021
