act_code: '150975'
requisite: Решение Кызылординского городского маслихата от 24 декабря 2020 года № 425-73/8. Зарегистрировано Департаментом юстиции Кызылординской области 29 декабря 2020 года № 7971
title:
  rus: О бюджете сельского округа Косшынырау на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Қосшыңырау ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-24
approved_by:
- '161002000002'
version_date:
  kaz: 2021-10-22
  rus: 2021-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/150975/kaz/22.10.2021
  rus: https://zan.gov.kz/client/#!/doc/150975/rus/22.10.2021
caused_by:
  code: '160507'
  requisite: Решение Кызылординского городского маслихата от 22 октября 2021 года № 78-12/8
  title:
    rus: О внесении изменений в решение Кызылординского городского маслихата от 24 декабря 2020 года №425-73/8 «О бюджете сельского округа Косшынырау на 2021-2023 годы»
    kaz: «2021-2023 жылдарға арналған Қосшыңырау ауылдық округінің бюджеті туралы» Қызылорда қалалық маслихатының 2020 жылғы 24 желтоқсандағы №425-73/8 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/160507/rus
