act_code: '60683'
requisite: Решение акимата поселка Тасбогет города Кызылорда от 29 июля 2011 года № 818. Зарегистрировано управлением юстиции города Кызылорда департамента юстиции Кызылординской области 23 сентября 2011 года за № 10-1-188
title:
  rus: О названии микрорайонов и улиц поселка Тасбогет
  kaz: Тасбөгет кентіндегі мөлтек аудандар және көшелерін атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-07-29
approved_by:
- '161002007001'
version_date:
  kaz: 2011-07-29
  rus: 2011-07-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/60683/kaz/29.07.2011
  rus: https://zan.gov.kz/client/#!/doc/60683/rus/29.07.2011
