act_code: '57019'
requisite: Решение от 24.12.2010 №286, Маслихат Сырдарьинского района
title:
  rus: '"2011-2013 жылдарға арналған аудандық бюджет туралы"'
  kaz: '"2011-2013 жылдарға арналған аудандық бюджет туралы"'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '161007000002'
version_date:
  kaz: 2011-05-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/57019/kaz/12.05.2011
caused_by:
  code: '58913'
  requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 12 мая 2011 года № 315. Зарегистрировано Департаментом юстиции Кызылординской области 24 мая 2011 года за № 10-8-148. Утратило силу - решением Сырдарьинского районного маслихата Кызылординской области от 20 марта 2012 года № 37
  title:
    rus: О внесений изменений в решение очередной ХХІХ сессии районного маслихата от 24 декабря 2010 года N 286 "О районном бюджете на 2011-2013 годы"
    kaz: '"2011-2013 жылдарға арналған аудандық бюджет туралы" аудандық мәслихаттың 2010 жылғы 24 желтоқсандағы кезекті ХХІХ сессиясының N 286 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/58913/rus
