act_code: '52314'
requisite: Қызылорда облысы Қармақшы аудандық мәслихатының 2010 жылғы 30 наурыздағы N 171 шешімі. Қызылорда облысының Әділет департаменті Қармақшы аудандық Әділет басқармасында 2010 жылы 04 мамырда  N 10-5-134 тіркелді. Күші жойылды - Қызылорда облысы Қармақшы аудандық мәслихатының 2010 жылғы 24 маусымдағы N 187 Шешімімен.
title:
  rus: Қармақшы ауданы аумағында абаттандыру, көркейту, санитарлық тазарту мен тазалықты қамтамасыз ету жөніндегі Ережені бекіту туралы
  kaz: Қармақшы ауданы аумағында абаттандыру, көркейту, санитарлық тазарту мен тазалықты қамтамасыз ету жөніндегі Ережені бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-30
approved_by:
- '161005000002'
version_date:
  kaz: 2010-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/52314/kaz/30.03.2010
