act_code: '52646'
requisite: Решение от 21.04.2010 №1024, Аким поселка Жанакорган
title:
  rus: Мансур Мусаевтың атына көше атын беру туралы
  kaz: Мансур Мусаевтың атына көше атын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-21
approved_by:
- '161009001001'
version_date:
  kaz: 2010-04-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/52646/kaz/21.04.2010
