act_code: '103340'
requisite: Решение Кызылординского областного маслихата от 19 мая 2016 года № 29. Зарегистрировано Департаментом юстиции Кызылординской области 6 июня 2016 года № 5526. Утратило силу решением Кызылординского областного маслихата от 15 марта 2017 года № 113
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса "Б" государственного учреждения "Аппарат Кызылординского областного маслихата"
  kaz: '"Қызылорда облыстық мәслихатының аппараты" мемлекеттік мекемесінің "Б" корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың Әдістемесін бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-05-19
approved_by:
- '161000000002'
version_date:
  kaz: 2016-05-19
  rus: 2016-05-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/103340/kaz/19.05.2016
  rus: https://zan.gov.kz/client/#!/doc/103340/rus/19.05.2016
