act_code: '221586'
requisite: Решение Жалагашского районного маслихата Кызылординской области от 19 декабря 2025 года № 37-3
title:
  rus: О бюджете поселка Жалагаш на 2026 - 2028 годы
  kaz: 2026 – 2028 жылдарға арналған Жалағаш кентінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-19
approved_by:
- '161006000002'
version_date:
  kaz: 2026-03-13
  rus: 2026-03-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/221586/kaz/13.03.2026
  rus: https://zan.gov.kz/client/#!/doc/221586/rus/13.03.2026
caused_by:
  code: '223545'
  requisite: Решение Жалагашского районного маслихата Кызылординской области от 13 марта 2026 года № 41-1
  title:
    rus: О внесении изменений в решение Жалагашского районного маслихата от 19 декабря 2025 года № 37-3 «О бюджете поселка Жалагаш на 2026-2028 годы»
    kaz: «2026 – 2028 жылдарға арналған Жалағаш кентінің бюджеті туралы» Жалағаш аудандық мәслихатының 2025 жылғы 19 желтоқсандағы № 37-3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/223545/rus
