act_code: '49600'
requisite: Решение от 23.12.2009 №126, Маслихат Аральского района
title:
  rus: 2010-2012 жылдарға арналған аудан бюджеті туралы
  kaz: 2010-2012 жылдарға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '161003000002'
version_date:
  kaz: 2010-10-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/49600/kaz/27.10.2010
caused_by:
  code: '55366'
  requisite: Решение от 27.10.2010 №185, Маслихат Аральского района
  title:
    rus: Аудандық мәслихаттың 2009 жылғы 23 желтоқсандағы кезекті жиырмасыншы сессиясының "2010-2012 жылдарға арналған аудан бюджет туралы" N 126 шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Аудандық мәслихаттың 2009 жылғы 23 желтоқсандағы кезекті жиырмасыншы сессиясының "2010-2012 жылдарға арналған аудан бюджет туралы" N 126 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/55366/rus
