act_code: '195152'
requisite: Решение Кызылординского областного маслихата от 29 марта 2024 года № 88
title:
  rus: Об утверждении целевых показателей качества окружающей среды Кызылординской области
  kaz: Қызылорда облысының қоршаған орта сапасының нысаналы көрсеткіштерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-29
approved_by:
- '161000000002'
version_date:
  kaz: 2024-03-29
  rus: 2024-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/195152/kaz/29.03.2024
  rus: https://zan.gov.kz/client/#!/doc/195152/rus/29.03.2024
