act_code: '206623'
requisite: Решение Жалагашского районного маслихата Кызылординской области от 23 декабря 2024 года № 28-6
title:
  rus: О бюджете сельского округа Аксу на 2025-2027 годы
  kaz: 2025 – 2027 жылдарға арналған Ақсу ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-23
approved_by:
- '161006000002'
version_date:
  kaz: 2024-12-23
  rus: 2024-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/206623/kaz/23.12.2024
  rus: https://zan.gov.kz/client/#!/doc/206623/rus/23.12.2024
