act_code: '163075'
requisite: Решение Шиелийского районного маслихата Кызылординской области от 27 декабря 2021 года № 17/2. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 декабря 2021 года № 26169
title:
  rus: О районном бюджете на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-27
approved_by:
- '161008000002'
version_date:
  kaz: 2021-12-27
  rus: 2021-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/163075/kaz/27.12.2021
  rus: https://zan.gov.kz/client/#!/doc/163075/rus/27.12.2021
