act_code: '43713'
requisite: Қызылорда облысы Қазалы аудандық мәслихатының 2008 жылғы 23 желтоқсандағы N 107 шешімі. Қызылорда облысының Әділет департаменті Қазалы аудандық Әділет басқармасында 2009 жылғы 22 қаңтарда N 10-4-89 тіркелді. Қолданылу мерзімінің аяқталуына байланысты күші жойылды - (Қызылорда облысы Қазалы аудандық мәслихатының 2014 жылғы 27 тамыздағы N 01-10/779 хатымен)
title:
  rus: Елді мекендердің жерлеріне (үй іргесіндегі учаскелерін қоспағанда) салынатын базалық салық ставкаларын бекіту туралы
  kaz: Елді мекендердің жерлеріне (үй іргесіндегі учаскелерін қоспағанда) салынатын базалық салық ставкаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-23
approved_by:
- '161004000002'
version_date:
  kaz: 2008-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/43713/kaz/23.12.2008
