act_code: '214559'
requisite: Решение акима сельского округа Екпинди Жанакорганского района Кызылординской области от 03 сентября 2025 года № 4-ш
title:
  rus: О присвоении наименования улице
  kaz: Көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-03
approved_by:
- '161009025002'
version_date:
  kaz: 2025-09-03
  rus: 2025-09-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/214559/kaz/03.09.2025
  rus: https://zan.gov.kz/client/#!/doc/214559/rus/03.09.2025
