act_code: '43142'
requisite: Решение от 23.12.2008 №73, Маслихат Аральского района
title:
  rus: 2009 жылға арналған аудан бюджеті туралы
  kaz: 2009 жылға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-23
approved_by:
- '161003000002'
version_date:
  kaz: 2008-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/43142/kaz/23.12.2008
