act_code: '43142'
requisite: Решение от 23.12.2008 №73, Маслихат Аральского района
title:
  rus: 2009 жылға арналған аудан бюджеті туралы
  kaz: 2009 жылға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-23
approved_by:
- '161003000002'
version_date:
  kaz: 2009-02-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/43142/kaz/17.02.2009
caused_by:
  code: '44464'
  requisite: Решение от 17.02.2009 №82, Маслихат Аральского района
  title:
    rus: Аудандық мәслихаттың 2008 жылғы 23 желтоқсандағы кезекті он бірінші сессиясының "2009 жылға арналған аудан бюджеті туралы" N 73 шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Аудандық мәслихаттың 2008 жылғы 23 желтоқсандағы кезекті он бірінші сессиясының "2009 жылға арналған аудан бюджеті туралы" N 73 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/44464/rus
