act_code: '170599'
requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 11 августа 2022 года № 158. Зарегистрировано в Министерстве юстиции Республики Казахстан 12 августа 2022 года № 29099
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов по Сырдарьинскому району
  kaz: Сырдария ауданы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-08-11
approved_by:
- '161007000002'
version_date:
  kaz: 2022-08-11
  rus: 2022-08-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/170599/kaz/11.08.2022
  rus: https://zan.gov.kz/client/#!/doc/170599/rus/11.08.2022
