act_code: '128079'
requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 26 декабря 2018 года № 267. Зарегистрировано Департаментом юстиции Кызылординской области 28 декабря 2018 года № 6606
title:
  rus: О бюджете сельского округа Н.Ильясов на 2019-2021 годы
  kaz: Н.Ілиясов ауылдық округінің 2019–2021 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-26
approved_by:
- '161007000002'
version_date:
  kaz: 2018-12-26
  rus: 2018-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/128079/kaz/26.12.2018
  rus: https://zan.gov.kz/client/#!/doc/128079/rus/26.12.2018
