act_code: '128079'
requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 26 декабря 2018 года № 267. Зарегистрировано Департаментом юстиции Кызылординской области 28 декабря 2018 года № 6606
title:
  rus: О бюджете сельского округа Н.Ильясов на 2019-2021 годы
  kaz: Н.Ілиясов ауылдық округінің 2019–2021 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-26
approved_by:
- '161007000002'
version_date:
  kaz: 2019-11-19
  rus: 2019-11-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/128079/kaz/19.11.2019
  rus: https://zan.gov.kz/client/#!/doc/128079/rus/19.11.2019
caused_by:
  code: '136298'
  requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 19 ноября 2019 года № 350. Зарегистрировано Департаментом юстиции Кызылординской области 21 ноября 2019 года № 6977
  title:
    rus: О внесении изменений в решение Сырдарьинского районного маслихата от 26 декабря 2018 года №267 «О бюджете сельского округа Наги Ильясов на 2019-2021 годы»
    kaz: «Нағи Ілиясов ауылдық округінің 2019–2021 жылдарға арналған бюджеті туралы» Сырдария аудандық мәслихатының 2018 жылғы 26 желтоқсандағы №267 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/136298/rus
