act_code: '150979'
requisite: Решение Казалинского районного маслихата Кызылординской области от 25 декабря 2020 года № 557. Зарегистрировано Департаментом юстиции Кызылординской области 29 декабря 2020 года № 7972
title:
  rus: О бюджете сельского округа Майлыбас на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Майлыбас ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-25
approved_by:
- '161004000002'
version_date:
  kaz: 2020-12-25
  rus: 2020-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/150979/kaz/25.12.2020
  rus: https://zan.gov.kz/client/#!/doc/150979/rus/25.12.2020
