act_code: '200671'
requisite: Решение акима поселка Айтеке би Казалинского района Кызылординской области от 9 сентября 2024 года № 523
title:
  rus: О переименовании улиц
  kaz: Көшеге қайта атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-09-04
approved_by:
- '161004001001'
version_date:
  kaz: 2024-09-04
  rus: 2024-09-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/200671/kaz/04.09.2024
  rus: https://zan.gov.kz/client/#!/doc/200671/rus/04.09.2024
