act_code: '137543'
requisite: Решение Аральского районного маслихата Кызылординской области от 19 декабря 2019 года № 289. Зарегистрировано Департаментом юстиции Кызылординской области 24 декабря 2019 года № 7043
title:
  rus: О районном бюджете на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-19
approved_by:
- '161003000002'
version_date:
  kaz: 2020-12-09
  rus: 2020-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/137543/kaz/09.12.2020
  rus: https://zan.gov.kz/client/#!/doc/137543/rus/09.12.2020
caused_by:
  code: '150013'
  requisite: Решение Аральского районного маслихата Кызылординской области от 9 декабря 2020 года № 433. Зарегистрировано Департаментом юстиции Кызылординской области 15 декабря 2020 года № 7905
  title:
    rus: О внесении изменений в решение Аральского районного маслихата от 19 декабря 2019 года № 289 «О районном бюджете на 2020-2022 годы»
    kaz: «2020-2022 жылдарға арналған аудандық бюджет туралы» Арал аудандық мәслихатының 2019 жылғы 19 желтоқсандағы № 289 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/150013/rus
