act_code: '137543'
requisite: Решение Аральского районного маслихата Кызылординской области от 19 декабря 2019 года № 289. Зарегистрировано Департаментом юстиции Кызылординской области 24 декабря 2019 года № 7043
title:
  rus: О районном бюджете на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-19
approved_by:
- '161003000002'
version_date:
  kaz: 2019-12-19
  rus: 2019-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/137543/kaz/19.12.2019
  rus: https://zan.gov.kz/client/#!/doc/137543/rus/19.12.2019
