act_code: '50264'
requisite: Решение от 09.12.2009 №787, Акимат Шиелийского района
title:
  rus: Шиелі кенті, "Көкшоқы" мөлтек ауданынан атауы жоқ көшеге Сағынтай Есеновтың есімін беру туралы
  kaz: Шиелі кенті, "Көкшоқы" мөлтек ауданынан атауы жоқ көшеге Сағынтай Есеновтың есімін беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-09
approved_by:
- '161008000001'
version_date:
  kaz: 2010-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/50264/kaz/28.12.2010
caused_by:
  code: '57088'
  requisite: Решение от 28.12.2010 №1104, Аким поселка Шиели
  title:
    rus: Шиелі кенті әкімінің 2009 жылғы 09 желтоқсандағы "Шиелі кенті "Көкшоқы" мөлтек ауданынан атауы жоқ көшеге Сағынтай Есеновтың есімін беру туралы" N 787 шешіміне өзгерістер енгізу туралы
    kaz: Шиелі кенті әкімінің 2009 жылғы 09 желтоқсандағы "Шиелі кенті "Көкшоқы" мөлтек ауданынан атауы жоқ көшеге Сағынтай Есеновтың есімін беру туралы" N 787 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/57088/rus
