act_code: '50264'
requisite: Решение от 09.12.2009 №787, Акимат Шиелийского района
title:
  rus: Шиелі кенті, "Көкшоқы" мөлтек ауданынан атауы жоқ көшеге Сағынтай Есеновтың есімін беру туралы
  kaz: Шиелі кенті, "Көкшоқы" мөлтек ауданынан атауы жоқ көшеге Сағынтай Есеновтың есімін беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-09
approved_by:
- '161008000001'
version_date:
  kaz: 2009-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/50264/kaz/09.12.2009
