act_code: '85895'
requisite: Решение от 15.12.2014 №297, Аким поселка Жосалы
title:
  rus: О переименовании улицы «1 мамыр» поселке Жосалы на имя Аягана Боханова
  kaz: Жосалы кентіндегі «1 мамыр» көшесін Аяған Бохановтың есімімен қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-15
approved_by:
- '161005001001'
version_date:
  kaz: 2014-12-15
  rus: 2014-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/85895/kaz/15.12.2014
  rus: https://zan.gov.kz/client/#!/doc/85895/rus/15.12.2014
