act_code: '195880'
requisite: Решение Жалагашского районного маслихата Кызылординской области от 18 апреля 2024 года № 18-1
title:
  rus: Об утверждении тарифов для населения на сбор, транспортировку, сортировку и захоронение твердых бытовых отходов  по Жалагашскому району
  kaz: Жалағаш ауданы бойынша халық үшін тұрмыстық қатты қалдықтарды жинауға, тасымалдауға, сұрыптауға және көмуге арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-04-18
approved_by:
- '161006000002'
version_date:
  kaz: 2024-04-18
  rus: 2024-04-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/195880/kaz/18.04.2024
  rus: https://zan.gov.kz/client/#!/doc/195880/rus/18.04.2024
