act_code: '76715'
requisite: Решение Жанакорганского районного маслихата Кызылординской области от 28 декабря 2013 года № 181. Зарегистрировано Департаментом юстиции Кызылординской области 15 января 2014 года № 4579. Прекращено действие в связи с истечением срока
title:
  rus: О районном бюджете на 2014-2016 годы
  kaz: 2014-2016 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-28
approved_by:
- '161009000002'
version_date:
  kaz: 2014-02-24
  rus: 2014-02-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/76715/kaz/24.02.2014
  rus: https://zan.gov.kz/client/#!/doc/76715/rus/24.02.2014
caused_by:
  code: '77804'
  requisite: Решение Жанакорганского районного маслихата Кызылординской области от 24 февраля 2014 года № 190. Зарегистрировано Департаментом юстиции Кызылординской области 03 марта 2014 года № 4606. Прекращено действие в связи с истечением срока
  title:
    rus: О внесении изменений в решение районного маслихата от 28 декабря 2013 года № 181 "О районном бюджете на 2014-2016 годы"
    kaz: '"2014-2016 жылдарға арналған аудандық бюджет туралы" аудандық мәслихатының 2013 жылғы 28 желтоқсандағы № 181 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/77804/rus
