act_code: '45635'
requisite: Решение от 30.03.2009 №105, Маслихат Кармакшинского района
title:
  rus: '"2009 жылға арналған арнаулы салық режимінде жұмыс жасайтын кәсіпкерлердің бір салық салу объектісінен алынатын және аудан көлеміндегі қолданылатын жер салығы үшін алынатын алым мөлшерін белгілеу туралы"'
  kaz: '"2009 жылға арналған арнаулы салық режимінде жұмыс жасайтын кәсіпкерлердің бір салық салу объектісінен алынатын және аудан көлеміндегі қолданылатын жер салығы үшін алынатын алым мөлшерін белгілеу туралы"'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-03-30
approved_by:
- '161005000002'
version_date:
  kaz: 2009-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/45635/kaz/30.03.2009
