act_code: '154072'
requisite: Решение акима поселка Жалагаш Жалагашского района Кызылординской области от 30 марта 2021 года № 81. Зарегистрировано Департаментом юстиции Кызылординской области 1 апреля 2021 года № 8235
title:
  rus: О присвоении наименований безымянным улицам
  kaz: Атауы жоқ көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-03-30
approved_by:
- '161006015002'
version_date:
  kaz: 2021-03-30
  rus: 2021-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/154072/kaz/30.03.2021
  rus: https://zan.gov.kz/client/#!/doc/154072/rus/30.03.2021
