act_code: '138994'
requisite: Решение Кармакшинского районного маслихата Кызылординской области от 27 декабря 2019 года № 288. Зарегистрировано Департаментом юстиции Кызылординской области 5 января 2020 года № 7185
title:
  rus: О бюджете сельского округа Акжар на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Ақжар ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-27
approved_by:
- '161005000002'
version_date:
  kaz: 2020-12-11
  rus: 2020-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/138994/kaz/11.12.2020
  rus: https://zan.gov.kz/client/#!/doc/138994/rus/11.12.2020
caused_by:
  code: '149971'
  requisite: Решение Кармакшинского районного маслихата Кызылординской области от 11 декабря 2020 года № 395. Зарегистрировано Департаментом юстиции Кызылординской области 15 декабря 2020 года № 7896
  title:
    rus: О внесении изменений в решение Кармакшинского районного маслихата от 27 декабря 2019 года №288 «О бюджете сельского округа Акжар на 2020-2022 годы»
    kaz: «2020-2022 жылдарға арналған Ақжар ауылдық округінің бюджеті туралы» Қармақшы аудандық мәслихатының 2019 жылғы 27 желтоқсандағы №288 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149971/rus
