act_code: '137904'
requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 27 декабря 2019 года № 376. Зарегистрировано Департаментом юстиции Кызылординской области 30 декабря 2019 года № 7093
title:
  rus: О бюджете сельского округа Аcкара Токмаганбетова на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Асқар Тоқмағанбетов ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-27
approved_by:
- '161007000002'
version_date:
  kaz: 2020-11-17
  rus: 2020-11-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/137904/kaz/17.11.2020
  rus: https://zan.gov.kz/client/#!/doc/137904/rus/17.11.2020
caused_by:
  code: '148801'
  requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 17 ноября 2020 года № 451. Зарегистрировано Департаментом юстиции Кызылординской области 20 ноября 2020 года № 7794
  title:
    rus: О внесении изменений в решение Сырдарьинского районного маслихата от 27 декабря 2019 года № 376 «О бюджете сельского округа Аскара Токмаганбетова на 2020-2022 годы»
    kaz: «2020 – 2022 жылдарға арналған Асқар Тоқмағанбетов ауылдық округінің бюджеті туралы» Сырдария аудандық маслихатының 2019 жылғы 27 желтоқсандағы № 376 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/148801/rus
