act_code: '88432'
requisite: Решение Шиелийского районного маслихата Кызылординской области от 27 марта 2015 года № 38/3. Зарегистрировано Департаментом юстиции Кызылординской области 09 апреля 2015 года № 4943. Прекращено действие в связи с истечением срока
title:
  rus: О предоставлении мер социальной поддержки на 2015 год
  kaz: 2015 жылға әлеуметтік қолдау шараларын көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-03-27
approved_by:
- '161008000002'
version_date:
  kaz: 2016-01-01
  rus: 2016-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/88432/kaz/01.01.2016
  rus: https://zan.gov.kz/client/#!/doc/88432/rus/01.01.2016
