act_code: '89385'
requisite: Решение №80 от 10.04.2015, Аким поселка Айтеке би
title:
  rus: О переименованиии улицу
  kaz: Көшені қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-04-10
approved_by:
- '161004001001'
version_date:
  kaz: 2015-04-10
  rus: 2015-04-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/89385/kaz/10.04.2015
  rus: https://zan.gov.kz/client/#!/doc/89385/rus/10.04.2015
