act_code: '187459'
requisite: Решение Жанакорганского районного маслихата Кызылординской области от 13 октября 2023 года № 94. Зарегистрировано Департаментом юстиции Кызылординской области 20 октября 2023 года № 8458-11
title:
  rus: Об утверждении правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан Жанакорганского района
  kaz: Жаңақорған ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-10-13
approved_by:
- '161009000002'
version_date:
  kaz: 2024-04-11
  rus: 2024-04-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/187459/kaz/11.04.2024
  rus: https://zan.gov.kz/client/#!/doc/187459/rus/11.04.2024
caused_by:
  code: '195968'
  requisite: Решение Жанакорганского районного маслихата Кызылординской области от 11 апреля 2024 года № 206. Зарегистрировано Департаментом юстиции Кызылординской области 22 апреля 2024 года № 8513-11
  title:
    rus: О внесении изменений и дополнения в решение маслихата Жанакорганского района от 13 октября 2023 года № 94 «Об утверждении правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан Жанакорганского района»
    kaz: «Жаңақорған ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» Жаңақорған ауданы мәслихатының 2023 жылғы 13 қазандағы № 94 шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/195968/rus
