act_code: '192557'
requisite: Решение акима сельского округа Каратобе Жанакорганского района Кызылординской области от 15 января 2024 года N 2
title:
  rus: О присвоении наименовании улицам
  kaz: Көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-01-15
approved_by:
- '161009010002'
version_date:
  kaz: 2024-01-15
  rus: 2024-01-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/192557/kaz/15.01.2024
  rus: https://zan.gov.kz/client/#!/doc/192557/rus/15.01.2024
