act_code: '92104'
requisite: Решение от 22.06.2015 №910, Аким поселка Жанакорган
title:
  rus: О присвоении наименований улиц поселка Жанакорган
  kaz: Жаңақорған кентінің көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-06-22
approved_by:
- '161009001001'
version_date:
  kaz: 2015-06-22
  rus: 2015-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/92104/kaz/22.06.2015
  rus: https://zan.gov.kz/client/#!/doc/92104/rus/22.06.2015
