act_code: '86083'
requisite: Решение от 24.12.2014 №270, Маслихат Казалинского района. Утратило силу решением Казалинского районного маслихата Кызылординской области от 7 декабря 2021 года № 151
title:
  rus: Об утверждении проекта (схемы) зонирования земель, границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки
  kaz: Жерлерді аймақтарға бөлу жобасын (схемасын), бағалау аймақтарының шекараларын және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '161004000002'
version_date:
  kaz: 2014-12-24
  rus: 2014-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/86083/kaz/24.12.2014
  rus: https://zan.gov.kz/client/#!/doc/86083/rus/24.12.2014
