act_code: '55365'
requisite: Решение от 11.10.2010 №677, Аким поселка Тасбогет
title:
  rus: Тасбөгет кенті көшелеріне жаңадан атау беру туралы
  kaz: Тасбөгет кенті көшелеріне жаңадан атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-10-11
approved_by:
- '161002007001'
version_date:
  kaz: 2012-04-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/55365/kaz/03.04.2012
caused_by:
  code: '65332'
  requisite: Решение акима поселка Тасбогет города Кызылорда от 3 апреля 2012 года № 937. Зарегистрировано управлением юстиции города Кызылорда департамента юстиции Кызылординской области 4 мая 2012 года за № 10-1-211
  title:
    rus: О внесении изменений в решение акима поселка Тасбогет от 11 октября 2010 года N 677 "О переименовании улиц поселка Тасбогет"
    kaz: '"Тасбөгет кенті көшелеріне жаңадан атау беру туралы" Тасбөгет кенті әкімінің 2010 жылғы 11 қазандағы N 677 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/65332/rus
