act_code: '55365'
requisite: Решение от 11.10.2010 №677, Аким поселка Тасбогет
title:
  rus: Тасбөгет кенті көшелеріне жаңадан атау беру туралы
  kaz: Тасбөгет кенті көшелеріне жаңадан атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-10-11
approved_by:
- '161002007001'
version_date:
  kaz: 2010-10-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/55365/kaz/11.10.2010
