act_code: '191803'
requisite: Решение Шиелийского районного маслихата Кызылординской области от 26 декабря 2023 года № 11/16
title:
  rus: О бюджете сельского округа Каргалы на 2024-2026 годы
  kaz: Қарғалы ауылдық округінің 2024-2026 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-26
approved_by:
- '161008000002'
version_date:
  kaz: 2024-03-11
  rus: 2024-03-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/191803/kaz/11.03.2024
  rus: https://zan.gov.kz/client/#!/doc/191803/rus/11.03.2024
caused_by:
  code: '194603'
  requisite: Решение Шиелийского районного маслихата Кызылординской области от 11 марта 2024 года № 14/16
  title:
    rus: О внесении изменений в решение Шиелийского районного маслихата от 26 декабря 2023 года № 11/16 «О бюджете сельского округа Каргалы на 2024-2026 годы»
    kaz: «Қарғалы ауылдық округінің 2024-2026 жылдарға арналған бюджеті туралы» Шиелі аудандық мәслихатының 2023 жылғы 26 желтоқсандағы № 11/16 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/194603/rus
