act_code: '1222'
requisite: Решение акима Кызылординской области от 11 мая 1998 года № 724. Зарегистрировано Управлением юстиции Кызылординской области 29 мая 1998 года № 26
title:
  rus: Об утверждении тарифа за услуги по подаче воды в орешаемом земледелии области на 1998 год
  kaz: 1998 жылға облыстың суармалы жерлеріне су жеткізіп беру қызметі үшін тарифін бекіту
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-05-10
approved_by:
- '161000000003'
version_date:
  kaz: 1998-05-10
  rus: 1998-05-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/1222/kaz/10.05.1998
  rus: https://zan.gov.kz/client/#!/doc/1222/rus/10.05.1998
