act_code: '56233'
requisite: Решение от 17.11.2010 №1074, Аким поселка Шиели
title:
  rus: Шиелі кентінің Солтүстік - Шығыс беткейінен ашылған мөлтек ауданға "Арай" атауын беру туралы
  kaz: Шиелі кентінің Солтүстік - Шығыс беткейінен ашылған мөлтек ауданға "Арай" атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-17
approved_by:
- '161008023001'
version_date:
  kaz: 2010-11-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/56233/kaz/17.11.2010
