act_code: '138563'
requisite: Решение Аральского районного маслихата Кызылординской области от 26 декабря 2019 года № 304. Зарегистрировано Департаментом юстиции Кызылординской области 5 января 2020 года № 7168
title:
  rus: О бюджете сельского округа Боген на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Бөген ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-26
approved_by:
- '161003000002'
version_date:
  kaz: 2020-12-25
  rus: 2020-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/138563/kaz/25.12.2020
  rus: https://zan.gov.kz/client/#!/doc/138563/rus/25.12.2020
caused_by:
  code: '151411'
  requisite: Решение Аральского районного маслихата Кызылординской области от 25 декабря 2020 года № 443. Зарегистрировано Департаментом юстиции Кызылординской области 30 декабря 2020 года № 8018
  title:
    rus: О внесении изменений в решение Аральского районного маслихата от 26 декабря 2019 года № 304 «О бюджете сельского округа Боген 2020-2022 годы»
    kaz: «2020-2022 жылдарға арналған Бөген ауылдық округінің бюджеті туралы» Арал аудандық мәслихатының 2019 жылғы 26 желтоқсандағы № 304 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/151411/rus
