act_code: '73938'
requisite: Решение Кызылординского городского маслихата от 16 июля 2013 года N 19/2. Зарегистрировано Департаментом юстиции Кызылординской области 13 августа 2013 года N 4490. Утратило силу решением Кызылординского городского маслихата от 01 февраля 2016 года N 53/2
title:
  rus: О дополнительном регламентировании порядка проведения собраний, митингов, шествий, пикетов и демонстраций
  kaz: Жиналыстар, митингілер, шерулер, пикеттер мен демонстрациялар өткізу тәртібін қосымша реттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-07-16
approved_by:
- '161002000002'
version_date:
  kaz: 2014-02-18
  rus: 2014-02-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/73938/kaz/18.02.2014
  rus: https://zan.gov.kz/client/#!/doc/73938/rus/18.02.2014
caused_by:
  code: '77731'
  requisite: Решение Кызылординского городского маслихата от 18 февраля 2014 года № 26/3. Зарегистрировано Департаментом юстиции Кызылординской области 27 февраля 2014 года № 4604
  title:
    rus: О внесении изменений в решение Кызылординского городского маслихата от 16 июля 2013 года N 19/2 "О дополнительном регламентировании порядка проведения собраний, митингов, шествий, пикетов и демонстраций"
    kaz: '"Жиналыстар, митингілер, шерулер, пикеттер мен демонстрациялар өткізу тәртібін қосымша реттеу туралы" Қызылорда қалалық мәслихатының 2013 жылғы 16 шілдедегі N 19/2 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/77731/rus
