act_code: '61399'
requisite: Решение акима аульного округа Акжарма города Кызылорда от 12 октября 2011 года № 27. Зарегистрировано управлением юстиции города Кызылорда департамента юстиции Кызылординской области 15 ноября 2011 года № 10-1-193. Утратило силу решением акима сельского округа Акжарма города Кызылорда Кызылординской области от 4 декабря 2017 года № 27
title:
  rus: О наименовании улиц аульного округа Акжарма
  kaz: Ақжарма ауылдық округінің көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-10-12
approved_by:
- '161002005001'
version_date:
  kaz: 2011-10-12
  rus: 2011-10-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/61399/kaz/12.10.2011
  rus: https://zan.gov.kz/client/#!/doc/61399/rus/12.10.2011
