act_code: '146508'
requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 16 сентября 2020 года № 430. Зарегистрировано Департаментом юстиции Кызылординской области 18 сентября 2020 года № 7648. Утратило силу решением Сырдарьинского районного маслихата Кызылординской области от 4 сентября 2023 года № 54
title:
  rus: Об утверждении правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтiк көмек көрсету, оның мөлшерлерiн белгiлеу және мұқтаж азаматтардың жекелеген санаттарының тiзбесiн айқындау Қағидаларын бекiту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-16
approved_by:
- '161007000002'
version_date:
  kaz: 2022-08-11
  rus: 2022-08-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/146508/kaz/11.08.2022
  rus: https://zan.gov.kz/client/#!/doc/146508/rus/11.08.2022
caused_by:
  code: '170674'
  requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 11 августа 2022 года № 157. Зарегистрировано в Министерстве юстиции Республики Казахстан 12 августа 2022 года № 29100. Утратило силу решением Сырдарьинского районного маслихата Кызылординской области от 4 сентября 2023 года № 54
  title:
    rus: О внесении изменения в решение Сырдарьинского районного маслихата от 16 сентября 2020 года №430 «Об утверждении правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: «Әлеуметтік көмек көрсету, оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау Қағидаларын бекіту туралы» Сырдария аудандық мәслихатының 2020 жылғы 16 қыркүйектегі №430 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/170674/rus
