act_code: '35324'
requisite: Қызылорда облысы Қазалы аудандық мәслихатының 2007 жылғы 14 наурыздағы № 250 шешімі. Қызылорда облысының Әділет басқармасында 2007 жылғы 17 сәуірде № 10-4-61 болып тіркелді
title:
  rus: Ауданда мұқтаж азаматтардың жекелеген санаттарына ауыз суға жинақталған қарызын өтеу үшін бір жолғы әлеуметтік көмек берудің уақытша Тәртібін бекіту туралы
  kaz: Ауданда мұқтаж азаматтардың жекелеген санаттарына ауыз суға жинақталған қарызын өтеу үшін бір жолғы әлеуметтік көмек берудің уақытша Тәртібін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-03-14
approved_by:
- '161004000002'
version_date:
  kaz: 2007-03-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/35324/kaz/14.03.2007
