act_code: '126896'
requisite: Решение акима поселка Шалхия Жанакорганского района Кызылординской области от 28 ноября 2018 года № 120. Зарегистрировано Департаментом юстиции Кызылординской области 5 декабря 2018 года № 6549
title:
  rus: О признании утратившим силу решения акима поселка Шалхия от 4 декабря 2017 года №59 «Об установлении ограничительных мероприятий»
  kaz: «Шектеу іс-шараларын белгілеу туралы» Шалқия кенті әкімінің 2017 жылдың 4 желтоқсандағы №59 шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-28
approved_by:
- '161009002001'
version_date:
  kaz: 2018-11-28
  rus: 2018-11-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/126896/kaz/28.11.2018
  rus: https://zan.gov.kz/client/#!/doc/126896/rus/28.11.2018
