act_code: '143492'
requisite: Решение акима Казалинского района Кызылординской области от 27 мая 2020 года № 97. Зарегистрировано Департаментом юстиции Кызылординской области 28 мая 2020 года № 7495. Утратило силу решением акимата Казалинского района Кызылординской области от 21 мая 2026 года № 3 (вводится в действие со дня первого официального опубликования)
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-05-27
approved_by:
- '161004000003'
version_date:
  kaz: 2020-05-27
  rus: 2020-05-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/143492/kaz/27.05.2020
  rus: https://zan.gov.kz/client/#!/doc/143492/rus/27.05.2020
