act_code: '94412'
requisite: Решение Кармакшинского районного маслихата Кызылординской области от 22 сентября 2015 года № 297. Зарегистрировано Департаментом юстиции Кызылординской области 12 октября 2015 года № 5170. Утратило силу решением Кармакшинского районного маслихата Кызылординской области от 28 апреля 2023 года № 27
title:
  rus: Об утверждении методики ежегодной оценки деятельности административных государственных служащих корпуса "Б" государственного учреждения "аппарат Кармакшинского районного маслихата"
  kaz: '"Қармақшы аудандық мәслихат аппараты" мемлекеттік мекемесінің "Б" корпусы мемлекеттік әкімшілік қызметшілерінің қызметін жыл сайынғы бағалаудың әдістемесін бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-09-22
approved_by:
- '161005000002'
version_date:
  kaz: 2015-09-22
  rus: 2015-09-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/94412/kaz/22.09.2015
  rus: https://zan.gov.kz/client/#!/doc/94412/rus/22.09.2015
