act_code: '98411'
requisite: Решение Кармакшинского районного маслихата Кызылординской области от 23 декабря 2015 года № 5320. Зарегистрировано Департаментом юстиции Кызылординской области 25 января 2016 года № 5320. Утратило силу решением Кармакшинского районного маслихата Кызылординской области от 27.09.2016 № 41.
title:
  rus: Об утверждении Положения государственного учреждения "Аппарат Кармакшинского районного маслихата"
  kaz: '"Қармақшы аудандық мәслихат аппараты" мемлекеттік мекемесінің Ережесін бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-23
approved_by:
- '161005000002'
version_date:
  kaz: 2015-12-23
  rus: 2015-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/98411/kaz/23.12.2015
  rus: https://zan.gov.kz/client/#!/doc/98411/rus/23.12.2015
