act_code: '134353'
requisite: Решение Кызылординского городского маслихата от 23 августа 2019 года № 252-45/4. Зарегистрировано Департаментом юстиции Кызылординской области 26 августа 2019 года № 6904
title:
  rus: Об утверждении порядка и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах
  kaz: Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына бюджет қаражаты есебінен коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету тәртібін және мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-08-23
approved_by:
- '161002000002'
version_date:
  kaz: 2022-03-29
  rus: 2022-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/134353/kaz/29.03.2022
  rus: https://zan.gov.kz/client/#!/doc/134353/rus/29.03.2022
caused_by:
  code: '166145'
  requisite: Решение Кызылординского городского маслихата от 29 марта 2022 года № 115-17/6. Зарегистрировано в Министерстве юстиции Республики Казахстан 6 апреля 2022 года № 27454
  title:
    rus: О внесении изменения в решение Кызылординского городского маслихата от 23 августа 2019 года № 252-45/4 «Об утверждении порядка и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах»
    kaz: «Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына бюджет қаражаты есебінен коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету тәртібін және мөлшерін бекіту туралы» Қызылорда қалалық мәслихатының 2019 жылғы  29 тамыздағы № 252-45/4 шешiмiне өзгеріс енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/166145/rus
