act_code: '150923'
requisite: Решение Кызылординского городского маслихата от 24 декабря 2020 года № 422-73/5. Зарегистрировано Департаментом юстиции Кызылординской области 29 декабря 2020 года № 7966
title:
  rus: О бюджете сельского округа Кызылжарма на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Қызылжарма ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-24
approved_by:
- '161002000002'
version_date:
  kaz: 2021-12-03
  rus: 2021-12-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/150923/kaz/03.12.2021
  rus: https://zan.gov.kz/client/#!/doc/150923/rus/03.12.2021
caused_by:
  code: '161940'
  requisite: Решение Кызылординского городского маслихата от 3 декабря 2021 года № 89-14/5
  title:
    rus: О внесении изменений в решение Кызылординского городского маслихата от 24 декабря 2020 года №422-73/5 «О бюджете сельского округа Кызылжарма на 2021-2023 годы»
    kaz: «2021-2023 жылдарға арналған Қызылжарма ауылдық округінің бюджеті туралы» Қызылорда қалалық маслихатының 2020 жылғы 24 желтоқсандағы №422-73/5 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/161940/rus
