act_code: '137951'
requisite: Решение Кызылординского городского маслихата от 25 декабря 2019 года № 284-54/2. Зарегистрировано Департаментом юстиции Кызылординской области 30 декабря 2019 года № 7071
title:
  rus: О бюджете поселка Белкол на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Белкөл кентінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-25
approved_by:
- '161002000002'
version_date:
  kaz: 2019-12-25
  rus: 2019-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/137951/kaz/25.12.2019
  rus: https://zan.gov.kz/client/#!/doc/137951/rus/25.12.2019
