act_code: '192962'
requisite: Решение акима сельского округа Туран Шиелийского района Кызылординской области от 25 января 2024 года № 135
title:
  rus: О присвоении наименования центральной улице села Ш.Кодаманова сельского округа Туран
  kaz: Тұран ауылдық округі Ш.Қодаманов ауылының орталық көшесіне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-01-25
approved_by:
- '161008022002'
version_date:
  kaz: 2024-01-25
  rus: 2024-01-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/192962/kaz/25.01.2024
  rus: https://zan.gov.kz/client/#!/doc/192962/rus/25.01.2024
