act_code: '138119'
requisite: Решение Жанакорганского районного маслихата Кызылординской области от 26 декабря 2019 года № 388. Зарегистрировано Департаментом юстиции Кызылординской области 30 декабря 2019 года № 7104
title:
  rus: О районном бюджете на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-26
approved_by:
- '161009000002'
version_date:
  kaz: 2020-11-30
  rus: 2020-11-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/138119/kaz/30.11.2020
  rus: https://zan.gov.kz/client/#!/doc/138119/rus/30.11.2020
caused_by:
  code: '149251'
  requisite: Решение Жанакорганского районного маслихата Кызылординской области от 30 ноября 2020 года № 537. Зарегистрировано Департаментом юстиции Кызылординской области 2 декабря 2020 года № 7820
  title:
    rus: О внесении изменений в решение Жанакорганского районного маслихата от 26 декабря 2019 года №388 «О районном бюджете на 2020-2022 годы»
    kaz: «2020-2022 жылдарға арналған аудандық бюджет туралы» Жаңақорған аудандық мәслихатының 2019 жылғы 26 желтоқсандағы №388 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149251/rus
