act_code: '138119'
requisite: Решение Жанакорганского районного маслихата Кызылординской области от 26 декабря 2019 года № 388. Зарегистрировано Департаментом юстиции Кызылординской области 30 декабря 2019 года № 7104
title:
  rus: О районном бюджете на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-26
approved_by:
- '161009000002'
version_date:
  kaz: 2019-12-26
  rus: 2019-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/138119/kaz/26.12.2019
  rus: https://zan.gov.kz/client/#!/doc/138119/rus/26.12.2019
