act_code: '206360'
requisite: Решение Аральского районного маслихата Кызылординской области от 27 декабря 2024 года № 318
title:
  rus: «О бюджете поселка Жаксыкылыш на 2025-2027 годы»
  kaz: «2025-2027 жылдарға арналған Жақсықылыш кентінің бюджеті туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '161003000002'
version_date:
  kaz: 2025-07-23
  rus: 2025-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/206360/kaz/23.07.2025
  rus: https://zan.gov.kz/client/#!/doc/206360/rus/23.07.2025
caused_by:
  code: '213063'
  requisite: Решение Аральского районного маслихата Кызылординской области от 23 июля 2025 года № 399
  title:
    rus: О внесении изменений в решение Аральского районного маслихата Кызылординской области от 27 декабря 2024 года № 318 «О бюджете поселка Жаксыкылыш на 2025-2027 годы»
    kaz: Қызылорда облысы Арал аудандық мәслихатының 2024 жылғы 27 желтоқсандағы № 318 «2025-2027 жылдарға арналған Жақсықылыш кентінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/213063/rus
