act_code: '37155'
requisite: Қызылорда облысы Сырдария аудандық мәслихатының 2007 жылғы 25 желтоқсандағы № 34 шешімі. Қызылорда облысының Әділет басқармасында 2008 жылғы 15 қаңтарда № 10-8-56 болып тіркелді
title:
  rus: Аудан бойынша аз қамтамасыз етілген азаматтарға тұрғын үйді үстауға және коммуналдық қызметтің ақысын төлеуге арналған тұрғын үй көмегін беру туралы Ережесін бекіту туралы
  kaz: Аудан бойынша аз қамтамасыз етілген азаматтарға тұрғын үйді үстауға және коммуналдық қызметтің ақысын төлеуге арналған тұрғын үй көмегін беру туралы Ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-25
approved_by:
- '161007000002'
version_date:
  kaz: 2007-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/37155/kaz/25.12.2007
