act_code: '117673'
requisite: Решение Казалинского районного маслихата Кызылординской области от 22 декабря 2017 года № 151. Зарегистрировано Департаментом юстиции Кызылординской области 4 января 2018 года № 6113
title:
  rus: О предоставлении льгот отдельным категориям граждан
  kaz: Жекелеген санаттағы азаматтарға жеңілдіктер беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-22
approved_by:
- '161004000002'
version_date:
  kaz: 2017-12-22
  rus: 2017-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/117673/kaz/22.12.2017
  rus: https://zan.gov.kz/client/#!/doc/117673/rus/22.12.2017
