act_code: '80773'
requisite: Решение Жалагашского районного маслихата Кызылординской области от 6 июня 2014 года № 33-2. Зарегистрировано Департаментом юстиции Кызылординской области 19 июня 2014 года за № 4703. Утратило силу решением Жалагашского районного маслихата Кызылординской области от 17 августа 2023 года № 5-3
title:
  rus: Об утверждении правил проведения раздельных сходов местного сообщества в Жалагашском районе
  kaz: Жалағаш ауданында бөлек жергілікті қоғамдастық жиындарын өткізудің қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-06-06
approved_by:
- '161006000002'
version_date:
  kaz: 2021-11-17
  rus: 2021-11-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/80773/kaz/17.11.2021
  rus: https://zan.gov.kz/client/#!/doc/80773/rus/17.11.2021
caused_by:
  code: '161542'
  requisite: Решение Жалагашского районного маслихата Кызылординской области от 17 ноября 2021 года № 10-7. Утратило силу решением Жалагашского районного маслихата Кызылординской области от 17 августа 2023 года № 5-4
  title:
    rus: О внесении изменений в решение Жалагашского районного маслихата от 06 июня 2014 года №33-2 «Об утверждении правил проведения раздельных сходов местного сообщества в Жалагашском районе»
    kaz: «Жалағаш ауданында бөлек жергілікті қоғамдастық жиындарын өткізудің Қағидасын бекіту туралы» Жалағаш аудандық мәслихатының 2014 жылғы 06 маусымдағы №33-2 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/161542/rus
