act_code: '77026'
requisite: Решение Кызылординского городского маслихата от 24 декабря 2013 года № 25/5. Зарегистрировано Департаментом юстиции Кызылординской области 24 января 2014 года № 4584. Утратило силу решением Кызылординского городского маслихата от 22 сентября 2016 года № 39-7/9
title:
  rus: Об утверждении регламента Кызылординского городского маслихата
  kaz: Қызылорда қалалық мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-24
approved_by:
- '161002000002'
version_date:
  kaz: 2013-12-24
  rus: 2013-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/77026/kaz/24.12.2013
  rus: https://zan.gov.kz/client/#!/doc/77026/rus/24.12.2013
