act_code: '122341'
requisite: Решение Аральского районного маслихата Кызылординской области от 23 мая 2018 года № 156. Зарегистрировано Департаментом юстиции Кызылординской области 5 июня 2018 года № 6311
title:
  rus: Об утверждении Регламента собрания местного сообщества Аманоткельского сельского округа Аральского района
  kaz: Арал ауданы Аманөткел ауылдық округінің жергілікті қоғамдастық жиналысының Регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-05-23
approved_by:
- '161003000002'
version_date:
  kaz: 2021-12-24
  rus: 2021-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/122341/kaz/24.12.2021
  rus: https://zan.gov.kz/client/#!/doc/122341/rus/24.12.2021
caused_by:
  code: '163980'
  requisite: Решение Аральского районного маслихата Кызылординской области от 24 декабря 2021 года № 175
  title:
    rus: «О внесении изменений в решение Аральского районного маслихата от 23 мая 2018 года №156 «Об утверждении Регламента собрания местного сообщества сельского округа Аманоткель Аральского района»
    kaz: «Арал ауданы Аманөткел ауылдық округінің жергілікті қоғамдастық жиналысының Регламентін бекіту туралы» Арал аудандық мәслихатының 2018 жылғы 23 мамырдағы № 156 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/163980/rus
