act_code: '123260'
requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 15 июня 2018 года № 198. Зарегистрировано Департаментом юстиции Кызылординской области 4 июля 2018 года № 6363
title:
  rus: Об утверждении Регламента собрания местного сообщества поселка Теренозек Сырдарьинского района
  kaz: Сырдария ауданы Тереңөзек кентінің жергілікті қоғамдастық жиналысының Регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-06-15
approved_by:
- '161007000002'
version_date:
  kaz: 2024-06-26
  rus: 2024-06-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/123260/kaz/26.06.2024
  rus: https://zan.gov.kz/client/#!/doc/123260/rus/26.06.2024
caused_by:
  code: '198347'
  requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 26 июня 2024 года № 120
  title:
    rus: О внесении изменения в решение Сырдарьинского районного маслихата от 15 июня 2018 года № 198 «Об утверждении Регламента собрания местного сообщества поселка Теренозек Сырдарьинского района»
    kaz: «Сырдария ауданы Тереңөзек кентінің жергілікті қоғамдастық жиналысының Регламентін бекіту туралы» Сырдария аудандық мәслихатының 2018 жылғы 15 маусымдағы № 198 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/198347/rus
