act_code: '214059'
requisite: Решение акима аульного округа Аксуат города Кызылорда Кызылординской области от 09 сентября 2025 года № 1227
title:
  rus: Об установлении норматива отчисления части чистого дохода коммунального государственного предприятия
  kaz: Коммуналдық мемлекеттік кәсіпорынның таза кірісінің бір бөлігін аудару нормативін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-09
approved_by:
- '161002002002'
version_date:
  kaz: 2025-09-09
  rus: 2025-09-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/214059/kaz/09.09.2025
  rus: https://zan.gov.kz/client/#!/doc/214059/rus/09.09.2025
