act_code: '127622'
requisite: Решение Кызылординского городского маслихата от 14 декабря 2018 года № 199-33/3. Зарегистрировано Департаментом юстиции Кызылординской области 19 декабря 2018 года № 6567
title:
  rus: О городском бюджете на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-14
approved_by:
- '161002000002'
version_date:
  kaz: 2019-05-22
  rus: 2019-05-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/127622/kaz/22.05.2019
  rus: https://zan.gov.kz/client/#!/doc/127622/rus/22.05.2019
caused_by:
  code: '131978'
  requisite: Решение Кызылординского городского маслихата от 22 мая 2019 года № 231-41/1. Зарегистрировано Департаментом юстиции Кызылординской области 24 мая 2019 года № 6796
  title:
    rus: О внесении изменений в решение сессии Кызылординского городского маслихата от 14 декабря 2018 года №199-33/3 «О городском бюджете на 2019-2021 годы»
    kaz: «2019-2021 жылдарға арналған қалалық бюджет туралы» Қызылорда қалалық мәслихатының 2018 жылғы 14 желтоқсандағы сессиясының №199-33/3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/131978/rus
