act_code: '168656'
requisite: Решение Кызылординского городского маслихата от 29 декабря 2021 года № 99-16/2
title:
  rus: О бюджете поселка Белкуль на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Белкөл кентінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-29
approved_by:
- '161002000002'
version_date:
  kaz: 2021-12-29
  rus: 2021-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/168656/kaz/29.12.2021
  rus: https://zan.gov.kz/client/#!/doc/168656/rus/29.12.2021
