act_code: '163362'
requisite: Решение Казалинского районного маслихата Кызылординской области от 29 декабря 2021 года № 186
title:
  rus: О бюджете сельского округа Аранды на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Аранды ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-29
approved_by:
- '161004000002'
version_date:
  kaz: 2022-05-27
  rus: 2022-05-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/163362/kaz/27.05.2022
  rus: https://zan.gov.kz/client/#!/doc/163362/rus/27.05.2022
caused_by:
  code: '172382'
  requisite: Решение Казалинского районного маслихата Кызылординской области от 27 мая 2022 года № 230
  title:
    rus: О внесении изменений в решение Казалинского районного маслихата Кызылординской области «О бюджете сельского округа Аранды на 2022-2024 годы» от 29 декабря 2021 года №186
    kaz: Қызылорда облысының Қазалы аудандық мәслихатының 2021 жылғы 29 желтоқсандағы №186 «2022-2024 жылдарға арналған Аранды ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/172382/rus
