act_code: '37172'
requisite: Қызылорда облысы Жалағаш аудандық мәслихатының 2007 жылғы 19 желтоқсандағы № 4-10 шешімі. Қызылорда облысының Әділет басқармасында 2008 жылғы 4 қаңтарда № 10-6-83 болып тіркелді
title:
  rus: Жалағаш ауданы бойынша салық салу обьектісінен алынатын тіркелген жиынтық салық ставкаларын белгілеу туралы
  kaz: Жалағаш ауданы бойынша салық салу обьектісінен алынатын тіркелген жиынтық салық ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-19
approved_by:
- '161006000002'
version_date:
  kaz: 2007-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/37172/kaz/19.12.2007
