act_code: '138038'
requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 27 декабря 2019 года № 378. Зарегистрировано Департаментом юстиции Кызылординской области 30 декабря 2019 года № 7092
title:
  rus: О бюджете сельского округа Айдарлы на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Айдарлы ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-27
approved_by:
- '161007000002'
version_date:
  kaz: 2020-09-16
  rus: 2020-09-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/138038/kaz/16.09.2020
  rus: https://zan.gov.kz/client/#!/doc/138038/rus/16.09.2020
caused_by:
  code: '146611'
  requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 16 сентября 2020 года № 435. Зарегистрировано Департаментом юстиции Кызылординской области 21 сентября 2020 года № 7653
  title:
    rus: О внесении изменений в решение Сырдарьинского районного маслихата от 27 декабря 2019 года №378 «О бюджете сельского округа Айдарлы на 2020-2022 годы»
    kaz: «2020 – 2022 жылдарға арналған Айдарлы ауылдық округінің бюджеті туралы» Сырдария аудандық мәслихаттың 2019 жылғы 27 желтоқсандағы №378 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/146611/rus
