act_code: '92212'
requisite: Решение акима Жанакорганского района Кызылординской области от 20 июля 2015 года № 17. Зарегистрировано Департаментом юстиции Кызылординской области 29 июля 2015 года № 5074. Утратило силу решением акима Жанакорганского района Кызылординской области от 2 октября 2015 года № 22
title:
  rus: Об объявлении чрезвычайной ситуации природного характера
  kaz: Табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-07-20
approved_by:
- '161009000001'
version_date:
  kaz: 2015-07-20
  rus: 2015-07-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/92212/kaz/20.07.2015
  rus: https://zan.gov.kz/client/#!/doc/92212/rus/20.07.2015
