act_code: '137567'
requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 23 декабря 2019 года № 361. Зарегистрировано Департаментом юстиции Кызылординской области 25 декабря 2019 года № 7049
title:
  rus: О районном бюджете на 2020-2022 годы
  kaz: 2020 – 2022 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-23
approved_by:
- '161007000002'
version_date:
  kaz: 2020-12-10
  rus: 2020-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/137567/kaz/10.12.2020
  rus: https://zan.gov.kz/client/#!/doc/137567/rus/10.12.2020
caused_by:
  code: '149937'
  requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 10 декабря 2020 года № 460. Зарегистрировано Департаментом юстиции Кызылординской области 14 декабря 2020 года № 7892
  title:
    rus: О внесении изменений в решение Сырдарьинского районного маслихата от 23 декабря 2019 года №361 «О районном бюджете на 2020-2022 годы»
    kaz: «2020–2022 жылдарға арналған аудандық бюджет туралы» Сырдария аудандық мәслихатының 2019 жылғы 23 желтоқсандағы №361 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149937/rus
