act_code: '192033'
requisite: Решение Аральского районного маслихата Кызылординской области от 26 декабря 2023 года № 148
title:
  rus: «О бюджете сельского округа Акирек на 2024-2026 годы»
  kaz: «2024-2026 жылдарға арналған Ақирек ауылдық округінің бюджеті туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-26
approved_by:
- '161003000002'
version_date:
  kaz: 2024-11-21
  rus: 2024-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/192033/kaz/21.11.2024
  rus: https://zan.gov.kz/client/#!/doc/192033/rus/21.11.2024
caused_by:
  code: '203226'
  requisite: Решение Аральского районного маслихата Кызылординской области от 21 ноября 2024 года № 292
  title:
    rus: О внесении изменений в решение Аральского районного маслихата Кызылординской области от 26 декабря 2023 года № 148 «О бюджете сельского округа Акирек  на 2024-2026 годы»
    kaz: Қызылорда облысы Арал аудандық мәслихатының 2023 жылғы 26 желтоқсандағы № 148  «2024-2026 жылдарға арналған Ақирек ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/203226/rus
