act_code: '179135'
requisite: Решение акима сельского округа Туран Шиелийского района Кызылординской области от 15 марта 2023 года № 99. Зарегистрировано Департаментом юстиции Кызылординской области 16 марта 2023 года № 8375-11
title:
  rus: О присвоении наименования безымянной улице села Ш.Кодаманова сельского округа Туран
  kaz: Тұран ауылдық округі Ш.Қодаманов ауылының атауы жоқ көшесіне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-03-15
approved_by:
- '161008022002'
version_date:
  kaz: 2023-03-15
  rus: 2023-03-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/179135/kaz/15.03.2023
  rus: https://zan.gov.kz/client/#!/doc/179135/rus/15.03.2023
