act_code: '125835'
requisite: Решение акима поселка Жосалы Кармакшинского района Кызылординской области от 12 октября 2018 года № 328. Зарегистрировано Департаментом юстиции Кызылординской области 6 ноября 2018 года № 6496
title:
  rus: О присвоении наименовании улицам и переименовании переулков поселка Жосалы
  kaz: Жосалы кентінің көшелеріне атау беру және тұйық көшелерді қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-10-12
approved_by:
- '161005001001'
version_date:
  kaz: 2018-10-12
  rus: 2018-10-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/125835/kaz/12.10.2018
  rus: https://zan.gov.kz/client/#!/doc/125835/rus/12.10.2018
