act_code: '43253'
requisite: Қызылорда облысы Қармақшы аудандық мәслихатының 2008 жылғы 24 желтоқсандағы N 84 шешімі. Қызылорда облысының Әділет департаменті Қармақшы аудандық Әділет басқармасында 2009 жылы 06 қаңтарда N 10-5-101 тіркелді. Қолданылу мерзімінің өтуіне байланысты күші жойылды (Қызылорда облысының Әділет департаменті Қармақшы аудандық Әділет басқармасының 2011 жылғы 15 тамыздағы N 2-9/2504 хаты)
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-24
approved_by:
- '161005000002'
version_date:
  kaz: 2009-02-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/43253/kaz/11.02.2009
caused_by:
  code: '44217'
  requisite: Решение от 11.02.2009 №97, Маслихат Кармакшинского района
  title:
    rus: '"2009 жылға арналған аудандық бюджет туралы" Қармақшы аудандық мәслихатының 2008 жылғы 24 желтоқсандағы кезекті 11 сессиясының N 84 шешіміне өзгерістер мен толықтырулар енгізу туралы'
    kaz: '"2009 жылға арналған аудандық бюджет туралы" Қармақшы аудандық мәслихатының 2008 жылғы 24 желтоқсандағы кезекті 11 сессиясының N 84 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/44217/rus
