act_code: '91299'
requisite: Решение Жанакорганского районного маслихата Кызылординской области от 05 мая 2015 года № 282. Зарегистрировано Департаментом юстиции Кызылординской области 04 июня 2015 года № 5011. Прекращено действие в связи с истечением срока
title:
  rus: О предоставлении мер социальной поддержки на 2015 год
  kaz: 2015 жылға әлеуметтік қолдау шараларын ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-05-05
approved_by:
- '161009000002'
version_date:
  kaz: 2015-05-05
  rus: 2015-05-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/91299/kaz/05.05.2015
  rus: https://zan.gov.kz/client/#!/doc/91299/rus/05.05.2015
