act_code: '44637'
requisite: Решение от 29.01.2009 №14/4, Маслихат Шиелийского района
title:
  rus: Біржолғы талон құнын белгілеу туралы
  kaz: Біржолғы талон құнын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-29
approved_by:
- '161008000002'
version_date:
  kaz: 2009-01-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/44637/kaz/29.01.2009
