act_code: '136847'
requisite: Решение акима сельского округа Оркендеу Казалинского района Кызылординской области от 5 декабря 2019 года № 21. Зарегистрировано Департаментом юстиции Кызылординской области 6 декабря 2019 года № 7010
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-05
approved_by:
- '161004012002'
version_date:
  kaz: 2019-12-05
  rus: 2019-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/136847/kaz/05.12.2019
  rus: https://zan.gov.kz/client/#!/doc/136847/rus/05.12.2019
