act_code: '124741'
requisite: Решение акима сельского округа Женишкекум Аральского района Кызылординской области от 18 сентября 2018 года № 12. Зарегистрировано Департаментом юстиции Кызылординской области 21 сентября 2018 года № 6434
title:
  rus: О переименовании улицы населенного пункта Токабай
  kaz: Тоқабай елді мекеніндегі көшені қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-09-18
approved_by:
- '161003013002'
version_date:
  kaz: 2018-09-18
  rus: 2018-09-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/124741/kaz/18.09.2018
  rus: https://zan.gov.kz/client/#!/doc/124741/rus/18.09.2018
