act_code: '122959'
requisite: Решение Кызылординского городского маслихата от 8 июня 2018 года № 161-26/8. Зарегистрировано Департаментом юстиции Кызылординской области 25 июня 2018 года № 6345
title:
  rus: Об утверждении регламента собрания местного сообщества
  kaz: Жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-06-08
approved_by:
- '161002000002'
version_date:
  kaz: 2022-03-29
  rus: 2022-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/122959/kaz/29.03.2022
  rus: https://zan.gov.kz/client/#!/doc/122959/rus/29.03.2022
caused_by:
  code: '165970'
  requisite: Решение Кызылординского городского маслихата от 29 марта 2022 года № 114-17/5
  title:
    rus: О внесении изменений в решение Кызылординского городского маслихата от 8 июня 2018 года №161-26/8 «Об утверждении регламента собрания местного сообщества на территории населенных пунктов города Кызылорда»
    kaz: «Қызылорда қаласы елді мекендерінің аумағындағы жергiлiктi қоғамдастық жиналысының регламентiн бекiту туралы» Қызылорда қалалық мәслихатының 2018 жылғы 8 маусымдағы №161-26/8 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/165970/rus
