act_code: '122959'
requisite: Решение Кызылординского городского маслихата от 8 июня 2018 года № 161-26/8. Зарегистрировано Департаментом юстиции Кызылординской области 25 июня 2018 года № 6345
title:
  rus: Об утверждении регламента собрания местного сообщества
  kaz: Жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-06-08
approved_by:
- '161002000002'
version_date:
  kaz: 2024-07-31
  rus: 2024-07-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/122959/kaz/31.07.2024
  rus: https://zan.gov.kz/client/#!/doc/122959/rus/31.07.2024
caused_by:
  code: '199375'
  requisite: Решение Кызылординского городского маслихата от 31 июля 2024 года № 175-23/3
  title:
    rus: О внесении изменений в решение Кызылординского городского маслихата от 8 июня 2018 года №161-26/8 «Об утверждении регламента собрания местного сообщества»
    kaz: «Жергілікті қоғамдастық жиналысының регламентін бекіту туралы» Қызылорда қалалық мәслихатының 2018 жылғы 8 маусымдағы №161-26/8 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/199375/rus
