act_code: '163009'
requisite: Решение Кызылординского городского маслихата от 29 декабря 2021 года № 107-16/10. Зарегистрировано в Министерстве юстиции Республики Казахстан 6 января 2022 года № 26393
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в городе Кызылорда
  kaz: Қызылорда қаласында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өтеу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-29
approved_by:
- '161002000002'
version_date:
  kaz: 2021-12-29
  rus: 2021-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/163009/kaz/29.12.2021
  rus: https://zan.gov.kz/client/#!/doc/163009/rus/29.12.2021
