act_code: '26006'
requisite: Решение от 27.09.2005 №213, Маслихат Кызылординской области
title:
  rus: '"Қызылорда облысы бойынша 2005-2015 жылдарға арналған энергия үнемдеу туралы" өңірлік бағдарламасын бекіту туралы'
  kaz: '"Қызылорда облысы бойынша 2005-2015 жылдарға арналған энергия үнемдеу туралы" өңірлік бағдарламасын бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-09-27
approved_by:
- '161000000002'
version_date:
  kaz: 2005-09-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/26006/kaz/27.09.2005
