act_code: '206456'
requisite: Решение Аральского районного маслихата Кызылординской области от 27 декабря 2024 года № 330
title:
  rus: «О бюджете сельского округа Сазды на 2025-2027 годы»
  kaz: «2025-2027 жылдарға арналған Сазды ауылдық округінің бюджеті туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '161003000002'
version_date:
  kaz: 2025-08-01
  rus: 2025-08-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/206456/kaz/01.08.2025
  rus: https://zan.gov.kz/client/#!/doc/206456/rus/01.08.2025
caused_by:
  code: '213164'
  requisite: Решение Аральского районного маслихата Кызылординской области от 1 августа 2025 года № 417
  title:
    rus: О внесении изменений в решение Аральского районного маслихата Кызылординской области от 27 декабря 2024 года №330 «О бюджете сельского округа Сазды на 2025-2027 годы»
    kaz: Қызылорда облысы Арал аудандық мәслихатының 2024 жылғы 27 желтоқсандағы №330 «2025-2027 жылдарға арналған Сазды ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/213164/rus
