act_code: '44078'
requisite: Решение от 12.01.2009 №59, Акимат аульного округа Жиделиарык
title:
  rus: Ауылдық округіндегі жаңа көшеге Мәулен Сырымбаевтың атын беру туралы
  kaz: Ауылдық округіндегі жаңа көшеге Мәулен Сырымбаевтың атын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-12
approved_by:
- '161008008001'
version_date:
  kaz: 2010-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/44078/kaz/23.12.2010
caused_by:
  code: '57091'
  requisite: Решение от 23.12.2010 №4, Акимат аульного округа Жиделиарык
  title:
    rus: '"Ауылдық округіндегі жаңа көшеге Мәулен Сырымбаевтың атын беру туралы" 2009 жылғы 12 қаңтардағы N 59 санды шешіміне өзгеріс енгізу туралы'
    kaz: '"Ауылдық округіндегі жаңа көшеге Мәулен Сырымбаевтың атын беру туралы" 2009 жылғы 12 қаңтардағы N 59 санды шешіміне өзгеріс енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/57091/rus
