act_code: '110175'
requisite: Решение Кызылординского областного маслихата от 15 февраля 2017 года № 89. Зарегистрировано Департаментом юстиции Кызылординской области 6 марта 2017 года № 5748. Утратило силу решением Кызылординского областного маслихата от 7 сентября 2022 года № 133
title:
  rus: Об утверждении перечня местных проектов государственно-частного по Кызылординской области партнерства, планируемых к реализации
  kaz: Қызылорда облысы бойынша іске асырылуы жоспарланатын тізбесін бекіту туралы әріптестік жобаларының жергілікті мемлекеттік-жекешелік
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-02-15
approved_by:
- '161000000002'
version_date:
  kaz: 2018-08-08
  rus: 2018-08-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/110175/kaz/08.08.2018
  rus: https://zan.gov.kz/client/#!/doc/110175/rus/08.08.2018
caused_by:
  code: '124287'
  requisite: Решение Кызылординского областного маслихата от 8 августа 2018 года № 232. Зарегистрировано Департаментом юстиции Кызылординской области 25 августа 2018 года № 6416. Утратило силу решением Кызылординского областного маслихата от 7 сентября 2022 года № 133
  title:
    rus: О внесении изменения в решение Кызылординского областного маслихата от 15 февраля 2017 года № 89 «Об утверждении перечня местных проектов государственно-частного партнерства, планируемых к реализации по Кызылординской области»
    kaz: «Қызылорда облысы бойынша іске асырылуы жоспарланатын жергілікті мемлекеттік-жекешелік әріптестік жобаларының тізбесін бекіту туралы» Қызылорда облыстық мәслихатының 2017 жылғы 15 ақпандағы № 89 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/124287/rus
