act_code: '22459'
requisite: Решение от 14.12.2004 №117, Маслихат Кызылординской области
title:
  rus: 2005 жылға арналған облыстық бюджет туралы
  kaz: 2005 жылға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-12-14
approved_by:
- '161000000002'
version_date:
  kaz: 2004-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/22459/kaz/14.12.2004
