act_code: '40314'
requisite: Қызылорда облысы Қазалы аудандық мәслихатының 2006 жылғы 22 желтоқсандағы № 226 шешімі. Қызылорда облысының Әділет басқармасында 2007 жылғы 15 қаңтарда № 10-4-58 болып тіркелді
title:
  rus: Қазалы ауданы аумағында кәсіпкерліктің кейбір түрлерімен айналысатын салық төлемгерлері үшін салық салу объектісінен алынатын тіркелген жиынтық салығының объектілеріне салынатын ставкасының мөлшерін бекіту жәйлі
  kaz: Қазалы ауданы аумағында кәсіпкерліктің кейбір түрлерімен айналысатын салық төлемгерлері үшін салық салу объектісінен алынатын тіркелген жиынтық салығының объектілеріне салынатын ставкасының мөлшерін бекіту жәйлі
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-22
approved_by:
- '161004000002'
version_date:
  kaz: 2006-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/40314/kaz/22.12.2006
