act_code: '151976'
requisite: Решение Шиелийского районного маслихата Кызылординской области от 29 декабря 2020 года № 65/21. Зарегистрировано Департаментом юстиции Кызылординской области 6 января 2021 года № 8073
title:
  rus: О бюджете сельского округа Когалы на 2021-2023 годы
  kaz: Қоғалы ауылдық округінің 2021-2023 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-29
approved_by:
- '161008000002'
version_date:
  kaz: 2021-12-15
  rus: 2021-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/151976/kaz/15.12.2021
  rus: https://zan.gov.kz/client/#!/doc/151976/rus/15.12.2021
caused_by:
  code: '162720'
  requisite: Решение Шиелийского районного маслихата Кызылординской области от 15 декабря 2021 года № 16/12
  title:
    rus: О внесении изменений в решение Шиелийского районного маслихата «О бюджете сельского округа Когалы на 2021-2023 годы» от 29 декабря 2020 года №65/21
    kaz: Шиелі аудандық мәслихатының 2020 жылғы 29 желтоқсандағы «Қоғалы ауылдық округінің 2021-2023 жылдарға арналған бюджеті туралы» №65/21 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/162720/rus
