act_code: '49401'
requisite: Решение от 11.12.2009 №192, Маслихат Кызылординской области
title:
  rus: 2010-2012 жылдарға арналған облыстық бюджет туралы
  kaz: 2010-2012 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-11
approved_by:
- '161000000002'
version_date:
  kaz: 2010-04-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/49401/kaz/12.04.2010
caused_by:
  code: '51941'
  requisite: Қызылорда облыстық мәслихатының 2010 жылғы 12 сәуірдегі N 224 шешімі. Қызылорда облысының Әділет департаментінде 2010 жылы 19 сәуірдегі N 4245 тіркелді. Қолданылу мерзімінің аяқталуына байланысты күші жойылды - (Қызылорда облыстық мәслихатының 2011 жылғы 26 қаңтардағы N 1-55М хатымен)
  title:
    rus: '"2010-2012 жылдарға арналған облыстық бюджет туралы" Қызылорда облыстық мәслихатының 2009 жылғы 11 желтоқсандағы N 192 шешіміне өзгерістер мен толықтырулар енгізу туралы'
    kaz: '"2010-2012 жылдарға арналған облыстық бюджет туралы" Қызылорда облыстық мәслихатының 2009 жылғы 11 желтоқсандағы N 192 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/51941/rus
