act_code: '44868'
requisite: Решение от 17.02.2009 №85, Маслихат Аральского района
title:
  rus: Аудан аумағында айына салық салу бірлігіне тіркелген салықтың базалық ставкаларының, елді мекендердің жерлеріне (үй іргесіндегі жер учаскелерін қоспағанда) салынатын базалық салық ставкаларының (алаңның бір шаршы метріне шаққанда) мөлшерлерін және біржолғы талон негізіндегі арнаулы, салық режимі бойынша кәсіпкерлік қызмет көрсететін жеке тұлғаларға берілетін біржолғы талондардың құндарын белгілеу туралы
  kaz: Аудан аумағында айына салық салу бірлігіне тіркелген салықтың базалық ставкаларының, елді мекендердің жерлеріне (үй іргесіндегі жер учаскелерін қоспағанда) салынатын базалық салық ставкаларының (алаңның бір шаршы метріне шаққанда) мөлшерлерін және біржолғы талон негізіндегі арнаулы, салық режимі бойынша кәсіпкерлік қызмет көрсететін жеке тұлғаларға берілетін біржолғы талондардың құндарын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-17
approved_by:
- '161003000002'
version_date:
  kaz: 2009-02-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/44868/kaz/17.02.2009
