act_code: '43601'
requisite: Решение от 31.12.2008 №14, Акимат Казалинского района
title:
  rus: Он жеті жасқа толатын азаматтарды әскерге шақыру учаскесіне тіркеу туралы
  kaz: Он жеті жасқа толатын азаматтарды әскерге шақыру учаскесіне тіркеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-31
approved_by:
- '161004000001'
version_date:
  kaz: 2008-12-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/43601/kaz/31.12.2008
