act_code: '54692'
requisite: Решение от 30.09.2010 №67, Акимат аульного округа Косшынырау
title:
  rus: Абай ауылындағы Жақыпбек Маханбетов көшесі қиылысынан Юрий Гагарин көшесіне дейінгі тұйық көшені ауылшаруашылық маманы Ұлы Отан соғысының ардагері Едербаев Асқар Есімімен қайта атау туралы
  kaz: Абай ауылындағы Жақыпбек Маханбетов көшесі қиылысынан Юрий Гагарин көшесіне дейінгі тұйық көшені ауылшаруашылық маманы Ұлы Отан соғысының ардагері Едербаев Асқар Есімімен қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-30
approved_by:
- '161002004001'
version_date:
  kaz: 2010-09-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/54692/kaz/13.09.2010
