act_code: '219285'
requisite: Решение Кызылординского областного маслихата от 09 декабря 2025 года № 209
title:
  rus: Об утверждении размера платы за один кубический метр питьевой воды, поданной из систем водоснабжения, включенных в перечень систем водоснабжения, стоимость услуг по подаче питьевой воды которых подлежит субсидированию в Кызылординской области
  kaz: Қызылорда облысында ауызсу беру бойынша көрсетілетін қызметтердің құны субсидиялауға жататын сумен жабдықтау жүйелерінің тізбесіне енгізілген сумен жабдықтау жүйелерінен берілген ауызсудың бір текше метрі үшін төлемақы мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-09
approved_by:
- '161000000002'
version_date:
  kaz: 2026-03-20
  rus: 2026-03-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/219285/kaz/20.03.2026
  rus: https://zan.gov.kz/client/#!/doc/219285/rus/20.03.2026
caused_by:
  code: '223306'
  requisite: Решение Кызылординского областного маслихата от 20 марта 2026 года № 239
  title:
    rus: О внесении изменений в решение Кызылординского областного маслихата от 9 декабря 2025 года № 209 «Об утверждении размера платы за один кубический метр питьевой воды, поданной из систем водоснабжения, включенных в перечень систем водоснабжения, стоимость услуг по подаче питьевой воды которых подлежит субсидированию»
    kaz: «Қызылорда облысында ауызсу беру бойынша көрсетілетін қызметтердің құны субсидиялауға жататын сумен жабдықтау жүйелерінің тізбесіне енгізілген сумен жабдықтау жүйелерінен берілген ауызсудың бір текше метрі үшін төлемақы мөлшерін бекіту туралы» Қызылорда облыстық мәслихатының 2025 жылғы 9 желтоқсандағы № 209 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/223306/rus
