act_code: '204795'
requisite: Решение Кызылординского городского маслихата от 18 декабря 2024 года № 223-32/1
title:
  rus: Об отверждении бюджета города Кызылорда на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Қызылорда қаласының бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-18
approved_by:
- '161002000002'
version_date:
  kaz: 2025-09-19
  rus: 2025-09-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/204795/kaz/19.09.2025
  rus: https://zan.gov.kz/client/#!/doc/204795/rus/19.09.2025
caused_by:
  code: '214568'
  requisite: Решение Кызылординского городского маслихата от 19 сентября 2025 года № 291-41/1
  title:
    rus: О внесении изменений в решение Кызылординского городского маслихата от 18 декабря 2024 года № 223-32/1 «Об утверждении бюджета города Кызылорда на 2025-2027 годы»
    kaz: «2025-2027 жылдарға арналған Қызылорда қаласының бюджетін бекіту туралы» Қызылорда қалалық мәслихатының 2024 жылғы 18 желтоқсандағы №223-32/1 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/214568/rus
