act_code: '204795'
requisite: Решение Кызылординского городского маслихата от 18 декабря 2024 года № 223-32/1
title:
  rus: Об отверждении бюджета города Кызылорда на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Қызылорда қаласының бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-18
approved_by:
- '161002000002'
version_date:
  kaz: 2024-12-18
  rus: 2024-12-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/204795/kaz/18.12.2024
  rus: https://zan.gov.kz/client/#!/doc/204795/rus/18.12.2024
