act_code: '55788'
requisite: Решение от 11.11.2010 №46, Акимат Жанакорганского района
title:
  rus: Аудан көлемінде тіркелетін жылы он жеті жасқа толатын еркек жынысты азаматтарды аудандық шақыру учаскесіне тіркеуге алу жұмыстарын жүргізу туралы
  kaz: Аудан көлемінде тіркелетін жылы он жеті жасқа толатын еркек жынысты азаматтарды аудандық шақыру учаскесіне тіркеуге алу жұмыстарын жүргізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-11
approved_by:
- '161009000001'
version_date:
  kaz: 2010-11-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/55788/kaz/11.11.2010
