act_code: '55787'
requisite: Решение от 17.11.2010 №76, Акимат аульного округа Томенарык
title:
  rus: Шамшидин Дүйсенбиевтің атына көше атын беру туралы
  kaz: Шамшидин Дүйсенбиевтің атына көше атын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-17
approved_by:
- '161009004001'
version_date:
  kaz: 2010-11-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/55787/kaz/17.11.2010
