act_code: '151275'
requisite: Решение Казалинского районного маслихата Кызылординской области от 25 декабря 2020 года № 556. Зарегистрировано Департаментом юстиции Кызылординской области 29 декабря 2020 года № 7978
title:
  rus: О бюджете сельского округа Майдакол на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Майдакөл ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-25
approved_by:
- '161004000002'
version_date:
  kaz: 2021-07-19
  rus: 2021-07-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/151275/kaz/19.07.2021
  rus: https://zan.gov.kz/client/#!/doc/151275/rus/19.07.2021
caused_by:
  code: '157436'
  requisite: Решение Казалинского районного маслихата Кызылординской области от 19 июля 2021 года № 76
  title:
    rus: О внесении изменений в решение Казалинского районного маслихата «О бюджете сельского округа Майдакол на 2021-2023 годы» от 25 декабря 2020 года №556
    kaz: Қазалы аудандық мәслихатының 2020 жылғы 25 желтоқсандағы №556 «2021-2023 жылдарға арналған Майдакөл ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/157436/rus
