act_code: '53977'
requisite: Решение от 06.08.2010 №133, Аким поселка Жосалы
title:
  rus: Жосалы кентінің бірқатар көшелерінің атауын өзгерту және бұрын атау берілмеген көшеге ат беру туралы
  kaz: Жосалы кентінің бірқатар көшелерінің атауын өзгерту және бұрын атау берілмеген көшеге ат беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-08-06
approved_by:
- '161005001001'
version_date:
  kaz: 2010-08-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/53977/kaz/06.08.2010
