act_code: '45268'
requisite: Решение от 27.03.2009 №143, Маслихат Кызылординской области
title:
  rus: Қызылорда облысының ауылдық жерлеріне жұмысқа жіберілген медицина және фармацевтика қызметкерлеріне әлеуметтік қолдау көрсетудің Қағидасын бекіту туралы
  kaz: Қызылорда облысының ауылдық жерлеріне жұмысқа жіберілген медицина және фармацевтика қызметкерлеріне әлеуметтік қолдау көрсетудің Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-03-27
approved_by:
- '161000000002'
version_date:
  kaz: 2009-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/45268/kaz/27.03.2009
