act_code: '101680'
requisite: Решение Кызылординского областного маслихата от 10 февраля 2016 года № 353
title:
  rus: О признании утратившим силу решение Кызылордского областного маслихата от 10 июля 2015 года № 282 "Об утверждении Правил застройки территории Кызылординской области"
  kaz: '"Қызылорда олысы аумағында құрылыс салу Қағидаларын бекіту туралы" Қызылорда облыстық мәслихатының 2015 жылғы 10 шілдедегі № 282 шешімінің күшін жою туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-02-10
approved_by:
- '161000000002'
version_date:
  kaz: 2016-02-10
  rus: 2016-02-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/101680/kaz/10.02.2016
  rus: https://zan.gov.kz/client/#!/doc/101680/rus/10.02.2016
