act_code: '37159'
requisite: Қызылорда облысы Қазалы аудандық мәслихатының 2007 жылғы 12 желтоқсандағы № 23 шешімі. Қызылорда облысының Әділет басқармасында 2007 жылғы 29 желтоқсанда № 10-4-72 болып тіркелді
title:
  rus: 2008 жылға арналған аудандық бюджет туралы
  kaz: 2008 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-25
approved_by:
- '161004000002'
version_date:
  kaz: 2007-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/37159/kaz/25.12.2007
