act_code: '62390'
requisite: Решение Казалинского районного маслихата Кызылординской области от 20 декабря 2011 года № 333. Зарегистрировано Департаментом юстиции Кызылординской области 30 декабря 2011 года за № 10-4-165. Утратило силу в связи с истечением срока применения - (письмо Казалинского районного маслихата Кызылординской области от 31 января 2013 года № 42)
title:
  rus: О районном бюджете на 2012-2014 годы
  kaz: 2012-2014 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-20
approved_by:
- '161004000002'
version_date:
  kaz: 2012-05-17
  rus: 2012-05-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/62390/kaz/17.05.2012
  rus: https://zan.gov.kz/client/#!/doc/62390/rus/17.05.2012
caused_by:
  code: '65607'
  requisite: Решение Казалинского районного маслихата Кызылординской области от 17 мая 2012 года № 33. Зарегистрировано Департаментом юстиции Кызылординской области 18 мая 2012 года № 10-4-176. Утратило силу в связи с истечением срока применения - (письмо Казалинского районного маслихата Кызылординской области от 31 января 2013 года № 42)
  title:
    rus: О внесении изменений и дополнений в решение XXXXIV сессии Казалинского районного маслихата от 20 декабря 2011 года N 333 "О районном бюджете на 2012-2014 годы"
    kaz: '"2012-2014 жылдарға арналған аудандық бюджет туралы" Қазалы аудандық Мәслихатының 2011 жылғы 20 желтоқсандағы ХХХXIV сессиясының N 333 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/65607/rus
