act_code: '179272'
requisite: Решение акима сельского округа Сунаката Жанакорганского района Кызылординской области от 20 марта 2023 года № 96. Зарегистрировано Департаментом юстиции Кызылординской области 27 марта 2023 года № 8379-11
title:
  rus: О присвоении наименования безымянной улице села Сунаката сельского округа Сунаката
  kaz: Сунақата ауылдық округі Сунақата ауылының атауы жоқ көшесіне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-03-20
approved_by:
- '161009003002'
version_date:
  kaz: 2023-03-20
  rus: 2023-03-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/179272/kaz/20.03.2023
  rus: https://zan.gov.kz/client/#!/doc/179272/rus/20.03.2023
