act_code: '9161'
requisite: Решение от 30.03.2001 №436, Аким Кызылординской области
title:
  rus: 1996-1999 жылдардағы облыстық «Инвестиция-Газ» орналастырудан түскен табыстарды әрі қарай пайдалану туралы
  kaz: 1996-1999 жылдардағы облыстық «Инвестиция-Газ» орналастырудан түскен табыстарды әрі қарай пайдалану туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-03-29
approved_by:
- '161000000003'
version_date:
  kaz: 2001-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/9161/kaz/29.03.2001
