act_code: '43111'
requisite: Қызылорда облысы Қызылорда қалалық мәслихатының 2008 жылғы 23 желтоқсандағы N 13/11 шешімі. Қызылорда облысының Әділет департаменті Қызылорда қалалық Әділет басқармасында 2008 жылғы 31 желтоқсанда N 10-1-103 тіркелді. Күші жойылды - Қызылорда облысы Қызылорда қалалық мәслихатының 2013 жылғы 20 маусымдағы N 18/2 шешімімен
title:
  rus: Қызылорда қаласының аумағындағы кәсіпкерліктің кейбір түрлерімен айналысатын салық төлемгерлері үшін салық салу объектісінен алынатын тіркелген салықтың ставкасының мөлшерін бекіту жайлы
  kaz: Қызылорда қаласының аумағындағы кәсіпкерліктің кейбір түрлерімен айналысатын салық төлемгерлері үшін салық салу объектісінен алынатын тіркелген салықтың ставкасының мөлшерін бекіту жайлы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-23
approved_by:
- '161002000002'
version_date:
  kaz: 2008-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/43111/kaz/23.12.2008
