act_code: '124897'
requisite: Решение Жанакорганского районного маслихата Кызылординской области от 14 сентября 2018 года № 257. Зарегистрировано Департаментом юстиции Кызылординской области 25 сентября 2018 года № 6436. Утратило силу решением Жанакорганского районного маслихата Кызылординской области от 27 июня 2023 года № 50
title:
  rus: Об определении размера и порядка возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану
  kaz: Мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсалған шығындарды өндіріп алу мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-09-14
approved_by:
- '161009000002'
version_date:
  kaz: 2018-09-14
  rus: 2018-09-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/124897/kaz/14.09.2018
  rus: https://zan.gov.kz/client/#!/doc/124897/rus/14.09.2018
