act_code: '163294'
requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 29 декабря 2021 года № 114
title:
  rus: Решение Сырдарьинского районного маслихата от 29 декабря 2021 года №114 «О бюджетах поселка и сельских округов Сырдарьинского района на 2022 – 2024 годы»
  kaz: «Сырдария ауданының кент және ауылдық округтерінің 2022 – 2024 жылдарға арналған бюджеттері туралы» Сырдария аудандық мәслихатының 2021 жылғы 29 желтоқсандағы №114 шешімі
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-29
approved_by:
- '161007000002'
version_date:
  kaz: 2021-12-29
  rus: 2021-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/163294/kaz/29.12.2021
  rus: https://zan.gov.kz/client/#!/doc/163294/rus/29.12.2021
