act_code: '79944'
requisite: Решение Аральского районного маслихата Кызылординской области от 11 апреля 2014 года N 155. Зарегистрировано Департаментом юстиции Кызылординской области 14 мая 2014 года за N 4670. Утратило силу решением Аральского районного маслихата Кызылординской области от 03.02.2016 № 284.
title:
  rus: О дополнительном регламентировании порядка проведения собраний, митингов, шествий, пикетов и демонстраций
  kaz: Жиналыстар, митингілер, шерулер, пикеттер және демонстрациялар өткізудің тәртібін қосымша реттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-11
approved_by:
- '161003000002'
version_date:
  kaz: 2014-04-11
  rus: 2014-04-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/79944/kaz/11.04.2014
  rus: https://zan.gov.kz/client/#!/doc/79944/rus/11.04.2014
