act_code: '7512'
requisite: Решение от 07.09.2000 №299, Аким Кызылординской области
title:
  rus: Шаруашылық есептегі «Қызылордасу-шаруашылығы» облыстық коммуналдық мемлекеттік кәсіпорны туралы
  kaz: Шаруашылық есептегі «Қызылордасу-шаруашылығы» облыстық коммуналдық мемлекеттік кәсіпорны туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-09-06
approved_by:
- '161000000003'
version_date:
  kaz: 2000-09-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/7512/kaz/06.09.2000
