act_code: '54877'
requisite: Решение от 07.09.2010 №179, Маслихат Аральского района
title:
  rus: '"Базарларда тауарлар өткізу, сату, жұмыстар орындау, қызмет көрсету жөніндегі қызметтерді жүзеге асыратын тұлғаларға қолданылатын біржолғы талондардың құнын" және "Дүркін-дүркін сипатындағы кәсіпкерлік қызметпен айналысатын жеке тұлғаларға берілетін біржолғы талондардың құнын" бекіту туралы'
  kaz: '"Базарларда тауарлар өткізу, сату, жұмыстар орындау, қызмет көрсету жөніндегі қызметтерді жүзеге асыратын тұлғаларға қолданылатын біржолғы талондардың құнын" және "Дүркін-дүркін сипатындағы кәсіпкерлік қызметпен айналысатын жеке тұлғаларға берілетін біржолғы талондардың құнын" бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-07
approved_by:
- '161003000002'
version_date:
  kaz: 2010-09-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/54877/kaz/07.09.2010
