act_code: '54740'
requisite: Решение от 25.08.2010 №45, Акимат аульного округа Майлытогай
title:
  rus: Майлытоғай ауылдық округіне қарасты атауы жоқ көшеге "Астана" атауын беру туралы
  kaz: Майлытоғай ауылдық округіне қарасты атауы жоқ көшеге "Астана" атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-08-25
approved_by:
- '161008017001'
version_date:
  kaz: 2010-08-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/54740/kaz/25.08.2010
