act_code: '193496'
requisite: Решение акима поселка Айтеке би Казалинского района Кызылординской области от 19 февраля 2024 года № 102
title:
  rus: О присвоении наименовании и переименованнии улиц и переулков
  kaz: Көшелерге және тұйық көшелерге атау беру және қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-19
approved_by:
- '161004001001'
version_date:
  kaz: 2024-02-19
  rus: 2024-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/193496/kaz/19.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193496/rus/19.02.2024
