act_code: '54514'
requisite: Решение от 09.08.2010 №108, Акимат аульного округа Дауылкол
title:
  rus: Тұрмағанбет ауылындағы бұрын атау берілмеген көшеге Бәйменов Уатай Балақбайұлының есімін беру туралы
  kaz: Тұрмағанбет ауылындағы бұрын атау берілмеген көшеге Бәйменов Уатай Балақбайұлының есімін беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-08-09
approved_by:
- '161005007001'
version_date:
  kaz: 2010-08-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/54514/kaz/09.08.2010
