act_code: '76273'
requisite: Решение Кызылординского городского маслихата от 24 декабря 2013 года № 25/2. Зарегистрировано Департаментом юстиции Кызылординской области 31 декабря 2013 года № 4569. Утратило силу в связи с истечением срока применения - (письмо Кызылординского городского маслихата от 12 января 2015 года № 17)
title:
  rus: О городском бюджете на 2014-2016 годы
  kaz: 2014-2016 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-24
approved_by:
- '161002000002'
version_date:
  kaz: 2014-11-27
  rus: 2014-11-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/76273/kaz/27.11.2014
  rus: https://zan.gov.kz/client/#!/doc/76273/rus/27.11.2014
caused_by:
  code: '84807'
  requisite: Решение Кызылординского городского маслихата от 27 ноября 2014 года № 36/1. Зарегистрировано Департаментом юстиции Кызылординской области 4 декабря 2014 года № 4808. Утратило силу в связи с истечением срока применения - (письмо Кызылординского городского маслихата от 12 января 2015 года № 17)
  title:
    rus: О внесении изменений в решение Кызылординского городского маслихата от 24 декабря 2013 года N 25/2 "О городском бюджете на 2014-2016 годы"
    kaz: '"2014-2016 жылдарға арналқан қалалық бюджет туралы" Қызылорда қалалық мәслихатының 2013 жылғы 24 желтоқсандағы N 25/2 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/84807/rus
