act_code: '54855'
requisite: Решение от 10.09.2010 №107, Акимат аульного округа Бестам
title:
  rus: Бестам ауылындағы Ленин көшесіне Әбекен Тоғызбаевтың есімін Беру туралы
  kaz: Бестам ауылындағы Ленин көшесіне Әбекен Тоғызбаевтың есімін Беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-10
approved_by:
- '161008004001'
version_date:
  kaz: 2010-09-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/54855/kaz/10.09.2010
