act_code: '128060'
requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 26 декабря 2018 года № 266. Зарегистрировано Департаментом юстиции Кызылординской области 28 декабря 2018 года № 6601
title:
  rus: О бюджете сельского округа Когалыколь на 2019-2021 годы
  kaz: Қоғалыкөл ауылдық округінің 2019–2021 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-26
approved_by:
- '161007000002'
version_date:
  kaz: 2019-02-22
  rus: 2019-02-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/128060/kaz/22.02.2019
  rus: https://zan.gov.kz/client/#!/doc/128060/rus/22.02.2019
caused_by:
  code: '129559'
  requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 22 февраля 2019 года № 286. Зарегистрировано Департаментом юстиции Кызылординской области 28 февраля 2019 года № 6721
  title:
    rus: О внесении изменений в решение Сырдарьинского районного маслихата от 26 декабря 2018 года №266 «О бюджете сельского округа Когалыколь на 2019-2021 годы»
    kaz: «Қоғалыкөл ауылдық округінің 2019–2021 жылдарға арналған бюджеті туралы» Сырдария аудандық мәслихаттың 2018 жылғы 26 желтоқсандағы №266 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/129559/rus
