act_code: '7983'
requisite: Решение от 06.01.2000 №128, Аким Кызылординской области
title:
  rus: Ауыл халқына алғашқы медициналық-санитарлық көмекті жақсарту және аудандық денсаулық сақтау бөлімдерін құру туралы
  kaz: Ауыл халқына алғашқы медициналық-санитарлық көмекті жақсарту және аудандық денсаулық сақтау бөлімдерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-01-06
approved_by:
- '161000000003'
version_date:
  kaz: 2000-01-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/7983/kaz/06.01.2000
