act_code: '125019'
requisite: Решение Кармакшинского районного маслихата Кызылординской области от 1 октября 2018 года № 202. Зарегистрировано Департаментом юстиции Кызылординской области 5 октября 2018 года № 6447
title:
  rus: О признании утратившим силу решения Кармакшинского районного маслихата «Об установлении единых ставок фиксированного налога на единицу объекта налогообложения» от 27 апреля 2012 года №26
  kaz: Қармақшы аудандық мәслихатының 2012 жылғы 27 сәуірдегі «Салық салу объектісінің бірлігіне тіркелген салықтық базалық ставкаларының мөлшерін белгілеу туралы» №26 шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-10-01
approved_by:
- '161005000002'
version_date:
  kaz: 2018-10-01
  rus: 2018-10-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/125019/kaz/01.10.2018
  rus: https://zan.gov.kz/client/#!/doc/125019/rus/01.10.2018
