act_code: '22146'
requisite: Решение Кызылординского областного маслихата от 25 июня 2004 года № 89. Зарегистрировано Департаментом юстиции Кызылординской области 14 июля 2004 года № 3895
title:
  rus: '"2005-2007 жылдарға арналған Қызылорда облысындағы тұрғын үй құрылысын дамыту" аймақтық бағдарламасын бекіту туралы'
  kaz: '"2005-2007 жылдарға арналған Қызылорда облысындағы тұрғын үй құрылысын дамыту" аймақтық бағдарламасын бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-06-24
approved_by:
- '161000000002'
version_date:
  kaz: 2004-06-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/22146/kaz/24.06.2004
