act_code: '221948'
requisite: Решение Шиелийского районного маслихата Кызылординской области от 24 декабря 2025 года № 39/4
title:
  rus: О бюджете сельского округа Актоган на 2026-2028 годы
  kaz: Ақтоған ауылдық округінің 2026-2028 жылдарға арналған  бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-24
approved_by:
- '161008000002'
version_date:
  kaz: 2025-12-24
  rus: 2025-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/221948/kaz/24.12.2025
  rus: https://zan.gov.kz/client/#!/doc/221948/rus/24.12.2025
