act_code: '43114'
requisite: Решение от 27.11.2008 №121, Акимат аульного округа Тонкерис
title:
  rus: '"Шеген Қодаманов ауылындағы жаңадан салынған көшелерге есім беру туралы"'
  kaz: '"Шеген Қодаманов ауылындағы жаңадан салынған көшелерге есім беру туралы"'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-11-27
approved_by:
- '161008022001'
version_date:
  kaz: 2008-11-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/43114/kaz/27.11.2008
