act_code: '55726'
requisite: Қызылорда облысы Қазалы аудандық мәслихатының 2010 жылғы 02 қарашадағы N 241 шешімі. Қызылорда облысының Әділет департаменті Қазалы ауданының Әділет басқармасында 2010 жылы 03 желтоқсанда N 10-4-129 тіркелді. Қолданылу мерзімінің аяқталуына байланысты күші жойылды - (Қызылорда облысы Қазалы аудандық мәслихатының 2014 жылғы 27 тамыздағы N 01-10/779 хатымен)
title:
  rus: Айына салық салу объектінің бірлігіне тіркелген салық ставкаларының мөлшерін бекіту туралы
  kaz: Айына салық салу объектінің бірлігіне тіркелген салық ставкаларының мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-02
approved_by:
- '161004000002'
version_date:
  kaz: 2010-11-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/55726/kaz/02.11.2010
