act_code: '62322'
requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 30 ноября 2011 года № 363. Зарегистрировано Департаментом юстиции Кызылординской области 23 декабря 2011 года за № 10-8-163
title:
  rus: О ставках земельного налога
  kaz: Жер салығының ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-11-30
approved_by:
- '161007000002'
version_date:
  kaz: 2011-11-30
  rus: 2011-11-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/62322/kaz/30.11.2011
  rus: https://zan.gov.kz/client/#!/doc/62322/rus/30.11.2011
