act_code: '136125'
requisite: Решение акима Жанакорганского района Кызылординской области от 19 ноября 2019 года № 1. Зарегистрировано Департаментом юстиции Кызылординской области 19 ноября 2019 года № 6973
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-11-19
approved_by:
- '161009000003'
version_date:
  kaz: 2019-11-19
  rus: 2019-11-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/136125/kaz/19.11.2019
  rus: https://zan.gov.kz/client/#!/doc/136125/rus/19.11.2019
