act_code: '98176'
requisite: Решение Аральского районного маслихата Кызылординской области от 24 декабря 2015 года № 273. Зарегистрировано Департаментом юстиции Кызылординской области 19 января 2016 года № 5304. Утратило силу решением Аральского районного маслихата Кызылординской области от 21 декабря 2016 года № 60
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсету, оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-24
approved_by:
- '161003000002'
version_date:
  kaz: 2016-08-03
  rus: 2016-08-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/98176/kaz/03.08.2016
  rus: https://zan.gov.kz/client/#!/doc/98176/rus/03.08.2016
caused_by:
  code: '105723'
  requisite: Решение Аральского районного маслихата Кызылординской области от 3 августа 2016 года № 32. Зарегистрировано Департаментом юстиции Кызылординской области 23 августа 2016 года № 5585. Утратило силу решением Аральского районного маслихата Кызылординской области от 21 декабря 2016 года № 60
  title:
    rus: О внесении изменений в решение Аральского районного маслихата от 24 декабря 2015 года № 273 "Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан"
    kaz: '"Әлеуметтік көмек көрсету, оның мөлшерлерін белгілеу және мұққтаж азаматтардың жекелеген санаттарының тізбесін айқындау Қағидаларын бекіту туралы" Арал аудандық мәслихатының 2015 жылғы 24 желтоқсандағы № 273 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/105723/rus
