act_code: '150561'
requisite: Решение Шиелийского районного маслихата Кызылординской области от 22 декабря 2020 года № 64/3. Зарегистрировано Департаментом юстиции Кызылординской области 24 декабря 2020 года № 7952
title:
  rus: О районном бюджете на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-22
approved_by:
- '161008000002'
version_date:
  kaz: 2021-03-16
  rus: 2021-03-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/150561/kaz/16.03.2021
  rus: https://zan.gov.kz/client/#!/doc/150561/rus/16.03.2021
caused_by:
  code: '153637'
  requisite: Решение Шиелийского районного маслихата Кызылординской области от 16 марта 2021 года № 3/2. Зарегистрировано Департаментом юстиции Кызылординской области 17 марта 2021 года № 8207
  title:
    rus: О внесении изменений в решение Шиелийского районного маслихата от 22 декабря 2020 года №64/3 «О районном бюджете на 2021-2023 годы»
    kaz: «2021-2023 жылдарға арналған аудандық бюджет туралы» Шиелі аудандық мәслихатының 2020 жылғы 22 желтоқсандағы №64/3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/153637/rus
