act_code: '137828'
requisite: Решение Шиелийского районного маслихата Кызылординской области от 27 декабря 2019 года № 49/16. Зарегистрировано Департаментом юстиции Кызылординской области 30 декабря 2019 года № 7060
title:
  rus: О бюджете сельского округа Актоган на 2020-2022 годы
  kaz: Ақтоған ауылдық округінің 2020-2022 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-27
approved_by:
- '161008000002'
version_date:
  kaz: 2019-12-27
  rus: 2019-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/137828/kaz/27.12.2019
  rus: https://zan.gov.kz/client/#!/doc/137828/rus/27.12.2019
