act_code: '150726'
requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 25 декабря 2020 года № 468. Зарегистрировано Департаментом юстиции Кызылординской области 28 декабря 2020 года № 7957
title:
  rus: О районном бюджете на 2021-2023 годы
  kaz: 2021 – 2023 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-25
approved_by:
- '161007000002'
version_date:
  kaz: 2021-09-01
  rus: 2021-09-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/150726/kaz/01.09.2021
  rus: https://zan.gov.kz/client/#!/doc/150726/rus/01.09.2021
caused_by:
  code: '158549'
  requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 1 сентября 2021 года № 48. Зарегистрировано в Министерстве юстиции Республики Казахстан 13 сентября 2021 года № 24321
  title:
    rus: О внесении изменений в решение Сырдарьинского районного маслихата от 25 декабря 2020 года № 468 «О районном бюджете на 2021-2023 годы»
    kaz: «2021–2023 жылдарға арналған аудандық бюджет туралы» Сырдария аудандық мәслихатының 2020 жылғы 25 желтоқсандағы № 468 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/158549/rus
