act_code: '128138'
requisite: Решение Кармакшинского районного маслихата Кызылординской области от 25 декабря 2018 года № 217. Зарегистрировано Департаментом юстиции Кызылординской области 28 декабря 2018 года № 6605
title:
  rus: О районном бюджете на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-25
approved_by:
- '161005000002'
version_date:
  kaz: 2019-05-24
  rus: 2019-05-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/128138/kaz/24.05.2019
  rus: https://zan.gov.kz/client/#!/doc/128138/rus/24.05.2019
caused_by:
  code: '132574'
  requisite: Решение Кармакшинского районного маслихата Кызылординской области от 24 мая 2019 года № 242. Зарегистрировано Департаментом юстиции Кызылординской области 30 мая 2019 года № 6801
  title:
    rus: О внесении изменений и дополнения в решение Кармакшинского районного маслихата от 25 декабря 2018 года №217 «О районном бюджете на 2019-2021 годы»
    kaz: «2019-2021 жылдарға арналған аудандық бюджет туралы» Қармақшы аудандық мәслихатының 2018 жылғы 25 желтоқсандағы №217 шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/132574/rus
