act_code: '128138'
requisite: Решение Кармакшинского районного маслихата Кызылординской области от 25 декабря 2018 года № 217. Зарегистрировано Департаментом юстиции Кызылординской области 28 декабря 2018 года № 6605
title:
  rus: О районном бюджете на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-25
approved_by:
- '161005000002'
version_date:
  kaz: 2018-12-25
  rus: 2018-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/128138/kaz/25.12.2018
  rus: https://zan.gov.kz/client/#!/doc/128138/rus/25.12.2018
