act_code: '94621'
requisite: Решение Шиелийского районного маслихата Кызылординской области от 01 октября 2015 года № 44/5. Зарегистрировано Департаментом юстиции Кызылординской области 20 октября 2015 года № 5182. Утратило силу решением Шиелийского районного маслихата Кызылординской области от 12.10.2016 № 5/9.
title:
  rus: О предоставлении социальной помощи на приобретение топлива
  kaz: Отын сатып алу үшін әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-10-01
approved_by:
- '161008000002'
version_date:
  kaz: 2015-10-01
  rus: 2015-10-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/94621/kaz/01.10.2015
  rus: https://zan.gov.kz/client/#!/doc/94621/rus/01.10.2015
