act_code: '94519'
requisite: Решение Жалагашского районного маслихата Кызылординской области от 23 сентября 2015 года № 46-8. Зарегистрировано Департаментом юстиции Кызылординской области 15 октября 2015 года № 5175. Утратило силу решением Жалагашского районного маслихата Кызылординской области от 30.09.2016 № 7-2.
title:
  rus: О повышении ставок земельного налога
  kaz: Жер салығының мөлшерлемесін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-09-23
approved_by:
- '161006000002'
version_date:
  kaz: 2015-09-23
  rus: 2015-09-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/94519/kaz/23.09.2015
  rus: https://zan.gov.kz/client/#!/doc/94519/rus/23.09.2015
