act_code: '123028'
requisite: Решение акима сельского округа Дауылкол Кармакшинского района Кызылординской области от 22 июня 2018 года № 21. Зарегистрировано Департаментом юстиции Кызылординской области 26 июня 2018 года № 6348
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-06-22
approved_by:
- '161005007002'
version_date:
  kaz: 2018-06-22
  rus: 2018-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/123028/kaz/22.06.2018
  rus: https://zan.gov.kz/client/#!/doc/123028/rus/22.06.2018
