act_code: '50268'
requisite: Решение от 25.12.2009 №40, Акимат Шиелийского района
title:
  rus: Шиелі ауданы бойынша он жеті жасқа толатын азаматтарды әскери есепке алу туралы
  kaz: Шиелі ауданы бойынша он жеті жасқа толатын азаматтарды әскери есепке алу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '161008000001'
version_date:
  kaz: 2009-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/50268/kaz/25.12.2009
