act_code: '29199'
requisite: Решение от 30.06.2006 №300, Маслихат Кызылординской области
title:
  rus: Қызылорда облысының елді мекендердегі жасыл желектерді күтіп ұстау мен қорғау Ережесін белгілеу туралы
  kaz: Қызылорда облысының елді мекендердегі жасыл желектерді күтіп ұстау мен қорғау Ережесін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-06-30
approved_by:
- '161000000002'
version_date:
  kaz: 2008-01-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/29199/kaz/29.01.2008
caused_by:
  code: '38016'
  requisite: "Қызылорда облыстық мәслихатының 2008 жылғы 29 қаңтардағы N 51 шешімі.\r\nҚызылорда облысының Әділет департаментінде 2008 жылғы 20 ақпанда N 4200 тіркелді. Күші жойылды - Қызылорда облыстық мәслихатының 2013 жылғы 25 сәуірдегі N 103 шешімімен"
  title:
    rus: '"Қызылорда облысының жасыл желектерді күтіп ұстау мен қорғау Ережесін белгілеу туралы" Қызылорда облыстық мәслихатының 2006 жылғы 30 маусымдағы N 300 шешіміне өзгерістер мен толықтырулар енгізу туралы'
    kaz: '"Қызылорда облысының жасыл желектерді күтіп ұстау мен қорғау Ережесін белгілеу туралы" Қызылорда облыстық мәслихатының 2006 жылғы 30 маусымдағы N 300 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/38016/rus
