act_code: '178610'
requisite: Решение акима поселка Саксаульск Аральского района Кызылординской области от 10 февраля 2023 года № 9. Зарегистрировано Департаментом юстиции Кызылординской области 10 февраля 2023 года № 8362-11
title:
  rus: О переименовании улиц и переулков поселка Саксаульск Аральского района Кызылординской области
  kaz: Қызылорда облысы Арал ауданы Сексеуіл кентінің көшелері мен тұйық көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-02-10
approved_by:
- '161003012001'
version_date:
  kaz: 2023-02-10
  rus: 2023-02-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/178610/kaz/10.02.2023
  rus: https://zan.gov.kz/client/#!/doc/178610/rus/10.02.2023
