act_code: '49498'
requisite: Решение от 23.12.2009 №169, Маслихат Казалинского района
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '161004000002'
version_date:
  kaz: 2010-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/49498/kaz/14.12.2010
caused_by:
  code: '56227'
  requisite: Решение от 14.12.2010 №244, Маслихат Казалинского района
  title:
    rus: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Қазалы аудандық Мәслихатының 2009 жылғы 23 желтоқсандағы XXI сессиясының N 169 шешіміне өзгерістер енгізу туралы'
    kaz: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Қазалы аудандық Мәслихатының 2009 жылғы 23 желтоқсандағы XXI сессиясының N 169 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/56227/rus
