act_code: '49498'
requisite: Решение от 23.12.2009 №169, Маслихат Казалинского района
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '161004000002'
version_date:
  kaz: 2010-07-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/49498/kaz/30.07.2010
caused_by:
  code: '54252'
  requisite: Қызылорда облысы Қазалы аудандық мәслихатының 2010 жылғы 30 шілдедегі N 220 шешімі. Қызылорда облысының Әділет департаменті Қазалы ауданының Әділет басқармасында 2010 жылы 01 қыркүйекте N 10-4-125 тіркелді. Күші жойылды - Қызылорда облысы Қазалы аудандық мәслихатының 2011 жылғы 04 наурыздағы N 272 шешімімен
  title:
    rus: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Қазалы аудандық мәслихатының 2009 жылғы 23 желтоқсандағы ХХІ сессиясының N 169 шешіміне өзгерістер мен толықтырулар енгізу туралы'
    kaz: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Қазалы аудандық мәслихатының 2009 жылғы 23 желтоқсандағы ХХІ сессиясының N 169 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/54252/rus
