act_code: '172976'
requisite: Решение Казалинского районного маслихата Кызылординской области от 29 декабря 2021 года № 197
title:
  rus: О бюджете сельского округа Г.Муратбаева на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Ғ.Мұратбаев ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-29
approved_by:
- '161004000002'
version_date:
  kaz: 2022-09-12
  rus: 2022-09-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/172976/kaz/12.09.2022
  rus: https://zan.gov.kz/client/#!/doc/172976/rus/12.09.2022
caused_by:
  code: '173157'
  requisite: Решение Казалинского районного маслихата Кызылординской области от 12 сентября 2022 года № 287
  title:
    rus: О внесении изменений в решение Казалинского районного маслихата Кызылординской области «О бюджете сельского округа Г. Муратбаев на 2022-2024 годы» от 29 декабря 2021 года №197
    kaz: Қызылорда облысының Қазалы аудандық мәслихатының 2021 жылғы 29 желтоқсандағы №197 «2022-2024 жылдарға арналған Ғ. Мұратбаев ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/173157/rus
