act_code: '214551'
requisite: Решение акима сельского округа Камыстыбас Аральского района Кызылординской области от 08 сентября 2025 года № 13
title:
  rus: О наименовании и переименовании улиц
  kaz: Көшеге атау беру және қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-08
approved_by:
- '161003006002'
version_date:
  kaz: 2025-09-08
  rus: 2025-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/214551/kaz/08.09.2025
  rus: https://zan.gov.kz/client/#!/doc/214551/rus/08.09.2025
