act_code: '61981'
requisite: Решение Кызылординского областного маслихата от 6 декабря 2011 года № 330. Зарегистрировано Департаментом юстиции Кызылординской области 20 декабря 2011 года за № 4282. Утратило силу в связи с истечением срока применения - (письмо маслихата Кызылординской области от 22 января 2013 года № 1-03-11/29М)
title:
  rus: Об областном бюджете на 2012-2014 годы
  kaz: 2012-2014 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-06
approved_by:
- '161000000002'
version_date:
  kaz: 2012-10-30
  rus: 2012-10-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/61981/kaz/30.10.2012
  rus: https://zan.gov.kz/client/#!/doc/61981/rus/30.10.2012
caused_by:
  code: '68462'
  requisite: Решение маслихата Кызылординской области от 30 октября 2012 года № 55. Зарегистрировано Департаментом юстиции Кызылординской области 9 ноября 2012 года за № 4337. Утратило силу в связи с истечением срока применения - (письмо маслихата Кызылординской области от 22 января 2013 года № 1-03-11/29М)
  title:
    rus: О внесении изменений и дополнений в решение Кызылординского областного маслихата от 6 декабря 2011 года N 330 "Об областном бюджете на 2012-2014 годы"
    kaz: '"2012-2014 жылдарға арналған облыстық бюджет туралы" Қызылорда облыстық мәслихатының 2011 жылғы 6 желтоқсандағы N 330 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/68462/rus
