act_code: '84002'
requisite: Решение Казалинского районного маслихата Кызылординской области от 20 октября 2014 года № 251. Зарегистрировано Департаментом юстиции Кызылординской области 31 октября 2014 года № 4785. Утратило силу решением Казалинского районного маслихата Кызылординской области от 23 февраля 2017 года № 87
title:
  rus: О повышении базовых налоговых ставок
  kaz: Жер салығының базалық мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-10-20
approved_by:
- '161004000002'
version_date:
  kaz: 2015-03-27
  rus: 2015-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/84002/kaz/27.03.2015
  rus: https://zan.gov.kz/client/#!/doc/84002/rus/27.03.2015
caused_by:
  code: '88431'
  requisite: ''
  title:
    rus: О внесении изменений в решение Казалинского районного маслихата от 20 октября 2014 года №251 «О повышении базовых налоговых ставок»
    kaz: «Базалық салық ставкаларын жоғарылату туралы» Қазалы аудандық мәслихатының 2014 жылғы 20 қазандағы № 251 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/88431/rus
