act_code: '42284'
requisite: Қызылорда облысы Шиелі аудандық мәслихатының 2008 жылғы 08 қазандағы N 11/11 шешімі. Қызылорда облысының Әділет департаменті Шиелі аудандық Әділет басқармасында 2008 жылы 11 қарашада N 10-9-69 тіркелді. Күші жойылды - Қызылорда облысы Шиелі аудандық мәслихатының 2009 жылғы 29 қаңтардағы N 14/4 шешімімен
title:
  rus: Аудан көлемінде орналасқан базарлар мен сауда қатарларында тауарларды сату құқығы үшін алынатын алымның мөлшерін қайта белгілеу туралы
  kaz: Аудан көлемінде орналасқан базарлар мен сауда қатарларында тауарларды сату құқығы үшін алынатын алымның мөлшерін қайта белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-10-08
approved_by:
- '161008000002'
version_date:
  kaz: 2008-10-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/42284/kaz/08.10.2008
