act_code: '97336'
requisite: Решение Жанакорганского районного маслихата Кызылординской области от 24 декабря 2015 года N 339. Зарегистрировано Департаментом юстиции Кызылординской области 30 декабря 2015 года N 5283
title:
  rus: '"О районном бюджете на 2016-2018 годы"'
  kaz: '"2016-2018 жылдарға арналған аудандық бюджет туралы"'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-24
approved_by:
- '161009000002'
version_date:
  kaz: 2016-10-12
  rus: 2016-10-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/97336/kaz/12.10.2016
  rus: https://zan.gov.kz/client/#!/doc/97336/rus/12.10.2016
caused_by:
  code: '106935'
  requisite: Решение Жанакорганского районного маслихата Кызылординской области от 12 октября 2016 года № 01-01-03/58. Зарегистрировано Департаментом юстиции Кызылординской области 14 октября 2016 года № 5619
  title:
    rus: О внесении изменений в решение районного маслихата от 24 декабря 2015 года №339 «О районном бюджетена 2016-2018 годы»
    kaz: «2016-2018 жылдарға арналған аудандық бюджет туралы» аудан мәслихатының 2015 жылғы 24 желтоқсандағы №339 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/106935/rus
