act_code: '46170'
requisite: Решение от 04.05.2009 №135, Маслихат Жанакорганского района
title:
  rus: Халықты жұмыспен қамтудың кейбір мәселелерін реттеуге байланысты қағидаларды бекіту туралы
  kaz: Халықты жұмыспен қамтудың кейбір мәселелерін реттеуге байланысты қағидаларды бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-05-04
approved_by:
- '161009000002'
version_date:
  kaz: 2009-05-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/46170/kaz/04.05.2009
