act_code: '164063'
requisite: Решение акима Кармакшинского района Кызылординской области от 11 января 2022 года № 1459. Зарегистрировано в Министерстве юстиции Республики Казахстан 19 января 2022 года № 26547
title:
  rus: О переименовании следующих частей поселка Жосалы Кармакшинский район Кызылординской области
  kaz: Қызылорда облысы Қармақшы ауданы Жосалы кентінің келесі бөліктерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-01-11
approved_by:
- '161005000003'
version_date:
  kaz: 2022-01-11
  rus: 2022-01-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/164063/kaz/11.01.2022
  rus: https://zan.gov.kz/client/#!/doc/164063/rus/11.01.2022
