act_code: '59851'
requisite: Решение Кызылординского областного маслихата от 29 июня 2011 года N 297. Зарегистрировано Департаментом юстиции Кызылординской области 2 августа 2011 года за № 4273. Утратило силу решением Кызылординского областного маслихата от 21 августа 2013 года № 140
title:
  rus: Об утверждении Правил проведения собрания (схода) местного сообщества и принятия решений
  kaz: Жергілікті қоғамдастықтың жиналысын (жиынын) өткізудің және шешімдерін қабылдаудың ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-06-29
approved_by:
- '161000000002'
version_date:
  kaz: 2011-06-29
  rus: 2011-06-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/59851/kaz/29.06.2011
  rus: https://zan.gov.kz/client/#!/doc/59851/rus/29.06.2011
