act_code: '163156'
requisite: Решение Аральского районного маслихата Кызылординской области от 24 декабря 2021 года № 161. Зарегистрировано в Министерстве юстиции Республики Казахстан 29 декабря 2021 года № 26183
title:
  rus: О районном бюджете на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '161003000002'
version_date:
  kaz: 2022-08-22
  rus: 2022-08-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/163156/kaz/22.08.2022
  rus: https://zan.gov.kz/client/#!/doc/163156/rus/22.08.2022
caused_by:
  code: '170990'
  requisite: Решение Аральского районного маслихата Кызылординской области от 22 августа 2022 года № 278
  title:
    rus: О внесении изменений в решение Аральского районного маслихата Кызылординской области от 24 декабря 2021 года № 161 «О районном бюджете на 2022-2024 годы»
    kaz: Қызылорда облысы Арал аудандық мәслихатының 2021 жылғы 24 желтоқсандағы № 161 «2022-2024 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/170990/rus
