act_code: '163025'
requisite: Решение Кармакшинского районного маслихата Кызылординской области от 23 декабря 2021 года № 118
title:
  rus: О бюджете сельского округа Акжар на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Ақжар ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-23
approved_by:
- '161005000002'
version_date:
  kaz: 2022-03-25
  rus: 2022-03-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/163025/kaz/25.03.2022
  rus: https://zan.gov.kz/client/#!/doc/163025/rus/25.03.2022
caused_by:
  code: '165665'
  requisite: Решение Кармакшинского районного маслихата Кызылординской области от 25 марта 2022 года № 145
  title:
    rus: О внесении изменений и дополнений в решение Кармакшинского районного маслихата Кызылординской области от 23 декабря 2021 года №118 «О бюджете сельского округа Акжар на 2022-2024 годы»
    kaz: Қызылорда облысы Қармақшы аудандық мәслихатының 2021 жылғы 23 желтоқсандағы №118 «2022-2024 жылдарға арналған Ақжар ауылдық округінің бюджеті туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/165665/rus
