act_code: '150421'
requisite: Решение Кызылординского областного маслихата от 11 декабря 2020 года № 521. Зарегистрировано Департаментом юстиции Кызылординской области 22 декабря 2020 года № 7946. Утратило силу решением Кызылординского областного маслихата от 16 июля 2021 года № 34
title:
  rus: Об утверждении правил по обеспечению общественного порядка и безопасности, предупреждению и ликвидации чрезвычайных ситуаций, за нарушение которых предусмотрена административная ответственность при их возникновении на территории Кызылординской области
  kaz: Қызылорда облысының аумағында оларды бұзғаны үшін әкімшілік жауаптылық көзделген төтенше жағдайлар туындаған кезде қоғамдық тәртіп пен қауіпсіздікті қамтамасыз ету, олардың алдын алу және жою жөніндегі қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-11
approved_by:
- '161000000002'
version_date:
  kaz: 2020-12-11
  rus: 2020-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/150421/kaz/11.12.2020
  rus: https://zan.gov.kz/client/#!/doc/150421/rus/11.12.2020
