act_code: '135110'
requisite: Решение акима сельского округа Косшынырау города Кызылорда Кызылординской области от 2 октября 2019 года № 80. Зарегистрировано Департаментом юстиции Кызылординской области 4 октября 2019 года № 6929
title:
  rus: О снятии ограничительных мероприятий на территории крестьянского хозяйства «Кылыш» расположенного в сельском округе Косшынырау
  kaz: Қосшыңырау ауылдық округінде орналасқан «Кылыш» шаруашылық қожалығы аумағында шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-10-02
approved_by:
- '161002004002'
version_date:
  kaz: 2019-10-02
  rus: 2019-10-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/135110/kaz/02.10.2019
  rus: https://zan.gov.kz/client/#!/doc/135110/rus/02.10.2019
