act_code: '107256'
requisite: Решение Кызылординского областного маслихата от 28 сентября 2016 года № 58. Зарегистрировано Департаментом юстиции Кызылординской области 28 октября 2016 года № 5633
title:
  rus: Об утверждении границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки в городе Кызылорде
  kaz: Қызылорда қаласындағы бағалау аймақтарының шекараларын және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-09-28
approved_by:
- '161000000002'
version_date:
  kaz: 2016-09-28
  rus: 2016-09-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/107256/kaz/28.09.2016
  rus: https://zan.gov.kz/client/#!/doc/107256/rus/28.09.2016
