act_code: '118050'
requisite: Решение Жанакорганского районного маслихата Кызылординской области от 26 декабря 2017 года № 05-16/191. Зарегистрировано Департаментом юстиции Кызылординской области 11 января 2018 года № 6145. Утратило силу решением Жанакорганского районного маслихата Кызылординской области от 20 декабря 2024 года № 298
title:
  rus: Об утверждении размера и порядка оказания жилищной помощи
  kaz: Тұрғын үй көмегін көрсетудің тәртібі мен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-26
approved_by:
- '161009000002'
version_date:
  kaz: 2019-12-26
  rus: 2019-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/118050/kaz/26.12.2019
  rus: https://zan.gov.kz/client/#!/doc/118050/rus/26.12.2019
caused_by:
  code: '137988'
  requisite: Решение Жанакорганского районного маслихата Кызылординской области от 26 декабря 2019 года № 391. Зарегистрировано Департаментом юстиции Кызылординской области 30 декабря 2019 года № 7076. Утратило силу решением Жанакорганского районного маслихата Кызылординской области от 20 декабря 2024 года № 298
  title:
    rus: О внесении изменения в решение Жанакорганского районного маслихата от 26 декабря 2017 года № 05-16/191 «Об утверждении размера и порядка оказания жилищной помощи»
    kaz: «Тұрғын үй көмегін көрсетудің тәртібі мен мөлшерін бекіту туралы» Жаңақорған аудандық мәслихатының 2017 жылғы 26 желтоқсаныңдағы № 05-16/191 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/137988/rus
