act_code: '44754'
requisite: Решение от 11.02.2009 №15/4, Маслихат Шиелийского района
title:
  rus: Ауыл шаруашылығы мақсатындағы, елді мекендердің жерлеріне (үй іргесіндегі жер учаскелерін қоспағанда), елді мекендерден тыс орналасқан өнеркәсіп жерлеріне салынатын базалық салық ставкаларын жоғарылату туралы
  kaz: Ауыл шаруашылығы мақсатындағы, елді мекендердің жерлеріне (үй іргесіндегі жер учаскелерін қоспағанда), елді мекендерден тыс орналасқан өнеркәсіп жерлеріне салынатын базалық салық ставкаларын жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-11
approved_by:
- '161008000002'
version_date:
  kaz: 2009-02-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/44754/kaz/11.02.2009
