act_code: '176198'
requisite: Решение Кармакшинского районного маслихата Кызылординской области от 21 декабря 2022 года № 260
title:
  rus: О бюджете сельского округа Алдашбай Ахун на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Алдашбай Ахун ауылдық округінің  бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-21
approved_by:
- '161005000002'
version_date:
  kaz: 2023-08-16
  rus: 2023-08-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/176198/kaz/16.08.2023
  rus: https://zan.gov.kz/client/#!/doc/176198/rus/16.08.2023
caused_by:
  code: '185596'
  requisite: Решение Кармакшинского районного маслихата Кызылординской области от 16 августа 2023 года № 71
  title:
    rus: О внесении изменений и дополнений в решение Кармакшинского районного маслихата Кызылординской области «О бюджете сельского округа Алдашбай Ахун на 2023-2025 годы» от 21 декабря 2022 года №260
    kaz: Қызылорда облысы Қармақшы аудандық мәслихатының 2022 жылғы 21 желтоқсандағы №260 «2023-2025 жылдарға арналған Алдашбай Ахун ауылдық округінің бюджеті туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/185596/rus
