act_code: '79851'
requisite: Решение Шиелийского районного маслихата Кызылординской области от 11 апреля 2014 года N 27/5. Зарегистрировано Департаментом юстиции Кызылординской области 12 мая 2014 года N 4663. Утратило силу решением Шиелийского районного маслихата Кызылординской области от 7 августа 2018 года № 27/5
title:
  rus: Об утверждении Правил оказания жилищной помощи
  kaz: Тұрғын үй көмегін көрсету Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-11
approved_by:
- '161008000002'
version_date:
  kaz: 2015-05-04
  rus: 2015-05-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/79851/kaz/04.05.2015
  rus: https://zan.gov.kz/client/#!/doc/79851/rus/04.05.2015
caused_by:
  code: '90171'
  requisite: Решение Шиелийского районного маслихата Кызылординской области от 4 мая 2015 года N 40/3. Зарегистрировано Департаментом юстиции Кызылординской области 29 мая 2015 года N 4999. Утратило силу решением Шиелийского районного маслихата Кызылординской области от 7 августа 2018 года № 27/5
  title:
    rus: О внесении изменений в решение районного маслихата от 11 апреля 2014 года № 27/5 "Об утверждении Правил оказания жилищной помощи"
    kaz: '"Тұрғын үй көмегін көрсету Қағидасын бекіту туралы" аудандық мәслихаттың 2014 жылғы 11 сәуірдегі №27/5 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/90171/rus
