act_code: '164133'
requisite: Решение Шиелийского районного маслихата Кызылординской области от 30 декабря 2021 года № 18/24
title:
  rus: О бюджете сельского округа Жиделиарык на 2022-2024 годы
  kaz: Жиделіарық ауылдық округінің 2022-2024 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '161008000002'
version_date:
  kaz: 2022-04-08
  rus: 2022-04-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/164133/kaz/08.04.2022
  rus: https://zan.gov.kz/client/#!/doc/164133/rus/08.04.2022
caused_by:
  code: '166565'
  requisite: Решение Шиелийского районного маслихата Кызылординской области от 8 апреля 2022 года № 21/24
  title:
    rus: О внесении изменений в решение Шиелийского районного маслихата «О бюджете сельского округа Жиделиарык на 2022-2024 годы» от 30 декабря 2021 года № 18/24
    kaz: Шиелі аудандық мәслихатының 2021 жылғы 30 желтоқсандағы «Жиделіарық ауылдық округінің 2022-2024 жылдарға арналған бюджеті туралы» № 18/24 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/166565/rus
