act_code: '94368'
requisite: Решение от 22.09.2015 №295, Маслихат Кармакшинского района
title:
  rus: Об утверждении проекта (схемы) зонирования земель, границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки поселка Торетам
  kaz: Төретам кентінің жерлерін аймақтарға бөлу жобасын (схемасын), бағалау аймақтарының шекараларын және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-09-22
approved_by:
- '161005000002'
version_date:
  kaz: 2015-09-22
  rus: 2015-09-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/94368/kaz/22.09.2015
  rus: https://zan.gov.kz/client/#!/doc/94368/rus/22.09.2015
