act_code: '71932'
requisite: Решение Кармакшинского районного маслихата Кызылординской области от 27 марта 2013 года № 84. Зарегистрировано Департаментом юстиции Кызылординской области 11 апреля 2013 года за № 4428. Утратило силу в связи с истечением срока применения - (письмо Кармакшинского районного маслихата Кызылординской области от 12 августа 2014 года № 03-11/143)
title:
  rus: Об оказании единовременной материальной помощи
  kaz: Біржолғы материалдық көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-03-27
approved_by:
- '161005000002'
version_date:
  kaz: 2013-03-27
  rus: 2013-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/71932/kaz/27.03.2013
  rus: https://zan.gov.kz/client/#!/doc/71932/rus/27.03.2013
