act_code: '206370'
requisite: Решение Аральского районного маслихата Кызылординской области от 27 декабря 2024 года № 323
title:
  rus: «О бюджете сельского округа Атанши на 2025-2027 годы»
  kaz: «2025-2027 жылдарға арналған Атанши ауылдық округінің бюджеті туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '161003000002'
version_date:
  kaz: 2024-12-27
  rus: 2024-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/206370/kaz/27.12.2024
  rus: https://zan.gov.kz/client/#!/doc/206370/rus/27.12.2024
