act_code: '48327'
requisite: Қызылорда облысы Жаңақорған аудандық мәслихатының 2009 жылғы 25 қыркүйектегі N 162 шешімі. Қызылорда облысының Әділет департаменті Жаңақорған аудандық Әділет басқармасында 2009 жылы 30 қазанда N 10-7-82 тіркелді. Күші жойылды - Қызылорда облысы Жаңақорған аудандық мәслихатының 2010 жылғы 05 наурыздағы N 204 шешімімен
title:
  rus: Аз қамтамасыз етілген азаматтарға тұрғын үйді ұстауға және коммуналдық қызметтің ақысын төлеуге арналған тұрғын үй көмегін беру Қағидасы мен коммуналдық шығындар мөлшерінің нормаларын бекіту туралы
  kaz: Аз қамтамасыз етілген азаматтарға тұрғын үйді ұстауға және коммуналдық қызметтің ақысын төлеуге арналған тұрғын үй көмегін беру Қағидасы мен коммуналдық шығындар мөлшерінің нормаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-09-25
approved_by:
- '161009000002'
version_date:
  kaz: 2009-09-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/48327/kaz/25.09.2009
