act_code: '44639'
requisite: Решение от 31.01.2009 №115, Маслихат Казалинского района
title:
  rus: Айына салық салу бірлігіне тіркелген салық ставкаларының мөлшерін бекіту туралы
  kaz: Айына салық салу бірлігіне тіркелген салық ставкаларының мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-31
approved_by:
- '161004000002'
version_date:
  kaz: 2009-01-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/44639/kaz/31.01.2009
