act_code: '56354'
requisite: Решение от 18.11.2010 №1075, Аким поселка Шиели
title:
  rus: Шиелі кентінен атауы жоқ көшеге Мұхамеджан Қаратаевтың есімін беру туралы
  kaz: Шиелі кентінен атауы жоқ көшеге Мұхамеджан Қаратаевтың есімін беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-18
approved_by:
- '161008023001'
version_date:
  kaz: 2010-11-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/56354/kaz/18.11.2010
