act_code: '103405'
requisite: Решение Кызылординского областного маслихата от 19 мая 2016 года № 26. Зарегистрировано Департаментом юстиции Кызылординской области 13 июня 2016 года № 5535. Утратило силу решением Кызылординского областного маслихата от от 17 марта 2021 года № 14
title:
  rus: Об утверждении границы охранной зоны, зоны регулирования застройки и зоны охраняемого природного ландшафта памятника истроии и культуры "Комплекс наскальных изображений урочища Сауыскандык", расположенного в Шиелийском районе"
  kaz: Шиелі ауданында орналасқан "Сауысқандық шатқалындағы жартастағы бейнелер кешені" тарих және мәдениет ескерткішінің қорғау аймағының, құрылыс салуды реттеу аймағының және қорғалатын табиғат ландшафт аймағының шекарасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-05-19
approved_by:
- '161000000002'
version_date:
  kaz: 2016-05-19
  rus: 2016-05-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/103405/kaz/19.05.2016
  rus: https://zan.gov.kz/client/#!/doc/103405/rus/19.05.2016
