act_code: '229003'
requisite: Решение Жанакорганского районного маслихата Кызылординской области от 12 августа 2026 года № 564
title:
  rus: О предоставлении мер социальной поддержки
  kaz: Әлеуметтік қолдау шараларын көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-08-12
approved_by:
- '161009000002'
version_date:
  kaz: 2026-08-12
  rus: 2026-08-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/229003/kaz/12.08.2026
  rus: https://zan.gov.kz/client/#!/doc/229003/rus/12.08.2026
