act_code: '7984'
requisite: Решение от 20.12.2000 №373, Аким Кызылординской области
title:
  rus: Облыс көлемінде 1984 жылы туылған азаматтарды шақыру учаскелерінде тіркеуді жүргізу туралы
  kaz: Облыс көлемінде 1984 жылы туылған азаматтарды шақыру учаскелерінде тіркеуді жүргізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-12-20
approved_by:
- '161000000003'
version_date:
  kaz: 2000-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/7984/kaz/20.12.2000
