act_code: '98166'
requisite: Решение Жанакорганского районного маслихата Кызылординской области от 24 декабря 2015 года N 342. Зарегистрировано Департаментом юстиции Кызылординской области 18 января 2016 года N 5302
title:
  rus: О предоставлении мер социальной поддержки на 2016 год
  kaz: 2016 жылға әлеуметтік қолдау шараларын ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-24
approved_by:
- '161009000002'
version_date:
  kaz: 2015-12-24
  rus: 2015-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/98166/kaz/24.12.2015
  rus: https://zan.gov.kz/client/#!/doc/98166/rus/24.12.2015
