act_code: '1221'
requisite: Решение акима Кызылординской области от 24 февраля 1998 года № 668. Зарегистрировано Управлением юстиции Кызылординской области 18 июня 1998 года № 24. Утратило силу постановлением акимата Кызылординской области от 20 декабря 2004 года № 247
title:
  rus: О размере сбора за право реализации товаров на рынках и определении категорий рынков и торговых рядов
  kaz: Базарларда тауарларды сату құқығы үшін алынатын алым мөлшерін және базар мен сауда қатарларының санаттарын анықтау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-02-24
approved_by:
- '161000000003'
version_date:
  kaz: 1998-02-24
  rus: 1998-02-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/1221/kaz/24.02.1998
  rus: https://zan.gov.kz/client/#!/doc/1221/rus/24.02.1998
