act_code: '150935'
requisite: Решение Казалинского районного маслихата Кызылординской области от 23 декабря 2020 года № 535. Зарегистрировано Департаментом юстиции Кызылординской области 29 декабря 2020 года № 7967
title:
  rus: О районном бюджете на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-23
approved_by:
- '161004000002'
version_date:
  kaz: 2021-08-27
  rus: 2021-08-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/150935/kaz/27.08.2021
  rus: https://zan.gov.kz/client/#!/doc/150935/rus/27.08.2021
caused_by:
  code: '158480'
  requisite: Решение Казалинского районного маслихата Кызылординской области от 27 августа 2021 года № 90. Зарегистрировано в Министерстве юстиции Республики Казахстан 7 сентября 2021 года № 24266
  title:
    rus: О внесении изменений в решение Казалинского районного маслихата Кызылординской области «О районном бюджете на 2021-2023 годы» от 23 декабря 2020 года №535
    kaz: Қызылорда облысы Қазалы аудандық мәслихатының 2020 жылғы 23 желтоқсандағы №535 «2021-2023 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/158480/rus
