act_code: '138643'
requisite: Решение Казалинского районного маслихата Кызылординской области от 26 декабря 2019 года № 365. Зарегистрировано Департаментом юстиции Кызылординской области 5 января 2020 года № 7188
title:
  rus: О бюджете сельского округа Майлыбас на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Майлыбас ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-26
approved_by:
- '161004000002'
version_date:
  kaz: 2019-12-26
  rus: 2019-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/138643/kaz/26.12.2019
  rus: https://zan.gov.kz/client/#!/doc/138643/rus/26.12.2019
