act_code: '122782'
requisite: Решение Шиелийского районного маслихата Кызылординской области от 31 мая 2018 года № 24/4. Зарегистрировано Департаментом юстиции Кызылординской области 18 июня 2018 года № 6324
title:
  rus: Об утверждении Регламента собрания местного сообщества сельского округа Акмая Шиелийского района
  kaz: Шиелі  ауданы Ақмая ауылдық округінің жергілікті қоғамдастық жиналысының Регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-05-31
approved_by:
- '161008000002'
version_date:
  kaz: 2023-11-14
  rus: 2023-11-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/122782/kaz/14.11.2023
  rus: https://zan.gov.kz/client/#!/doc/122782/rus/14.11.2023
caused_by:
  code: '188795'
  requisite: Решение Шиелийского районного маслихата Кызылординской области от 14 ноября 2023 года № 7/13
  title:
    rus: О внесении изменений в решение Шиелийского районного маслихата от 31 мая 2018 года №24/4 «Об утверждении Регламента собрания местного сообщества сельского округа Акмая Шиелийского района»
    kaz: «Шиелі ауданы Ақмая ауылдық округінің жергілікті қоғамдастық жиналысының Регламентін бекіту туралы» Шиелі аудандық мәслихатының 2018 жылғы 31 мамырдағы №24/4 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/188795/rus
