act_code: '99336'
requisite: Решение акима сельского округа Аккыр Жалагашского района Кызылординской области от 26 января 2016 года N 2. Зарегистрировано Департаментом юстиции Кызылординской области 11 февраля 2016 года N 5345
title:
  rus: О переименовании улицы
  kaz: Көшені қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-01-26
approved_by:
- '161006003001'
version_date:
  kaz: 2016-01-26
  rus: 2016-01-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/99336/kaz/26.01.2016
  rus: https://zan.gov.kz/client/#!/doc/99336/rus/26.01.2016
