act_code: '57165'
requisite: Решение от 23.12.2010 №37/12, Маслихат г. Кызылорды
title:
  rus: Қызылорда қаласын абаттандыру, аумақты санитарлық күтіп ұстау және тазалықты қамтамасыз ету Қағидасын бекіту
  kaz: Қызылорда қаласын абаттандыру, аумақты санитарлық күтіп ұстау және тазалықты қамтамасыз ету Қағидасын бекіту
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-23
approved_by:
- '161002000002'
version_date:
  kaz: 2010-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/57165/kaz/23.12.2010
