act_code: '178237'
requisite: Решение Жанакорганского районного маслихата Кызылординской области от 29 декабря 2022 года № 339
title:
  rus: О бюджете сельского округа Кейден на 2023-2025 годы
  kaz: Кейден ауылдық округінің 2023-2025 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-29
approved_by:
- '161009000002'
version_date:
  kaz: 2023-08-31
  rus: 2023-08-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/178237/kaz/31.08.2023
  rus: https://zan.gov.kz/client/#!/doc/178237/rus/31.08.2023
caused_by:
  code: '185896'
  requisite: Решение Жанакорганского районного маслихата Кызылординской области от 31 августа 2023 года № 74
  title:
    rus: О внесении изменений в решение маслихата Жанакорганского района от 29 декабря 2022 года №339 «О бюджете сельского округа Кейден на 2023-2025 годы»
    kaz: «Кейден ауылдық округінің «2023-2025 жылдарға арналған бюджеті туралы» Жаңақорған ауданы мәслихатының 2022 жылғы 29 желтоқсандағы №339 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/185896/rus
