act_code: '176320'
requisite: Решение Казалинского районного маслихата Кызылординской области от 28 декабря 2022 года № 342
title:
  rus: О бюджете сельского округа Арыкбалык на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Арықбалық ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-28
approved_by:
- '161004000002'
version_date:
  kaz: 2023-09-05
  rus: 2023-09-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/176320/kaz/05.09.2023
  rus: https://zan.gov.kz/client/#!/doc/176320/rus/05.09.2023
caused_by:
  code: '186211'
  requisite: Решение Казалинского районного маслихата Кызылординской области от 5 сентября 2023 года № 68
  title:
    rus: О внесении изменений в решение от 23 декабря 2022 года №356 Казалинского районного маслихата Кызылординской области «О бюджете сельского округа Арыкбалык на 2023-2025 годы»
    kaz: Қызылорда облысының Қазалы аудандық мәслихатының «2023-2025 жылдарға арналған Арықбалық ауылдық округінің бюджеті туралы» 2022 жылғы 23 желтоқсандағы №356 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/186211/rus
