act_code: '61806'
requisite: Решение маслихата Сырдарьинского района Кызылординской области от 15 ноября 2011 года № 358. Зарегистрировано Департаментом юстиции Кызылординской области 8 декабря 2011 года за № 10-8-158. Утратило силу решением маслихата Сырдарьинского района Кызылординской области от 21 ноября 2012 года № 86
title:
  rus: Об утверждении Правилы о порядке и размере оказания жилищной помощи малообеспеченным семьям (гражданам)
  kaz: Аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшері мен тәртібі жөніндегі Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-11-15
approved_by:
- '161007000002'
version_date:
  kaz: 2011-11-15
  rus: 2011-11-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/61806/kaz/15.11.2011
  rus: https://zan.gov.kz/client/#!/doc/61806/rus/15.11.2011
