act_code: '204787'
requisite: Решение Казалинского районного маслихата Кызылординской области от 23 декабря 2024 года № 347
title:
  rus: О районном бюджете на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-23
approved_by:
- '161004000002'
version_date:
  kaz: 2025-02-26
  rus: 2025-02-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/204787/kaz/26.02.2025
  rus: https://zan.gov.kz/client/#!/doc/204787/rus/26.02.2025
caused_by:
  code: '207420'
  requisite: Решение Казалинского районного маслихата Кызылординской области от 26 февраля 2025 года № 377
  title:
    rus: О внесении изменений и дополнений в решение Казалинского районного маслихата Кызылординской области от 23 декабря 2024 года № 347 «О районном бюджете на 2025-2027 годы»
    kaz: Қызылорда облысы Қазалы аудандық мәслихатының 2024 жылғы 23 желтоқсандағы № 347 «2025-2027 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/207420/rus
