act_code: '117448'
requisite: Решение Казалинского районного маслихата Кызылординской области от 25 декабря 2017 года № 164. Зарегистрировано Департаментом юстиции Кызылординской области 27 декабря 2017 года № 6095
title:
  rus: О бюджетах города районного значения, поселка, сельских округов на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған аудандық маңызы бар қала, кент, ауылдық округтер бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-25
approved_by:
- '161004000002'
version_date:
  kaz: 2018-04-13
  rus: 2018-04-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/117448/kaz/13.04.2018
  rus: https://zan.gov.kz/client/#!/doc/117448/rus/13.04.2018
caused_by:
  code: '121400'
  requisite: Решение Казалинского районного маслихата Кызылординской области от 13 апреля 2018 года № 193. Зарегистрировано Департаментом юстиции Кызылординской области 19 апреля 2018 года № 6263
  title:
    rus: О внесении изменений в решение Казалинского районного маслихата от 25 декабря 2017 года №164 «О бюджетах города районного значения, поселка, сельских округов на 2018-2020 годы»
    kaz: «2018-2020 жылдарға арналған аудандық маңызы бар қала, кент, ауылдық округтер бюджеттері туралы» Қазалы аудандық мәслихатының 2017 жылғы 25 желтоқсандағы №164 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/121400/rus
