act_code: '42579'
requisite: Решение от 22.10.2008 №107, Маслихат Сырдарьинского района
title:
  rus: Сырдария ауданы, Төреңөзек кентінің жерлерін аймақтарға бөлу схемасын және салықтың базалық ставкасының түзету коэффициенттерін бекіту туралы
  kaz: Сырдария ауданы, Төреңөзек кентінің жерлерін аймақтарға бөлу схемасын және салықтың базалық ставкасының түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-10-22
approved_by:
- '161007000002'
version_date:
  kaz: 2008-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/42579/kaz/22.10.2008
