act_code: '57166'
requisite: Решение Кызылординского городского маслихата от 23 декабря 2010 года № 37/11. Зарегистрировано Департаментом юстиции Кызылординской области 28 января 2011 года за № 10-1-164. Утратило силу - решением Кызылординского городского маслихата от 14 июня 2011 года № 43/6
title:
  rus: Об утверждении Правил застройки на территории города Кызылорды
  kaz: Қызылорда қаласы аумағында құрылыс салу Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-23
approved_by:
- '161002000002'
version_date:
  kaz: 2010-12-23
  rus: 2010-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/57166/kaz/23.12.2010
  rus: https://zan.gov.kz/client/#!/doc/57166/rus/23.12.2010
