act_code: '163539'
requisite: Решение Аральского районного маслихата Кызылординской области от 29 декабря 2021 года № 206
title:
  rus: О бюджете сельского округа Куланды на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Құланды ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-29
approved_by:
- '161003000002'
version_date:
  kaz: 2021-12-29
  rus: 2021-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/163539/kaz/29.12.2021
  rus: https://zan.gov.kz/client/#!/doc/163539/rus/29.12.2021
