act_code: '151436'
requisite: Решение Жанакорганского районного маслихата Кызылординской области от 24 декабря 2020 года № 576. Зарегистрировано Департаментом юстиции Кызылординской области 31 декабря 2020 года № 8024
title:
  rus: О районном бюджете на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-24
approved_by:
- '161009000002'
version_date:
  kaz: 2020-12-24
  rus: 2020-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/151436/kaz/24.12.2020
  rus: https://zan.gov.kz/client/#!/doc/151436/rus/24.12.2020
