act_code: '214029'
requisite: Решение акима Актоганского сельского округа Шиелийского района Кызылординской области от 08 сентября 2025 года № 02-2/10
title:
  rus: Кызылординская область, Шиелийский район, сельский округ Актоган о присвоении наименований безымянным улицам села Досбол датка
  kaz: Қызылорда облысы, Шиелі ауданы, Ақтоған ауылдық округі, Досбол датқа ауылындағы атауы жоқ көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-08
approved_by:
- '161008006002'
version_date:
  kaz: 2025-09-08
  rus: 2025-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/214029/kaz/08.09.2025
  rus: https://zan.gov.kz/client/#!/doc/214029/rus/08.09.2025
