act_code: '139341'
requisite: Решение акима сельского округа Басыкара Казалинского района Кызылординской области от 31 января 2020 года № 5. Зарегистрировано Департаментом юстиции Кызылординской области 3 февраля 2020 года № 7230
title:
  rus: О переименовании улицы
  kaz: Көшені қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-31
approved_by:
- '161004007002'
version_date:
  kaz: 2020-01-31
  rus: 2020-01-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/139341/kaz/31.01.2020
  rus: https://zan.gov.kz/client/#!/doc/139341/rus/31.01.2020
