act_code: '123751'
requisite: Решение Кармакшинского районного маслихата Кызылординской области от 10 июля 2018 года № 178. Зарегистрировано Департаментом юстиции Кызылординской области 24 июля 2018 года № 6390. Утратило силу решением Кармакшинского районного маслихата Кызылординской области от 15 июня 2022 года № 195
title:
  rus: О ставках земельного налога
  kaz: Жер салығынының мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-07-10
approved_by:
- '161005000002'
version_date:
  kaz: 2018-07-10
  rus: 2018-07-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/123751/kaz/10.07.2018
  rus: https://zan.gov.kz/client/#!/doc/123751/rus/10.07.2018
