act_code: '123383'
requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 15 июня 2018 года № 195. Зарегистрировано Департаментом юстиции Кызылординской области 4 июля 2018 года № 6369
title:
  rus: Об утверждении Регламента собрания местного сообщества сельского округа Акжарма Сырдарьинского района
  kaz: Сырдария ауданы Ақжарма ауылдық округінің жергілікті қоғамдастық жиналысының Регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-06-15
approved_by:
- '161007000002'
version_date:
  kaz: 2021-10-27
  rus: 2021-10-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/123383/kaz/27.10.2021
  rus: https://zan.gov.kz/client/#!/doc/123383/rus/27.10.2021
caused_by:
  code: '159930'
  requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 27 октября 2021 года № 72
  title:
    rus: Решение Сырдарьинского районного маслихата от 27 октября 2021 года №72 «О внесении изменений в решение Сырдарьинского районного маслихата от 15 июня 2018 года №195 «Об утверждении Регламента собрания местного сообщества сельского округа Акжарма Сырдарьинского района»
    kaz: Сырдария ауданы Ақжарма ауылдық округінің жергiлiктi қоғамдастық жиналысының Регламентiн бекiту туралы» Сырдария аудандық мәслихатының 2018 жылғы 15 маусымдағы №195 шешіміне өзгерістер енгізу туралы» Сырдария аудандық мәслихатының 2021 жылғы 27 қазандағы №72 шешімі
  link: https://zan.gov.kz/client/#!/doc/159930/rus
