act_code: '42258'
requisite: Шиелі кенті әкімінің 2008 жылғы 24 қыркүйектегі N 204 шешімі. Шиелі аудандық Әділет басқармасының 2008 жылы 05 қарашада N 10-9-65 тіркелді.
title:
  rus: Шиелі кенті "Көкшоқы" мөлтек ауданындағы атау берілмеген көшеге Ыбырайхан Нәлібайұлының есімін беру туралы
  kaz: Шиелі кенті "Көкшоқы" мөлтек ауданындағы атау берілмеген көшеге Ыбырайхан Нәлібайұлының есімін беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-09-24
approved_by:
- '161008023001'
version_date:
  kaz: 2010-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/42258/kaz/28.12.2010
caused_by:
  code: '57086'
  requisite: Решение от 28.12.2010 №1102, Аким поселка Шиели
  title:
    rus: Шиелі кенті әкімінің 2008 жылғы 24 қыркүйектегі "Шиелі кенті "Көкшоқы" мөлтек ауданындағы атауы берілмеген көшеге Ыбырайхан Нәлібайұлының есімін беру туралы" N 204 шешіміне өзгерістер енгізу туралы
    kaz: Шиелі кенті әкімінің 2008 жылғы 24 қыркүйектегі "Шиелі кенті "Көкшоқы" мөлтек ауданындағы атауы берілмеген көшеге Ыбырайхан Нәлібайұлының есімін беру туралы" N 204 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/57086/rus
