act_code: '53101'
requisite: Решение от 11.05.2010 №587, Аким поселка Тасбогет
title:
  rus: Тасбөгет кенті көшелеріне жаңадан атау беру туралы
  kaz: Тасбөгет кенті көшелеріне жаңадан атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-05-11
approved_by:
- '161002007001'
version_date:
  kaz: 2010-05-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/53101/kaz/11.05.2010
