act_code: '540'
requisite: Решение акима Кызылординской области от 6 июня 1997 года № 504. Зарегистрировано Управлением юстиции Кызылординской области 06 июня 1997 года № 12. Утратило силу постановлением акимата Кызылординской области от 20 декабря 2004 года № 247
title:
  rus: О реализации постановления Правительства РК "Об упорядочении применения норм потребления тепла, горячей и холодной воды" от 29 мая 1997 года № 889
  kaz: Қазақстан Республикасы Үкiметiнiң 1997 жылғы 29 мамырдағы № 889 «Жылуды, ыстық және суық суды тұтыну нормаларын қолдануды ретке келтiру туралы» қаулысын жүзеге асыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1997-06-05
approved_by:
- '161000000003'
version_date:
  kaz: 1997-06-05
  rus: 1997-06-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/540/kaz/05.06.1997
  rus: https://zan.gov.kz/client/#!/doc/540/rus/05.06.1997
