act_code: '154675'
requisite: Решение акима сельского округа Бирлик Казалинского района Кызылординской области от 13 апреля 2021 года № 11. Зарегистрировано Департаментом юстиции Кызылординской области 14 апреля 2021 года № 8295
title:
  rus: О переименовании улицы
  kaz: Көшені қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-04-13
approved_by:
- '161004009002'
version_date:
  kaz: 2021-04-13
  rus: 2021-04-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/154675/kaz/13.04.2021
  rus: https://zan.gov.kz/client/#!/doc/154675/rus/13.04.2021
