act_code: '142578'
requisite: Решение Кармакшинского районного маслихата Кызылординской области от 30 апреля 2020 года № 323. Зарегистрировано Департаментом юстиции Кызылординской области 4 мая 2020 года № 7409. Утратило силу решением Кармакшинского районного маслихата Кызылординской области от 12 декабря 2024 года № 224
title:
  rus: Об определении размера и порядка оказания жилищной помощи
  kaz: Тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-04-30
approved_by:
- '161005000002'
version_date:
  kaz: 2020-12-28
  rus: 2020-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/142578/kaz/28.12.2020
  rus: https://zan.gov.kz/client/#!/doc/142578/rus/28.12.2020
caused_by:
  code: '152046'
  requisite: Решение Кармакшинского районного маслихата Кызылординской области от 28 декабря 2020 года № 421. Зарегистрировано Департаментом юстиции Кызылординской области 6 января 2021 года № 8098. Утратило силу решением Кармакшинского районного маслихата Кызылординской области от 12 декабря 2024 года № 224
  title:
    rus: О внесении изменений в решение Кармакшинского районного маслихата от 30 апреля 2020 года № 323 «Об определении размера и порядка оказания жилищной помощи»
    kaz: «Тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы» Қармақшы аудандық мәслихатының 2020 жылғы 30 сәуірдегі № 323 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/152046/rus
