act_code: '152248'
requisite: Решение Жанакорганского районного маслихата Кызылординской области от 30 декабря 2020 года № 609. Зарегистрировано Департаментом юстиции Кызылординской области 8 января 2021 года № 8123
title:
  rus: О бюджете сельского округа Суттикудык на 2021-2023 годы
  kaz: Сүттіқұдық ауылдық округінің 2021-2023 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-30
approved_by:
- '161009000002'
version_date:
  kaz: 2021-03-25
  rus: 2021-03-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/152248/kaz/25.03.2021
  rus: https://zan.gov.kz/client/#!/doc/152248/rus/25.03.2021
caused_by:
  code: '154385'
  requisite: Решение Жанакорганского районного маслихата Кызылординской области от 25 марта 2021 года № 33. Зарегистрировано Департаментом юстиции Кызылординской области 2 апреля 2021 года № 8268
  title:
    rus: О внесении изменений в решение Жанакорганского районного маслихата №609 от 30 декабря 2020 года «О бюджете сельского округа Суттикудық на 2021-2023 годы»
    kaz: «Сүттіқұдық ауылдық округінің 2021-2023 жылдарға арналған бюджеті туралы» Жаңақорған аудандық мәслихатының 2020 жылғы 30 желтоқсандағы №609 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/154385/rus
