act_code: '46443'
requisite: Решение от 30.04.2009 №100, Маслихат Аральского района
title:
  rus: Ауылдық елді мекендерде жұмыс істейтін және тұратын денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарының тізбесі мен оларға әлеуметтік қызмет көрсету қағидасына келісім беру туралы
  kaz: Ауылдық елді мекендерде жұмыс істейтін және тұратын денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарының тізбесі мен оларға әлеуметтік қызмет көрсету қағидасына келісім беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-30
approved_by:
- '161003000002'
version_date:
  kaz: 2009-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/46443/kaz/23.12.2009
caused_by:
  code: '50371'
  requisite: Решение от 23.12.2009 №135, Маслихат Аральского района
  title:
    rus: Аудандық мәслихаттың 2009 жылғы 30 сәуіріндегі кезектен тыс он бесінші сессиясының N 100 шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Аудандық мәслихаттың 2009 жылғы 30 сәуіріндегі кезектен тыс он бесінші сессиясының N 100 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/50371/rus
