act_code: '88958'
requisite: Решение Кызылординского областного маслихата от 18 марта 2015 года N 262. Зарегистрировано Департаментом юстиции Кызылординской области 21 апреля 2015 года N 4961. Утратило силу решением Кызылординского областного маслихата от 12 октября 2022 года № 143
title:
  rus: Об утверждении правил содержания и выгула собак и кошек, отлова и уничтожения бродячих собак и кошек в населенных пунктах Кызылординской области
  kaz: Қызылорда облысының елді мекендерінде иттер мен мысықтарды асырау және серуендету, қаңғыбас иттер мен мысықтарды аулау және жою қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-03-18
approved_by:
- '161000000002'
version_date:
  kaz: 2015-03-18
  rus: 2015-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/88958/kaz/18.03.2015
  rus: https://zan.gov.kz/client/#!/doc/88958/rus/18.03.2015
