act_code: '54669'
requisite: Решение от 14.09.2010 №5, Акимат аульного округа Тан
title:
  rus: Таң ауылдық округінің көшелерін қайта атау және атау беру туралы.
  kaz: Таң ауылдық округінің көшелерін қайта атау және атау беру туралы.
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-14
approved_by:
- '161006011001'
version_date:
  kaz: 2010-09-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/54669/kaz/14.09.2010
