act_code: '43021'
requisite: Қызылорда облыстық мәслихатының 2008 жылғы 11 желтоқсандағы N 114 шешімі. Қызылорда облысының Әділет департаментінде 2008 жылғы 24 желтоқсанда N 4213 тіркелді. Қолданылу мерзімінің аяқталуына байланысты күші жойылды - (Қызылорда облыстық мәслихатының 2010 жылғы 01 сәуірдегі N 1-214м хатымен)
title:
  rus: 2009 жылға арналған облыстық бюджет туралы
  kaz: 2009 жылға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-11
approved_by:
- '161000000002'
version_date:
  kaz: 2009-04-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/43021/kaz/21.04.2009
caused_by:
  code: '45468'
  requisite: Қызылорда облыстық мәслихатының 2009 жылғы 21 сәуірдегі N 156 шешімі. Қызылорда облыстық Әділет департаментінде 2009 жылы 24 сәуірде N 4227 тіркелді. Қолданылу мерзімінің аяқталуына байланысты күші жойылды - (Қызылорда облыстық мәслихатының 2010 жылғы 01 сәуірдегі N 1-214м хатымен)
  title:
    rus: '"2009 жылға арналған облыстық бюджет туралы" Қызылорда облыстық мәслихатының 2008 жылғы 11 желтоқсандағы N 114 шешіміне өзгерістер мен толықтырулар енгізу туралы'
    kaz: '"2009 жылға арналған облыстық бюджет туралы" Қызылорда облыстық мәслихатының 2008 жылғы 11 желтоқсандағы N 114 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/45468/rus
