act_code: '43021'
requisite: Қызылорда облыстық мәслихатының 2008 жылғы 11 желтоқсандағы N 114 шешімі. Қызылорда облысының Әділет департаментінде 2008 жылғы 24 желтоқсанда N 4213 тіркелді. Қолданылу мерзімінің аяқталуына байланысты күші жойылды - (Қызылорда облыстық мәслихатының 2010 жылғы 01 сәуірдегі N 1-214м хатымен)
title:
  rus: 2009 жылға арналған облыстық бюджет туралы
  kaz: 2009 жылға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-11
approved_by:
- '161000000002'
version_date:
  kaz: 2009-01-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/43021/kaz/29.01.2009
caused_by:
  code: '44080'
  requisite: Решение от 29.01.2009 №134, Маслихат Кызылординской области
  title:
    rus: '"2009 жылға арналған облыстық бюджет туралы" Қызылорда облыстық мәслихатының 2008 жылғы 11 желтоқсандағы кезектен тыс ХІ сессиясының N 114 шешіміне өзгерістер мен толықтырулар енгізу туралы'
    kaz: '"2009 жылға арналған облыстық бюджет туралы" Қызылорда облыстық мәслихатының 2008 жылғы 11 желтоқсандағы кезектен тыс ХІ сессиясының N 114 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/44080/rus
