act_code: '163658'
requisite: Решение Шиелийского районного маслихата Кызылординской области от 30 декабря 2021 года № 18/12
title:
  rus: О бюджете сельского округа Сулутобе на 2022-2024 годы
  kaz: Сұлутөбе ауылдық округінің 2022-2024 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '161008000002'
version_date:
  kaz: 2022-04-08
  rus: 2022-04-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/163658/kaz/08.04.2022
  rus: https://zan.gov.kz/client/#!/doc/163658/rus/08.04.2022
caused_by:
  code: '166502'
  requisite: Решение Шиелийского районного маслихата Кызылординской области от 8 апреля 2022 года № 21/12
  title:
    rus: О внесении изменений в решение Шиелийского районного маслихата «О бюджете сельского округа Сулутобе на 2022-2024 годы» от 30 декабря 2021 года № 18/12
    kaz: Шиелі аудандық мәслихатының 2021 жылғы 30 желтоқсандағы «Сұлутөбе ауылдық округінің 2022-2024 жылдарға арналған бюджеті туралы» № 18/12 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/166502/rus
