act_code: '69116'
requisite: Решение Шиелийского районного маслихата Кызылординской области от 15 ноября 2012 года N 9/4. Зарегистрировано Департаментом юстиции Кызылординской области 12 декабря 2012 года за N 4365. Утратило силу решением Шиелийского районного маслихата Кызылординской области от 20 июня 2013 года N 18/4
title:
  rus: Об оказания единовременной материальной помощи
  kaz: Біржолғы материалдық көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-11-15
approved_by:
- '161008000002'
version_date:
  kaz: 2012-11-15
  rus: 2012-11-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/69116/kaz/15.11.2012
  rus: https://zan.gov.kz/client/#!/doc/69116/rus/15.11.2012
