act_code: '56768'
requisite: Қызылорда облысы Жаңақорған аудандық мәслихатының 2010 жылғы 24 желтоқсандағы N 277 шешімі. Қызылорда облысының Әділет департаменті Жаңақорған аудандық Әділет басқармасында 2011 жылы 12 қаңтарда N 10-7-123 тіркелді. Шешімнің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды (Қызылорда облысы Жаңақорған аудандық мәслихатының 2012 жылғы 05 маусымдағы N 119 хатымен)
title:
  rus: '"2011-2013 жылдарға арналған аудандық бюджет туралы"'
  kaz: '"2011-2013 жылдарға арналған аудандық бюджет туралы"'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '161009000002'
version_date:
  kaz: 2011-01-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/56768/kaz/28.01.2011
caused_by:
  code: '57350'
  requisite: Решение Жанакорганского районного маслихата Кызылординской области от 28 января 2011 года № 285. Зарегистрировано Управлением юстиции Жанакорганского района Кызылординской области 21 февраля 2011 года за № 10-7-133. Утратило силу в связи с истечением срока применения - (письмо Жанакорганского районного маслихата Кызылординской области от 05 июня 2012 года N 119)
  title:
    rus: О внесение изменений и в решение Жанакорганского районного маслихата от 24 декабря 2010 года N 277 "О районном бюджете на 2011-2013 годы
    kaz: '"2011-2013 жылдарға арналған аудандық бюджет туралы" Жаңақорған аудандық мәслихатының 2010 жылғы 24 желтоқсандағы N 277 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/57350/rus
