act_code: '55525'
requisite: Решение от 03.11.2010 №105, Акимат аульного округа Кердели
title:
  rus: Керделі ауылдық округі, Н. Бекежанов елді мекенінің батыс беткейіндегі атауы жоқ көшеге "Бекхожаев Әнтай Бекхожаұлы" есімін беру туралы
  kaz: Керделі ауылдық округі, Н. Бекежанов елді мекенінің батыс беткейіндегі атауы жоқ көшеге "Бекхожаев Әнтай Бекхожаұлы" есімін беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-03
approved_by:
- '161008020001'
version_date:
  kaz: 2010-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/55525/kaz/03.11.2010
