act_code: '95367'
requisite: Решение от 09.11.2015 №418, Акимат г. Кызылорды. Зарегистрировано Департаментом юстиции Кызылординской области 13 ноября 2015 года N 5219. Утратило силу решением акима города Кызылорда Кызылординской области от 30.03.2016 № 452
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-11-09
approved_by:
- '161002000001'
version_date:
  kaz: 2015-11-09
  rus: 2015-11-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/95367/kaz/09.11.2015
  rus: https://zan.gov.kz/client/#!/doc/95367/rus/09.11.2015
