act_code: '25720'
requisite: Решение от 23.06.2005 №185, Маслихат Кызылординской области
title:
  rus: Қызылорда облысының 2005-2007 жылдарға арналған өңірлік экологиялық бағдарламасын бекіту туралы
  kaz: Қызылорда облысының 2005-2007 жылдарға арналған өңірлік экологиялық бағдарламасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-06-23
approved_by:
- '161000000002'
version_date:
  kaz: 2005-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/25720/kaz/23.06.2005
