act_code: '151008'
requisite: Решение Казалинского районного маслихата Кызылординской области от 25 декабря 2020 года № 544. Зарегистрировано Департаментом юстиции Кызылординской области 29 декабря 2020 года № 7974
title:
  rus: О бюджете города Казалинск на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Қазалы қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-25
approved_by:
- '161004000002'
version_date:
  kaz: 2021-11-11
  rus: 2021-11-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/151008/kaz/11.11.2021
  rus: https://zan.gov.kz/client/#!/doc/151008/rus/11.11.2021
caused_by:
  code: '161126'
  requisite: Решение Казалинского районного маслихата Кызылординской области от 11 ноября 2021 года № 128
  title:
    rus: О внесении изменений и дополнение в решение Казалинского районного маслихата Кызылординской области «О бюджете города Казалинск на 2021-2023 годы» от 25 декабря 2020 года № 544
    kaz: Қызылорда облысы Қазалы аудандық мәслихатының 2020 жылғы 25 желтоқсандағы №544 «2021-2023 жылдарға арналған Қазалы қаласының бюджеті туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/161126/rus
