act_code: '142457'
requisite: Решение акима сельского округа Бесарык Жанакорганского района Кызылординской области от 29 апреля 2020 года № 180. Зарегистрировано Департаментом юстиции Кызылординской области 30 апреля 2020 года № 7406
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-04-29
approved_by:
- '161009013002'
version_date:
  kaz: 2020-04-29
  rus: 2020-04-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/142457/kaz/29.04.2020
  rus: https://zan.gov.kz/client/#!/doc/142457/rus/29.04.2020
