act_code: '85780'
requisite: Решение Шиелийского районного маслихата Кызылординской области 24 декабря 2014 года № 36/2. Зарегистрировано Департаментом юстиции Кызылординской области 09 января 2015 года № 4839. Прекращено действие в связи с истечением срока
title:
  rus: О районном бюджете на 2015-2017 годы
  kaz: 2015-2017 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '161008000002'
version_date:
  kaz: 2015-10-01
  rus: 2015-10-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/85780/kaz/01.10.2015
  rus: https://zan.gov.kz/client/#!/doc/85780/rus/01.10.2015
caused_by:
  code: '94248'
  requisite: Решение Шиелийского районного маслихата Кызылординской области от 01 октября 2015 года № 44/3. Зарегистрировано Департаментом юстиции Кызылординской области 07 октября 2015 года № 5165. Прекращено действие в связи с истечением срока
  title:
    rus: О внесении изменений в решение районного маслихата от 24 декабря 2014 года № 36/2 "О районном бюджете на 2015-2017 годы"
    kaz: '"2015-2017 жылдарға арналған аудандық бюджет туралы" аудандық мәслихаттың 2014 жылғы 24 желтоқсандақы № 36/2 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/94248/rus
