act_code: '57714'
requisite: Решение Казалиснкого районного маслихата Кызылординской области от 19 февраля 2011 года № 267. Зарегистрировано Управление юстиции Казалинского района Кызылординской области 16 марта 2011 года за № 10-4-143. Утратило силу в связи с истечением срока применения - письмо Казалинского районного маслихата Кызылординской области от 11 декабря 2012 года № 356
title:
  rus: Об установлении стоимости разовых талонов, дающих право лицам, заниматься предпринимательской деятельностью, услугами по продаже товаров на рынках, в торговых рядах, в обозначенных местах
  kaz: Базарларда, сауда қатарлары мен белгіленген орындарда тауар сатуға және түрлі кәсіпкерлік қызметпен айналысатын тұлғаларға құқық беретін бір жолғы талондардың құнын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-02-19
approved_by:
- '161004000002'
version_date:
  kaz: 2011-02-19
  rus: 2011-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/57714/kaz/19.02.2011
  rus: https://zan.gov.kz/client/#!/doc/57714/rus/19.02.2011
