act_code: '214008'
requisite: Решение акима поселка Шиели Шиелийского района Кызылординской области от 08 сентября 2025 года № 1820
title:
  rus: О Присвоении наименовании безымянным улицам поселка Шиели
  kaz: Шиелі кентінің атауы жоқ көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-08
approved_by:
- '161008023001'
version_date:
  kaz: 2025-09-08
  rus: 2025-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/214008/kaz/08.09.2025
  rus: https://zan.gov.kz/client/#!/doc/214008/rus/08.09.2025
