act_code: '51769'
requisite: Решение от 05.03.2010 №147, Маслихат Аральского района
title:
  rus: Аудандағы аз қамтамасыз етілген азаматтарға тұрғын үй ұстауға және коммуналдық қызметтің ақысын төлеуге арналған тұрғын үй көмегін көрсетудің мөлшері мен тәртібінің қағидасын бекіту туралы
  kaz: Аудандағы аз қамтамасыз етілген азаматтарға тұрғын үй ұстауға және коммуналдық қызметтің ақысын төлеуге арналған тұрғын үй көмегін көрсетудің мөлшері мен тәртібінің қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-05
approved_by:
- '161003000002'
version_date:
  kaz: 2010-10-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/51769/kaz/27.10.2010
caused_by:
  code: '55575'
  requisite: Решение от 27.10.2010 №188, Маслихат Аральского района
  title:
    rus: Аудандық мәслихаттың 2010 жылғы 05 наурыздағы кезекті жиырма үшінші сессиясында бекітілген "Аудандағы аз қамтамасыз етілген азаматтарға тұрғын үй ұстау және коммуналдық қызметтің ақысын  төлеуге арналған тұрғын үй көмегін көрсетудің мөлшері мен тәртібінің қағидасын бекіту туралы" N 147 шешіміне толықтыру енгізу туралы
    kaz: Аудандық мәслихаттың 2010 жылғы 05 наурыздағы кезекті жиырма үшінші сессиясында бекітілген "Аудандағы аз қамтамасыз етілген азаматтарға тұрғын үй ұстау және коммуналдық қызметтің ақысын  төлеуге арналған тұрғын үй көмегін көрсетудің мөлшері мен тәртібінің қағидасын бекіту туралы" N 147 шешіміне толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/55575/rus
