act_code: '52655'
requisite: Решение от 21.04.2010 №02, Акимат аульного округа Макпалкол
title:
  rus: Мақпалкөл ауылдық округіндегі "Ленин" көшесінің атауын өзгерту туралы
  kaz: Мақпалкөл ауылдық округіндегі "Ленин" көшесінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-21
approved_by:
- '161006007001'
version_date:
  kaz: 2010-04-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/52655/kaz/21.04.2010
