act_code: '102364'
requisite: Решение акима сельского округа Алга Казалинского района Кызылординской области от 13 мая 2016 года № 7. Зарегистрировано Департаментом юстиции Кызылординской области 17 мая 2016 года № 5511
title:
  rus: О переименовании улицы
  kaz: Көшені қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-05-13
approved_by:
- '161004003001'
version_date:
  kaz: 2016-05-13
  rus: 2016-05-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/102364/kaz/13.05.2016
  rus: https://zan.gov.kz/client/#!/doc/102364/rus/13.05.2016
