act_code: '154569'
requisite: Решение акима сельского округа Косуйенки Жанакорганского района Кызылординской области от 7 апреля 2021 года № 40. Зарегистрировано Департаментом юстиции Кызылординской области 8 апреля 2021 года № 8292
title:
  rus: О переименовании улицы
  kaz: Көшені қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-04-07
approved_by:
- '161009018002'
version_date:
  kaz: 2021-04-07
  rus: 2021-04-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/154569/kaz/07.04.2021
  rus: https://zan.gov.kz/client/#!/doc/154569/rus/07.04.2021
