act_code: '144343'
requisite: Решение Кызылординского городского маслихата от 24 июня 2020 года № 350-62/8. Зарегистрировано Департаментом юстиции Кызылординской области 26 июня 2020 года № 7548
title:
  rus: Об утверждении планов по управлению пастбищами и их использованию по сельским округам Аксуат, Кызылжарма, Акжарма, Талсуат, Кызылозек, Косшынырау, Карауылтобе и поселкам Тасбугет, Белкуль города Кызылорды на 2020-2021 годы
  kaz: Қызылорда қаласы Ақсуат, Қызылжарма, Ақжарма, Талсуат, Қызылөзек, Қосшыңырау, Қарауылтөбе ауылдық округтері мен Тасбөгет, Белкөл кенттері бойынша 2020-2021 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-24
approved_by:
- '161002000002'
version_date:
  kaz: 2020-06-24
  rus: 2020-06-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/144343/kaz/24.06.2020
  rus: https://zan.gov.kz/client/#!/doc/144343/rus/24.06.2020
