act_code: '148092'
requisite: Решение Кызылординского областного маслихата от 21 октября 2020 года № 476. Зарегистрировано Департаментом юстиции Кызылординской области 2 ноября 2020 года № 7769
title:
  rus: О предоставлении бесплатного или льготного проезда гражданам за пределы населенного пункта постоянного проживания для получения высокотехнологичных медицинских услуг в рамках гарантированного объема бесплатной медицинской помощи и (или) медицинской помощи в системе обязательного социального медицинского страхования за счет бюджетных средств
  kaz: Тегін медициналық көмектің кепілдік берілген көлемі шеңберінде жоғары технологиялық медициналық көрсетілетін қызметтерді және (немесе) міндетті әлеуметтік медициналық сақтандыру жүйесінде медициналық көмекті алу үшін азаматтарға тұрақты тұратын елді мекеннен тысқары жерлерге бюджет қаражаты есебінен тегін немесе жеңілдікпен жол жүруді ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-10-21
approved_by:
- '161000000002'
version_date:
  kaz: 2020-10-21
  rus: 2020-10-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/148092/kaz/21.10.2020
  rus: https://zan.gov.kz/client/#!/doc/148092/rus/21.10.2020
