act_code: '62585'
requisite: Решение акима Казалинского района Кызылординской области от 08 декабря 2011 года № 2. Зарегистрировано Департаментом юстиции Кызылординской области 9 января 2012 года № 10-4-166. Утратило силу - решением акима Казалинского района Кызылординской области от 12 марта 2012 года № 4
title:
  rus: О проведении мероприятий по приписке граждан мужского пола на воинской учет, которым в год приписке исполняется семнадцать лет
  kaz: Тіркелетін жылы он жеті жасқа толатын еркек жынысты азаматтарды әскери есепке тіркеуге алу жұмыстарын жүргізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-08
approved_by:
- '161004000001'
version_date:
  kaz: 2011-12-08
  rus: 2011-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/62585/kaz/08.12.2011
  rus: https://zan.gov.kz/client/#!/doc/62585/rus/08.12.2011
