act_code: '100906'
requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 29 февраля 2016 года № 383. Зарегистрировано Департаментом юстиции Кызылординской области 01 апреля 2016 года № 5430. Утратило силу решением Сырдарьинского районного маслихата Кызылординской области от 28 февраля 2018 года № 174
title:
  rus: О ставках земельного налога
  kaz: Жер салығының мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-02-29
approved_by:
- '161007000002'
version_date:
  kaz: 2016-02-29
  rus: 2016-02-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/100906/kaz/29.02.2016
  rus: https://zan.gov.kz/client/#!/doc/100906/rus/29.02.2016
