act_code: '42176'
requisite: Решение от 09.10.2008 №12-2, Маслихат Жалагашского района
title:
  rus: Жалағаш кенті бойынша жер учаскелері үшін салықтық төлемақының базалық ставкаларына түзеті коэффициенттерін және жерді аймақтарға бөлу жобасын (схемасын) бекіту туралы
  kaz: Жалағаш кенті бойынша жер учаскелері үшін салықтық төлемақының базалық ставкаларына түзеті коэффициенттерін және жерді аймақтарға бөлу жобасын (схемасын) бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-10-09
approved_by:
- '161006000002'
version_date:
  kaz: 2008-10-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/42176/kaz/09.10.2008
