act_code: '214097'
requisite: Решение акима сельского округа Калжан ахуна Сырдарьинского района Кызылординской области от 10 сентября 2025 года № 13
title:
  rus: О присвоении наименования безымянной улице в сельском округе Калжан ахун
  kaz: Қалжан ахун ауылдық округіндегі атауы жоқ көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-10
approved_by:
- '161007006002'
version_date:
  kaz: 2025-09-10
  rus: 2025-09-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/214097/kaz/10.09.2025
  rus: https://zan.gov.kz/client/#!/doc/214097/rus/10.09.2025
