act_code: '118082'
requisite: Решение Жанакорганского районного маслихата Кызылординской области от 26 декабря 2017 года № 05-16/186. Зарегистрировано Департаментом юстиции Кызылординской области 5 января 2018 года № 6115
title:
  rus: О районном бюджете на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-26
approved_by:
- '161009000002'
version_date:
  kaz: 2018-06-20
  rus: 2018-06-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/118082/kaz/20.06.2018
  rus: https://zan.gov.kz/client/#!/doc/118082/rus/20.06.2018
caused_by:
  code: '123489'
  requisite: Решение Жанакорганского районного маслихата Кызылординской области от 20 июня 2018 года № 234. Зарегистрировано Департаментом юстиции Кызылординской области 11 июля 2018 года № 6373
  title:
    rus: О внесении изменений в решение Жанакоргаского районного маслихата от 26 декабря 2017 года №05-16/186 «О районном бюджете на 2018-2020 годы»
    kaz: «2018-2020 жылдарға арналған аудандық бюджет туралы» Жаңақорған аудандық мәслихатының 2017 жылғы 26 желтоқсандағы №05-16/186 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123489/rus
