act_code: '205750'
requisite: Решение Кармакшинского районного маслихата Кызылординской области от 26 декабря 2024 года № 245
title:
  rus: О бюджете сельского округа Т.Комекбаева на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Т.Көмекбаев ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-26
approved_by:
- '161005000002'
version_date:
  kaz: 2025-12-11
  rus: 2025-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/205750/kaz/11.12.2025
  rus: https://zan.gov.kz/client/#!/doc/205750/rus/11.12.2025
caused_by:
  code: '220447'
  requisite: Решение Кармакшинского районного маслихата Кызылординской области от 11 декабря 2025 года № 349
  title:
    rus: О внесении изменений в решение Кармакшинского районного маслихата Кызылординской области «О бюджете сельского округа Т.Комекбаева на 2025-2027 годы» от 26 декабря 2024 года №245
    kaz: Қызылорда облысы Қармақшы аудандық мәслихатының 2024 жылғы 26 желтоқсандағы №245 «2025-2027 жылдарға арналған Т.Көмекбаев ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/220447/rus
