act_code: '221318'
requisite: Решение Кармакшинского районного маслихата Кызылординской области от 19 декабря 2025 года № 352
title:
  rus: О районном бюджете на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-19
approved_by:
- '161005000002'
version_date:
  kaz: 2026-02-13
  rus: 2026-02-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/221318/kaz/13.02.2026
  rus: https://zan.gov.kz/client/#!/doc/221318/rus/13.02.2026
caused_by:
  code: '222565'
  requisite: Решение Кармакшинского районного маслихата Кызылординской области от 13 февраля 2026 года № 376
  title:
    rus: О внесении изменений и дополнений в решение Кармакшинского районного маслихата Кызылординской области от 19 декабря 2025 года №352 «О районном бюджете на 2026-2028 годы»
    kaz: Қызылорда облысы Қармақшы аудандық мәслихатының 2025 жылғы 19 желтоқсандағы №352 «2026-2028 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/222565/rus
