act_code: '52424'
requisite: Решение от 12.04.2010 №143, Акимат аульного округа Кызылжарма
title:
  rus: Қызылжарма ауылдық округіндегі көшелерге атаулар беру туралы
  kaz: Қызылжарма ауылдық округіндегі көшелерге атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-12
approved_by:
- '161002001001'
version_date:
  kaz: 2010-04-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/52424/kaz/12.04.2010
