act_code: '7327'
requisite: Решение от 27.12.1999 №108, Аким Кызылординской области
title:
  rus: Облыс сауда мекемелері мен базарларда сатылатын ас тұзының сапасын бақылауды күшейту туралы
  kaz: Облыс сауда мекемелері мен базарларда сатылатын ас тұзының сапасын бақылауды күшейту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-12-27
approved_by:
- '161000000003'
version_date:
  kaz: 1999-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/7327/kaz/27.12.1999
