act_code: '98180'
requisite: Решение Жанакорганского районного маслихата Кызылординской области от 24 декабря 2015 года № 343. Зарегистрировано Департаментом юстиции Кызылординской области 19 января 2016 года № 5305. Утратило силу решением Жанакорганского районного маслихата Кызылординской области от 23 декабря 2016 года № 01-01-03/86
title:
  rus: Об утверждении правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсету, оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-24
approved_by:
- '161009000002'
version_date:
  kaz: 2016-08-26
  rus: 2016-08-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/98180/kaz/26.08.2016
  rus: https://zan.gov.kz/client/#!/doc/98180/rus/26.08.2016
caused_by:
  code: '106149'
  requisite: Решение Жанакорганского районного маслихата Кызылординской области от 26 августа 2016 года № 01-01-03/49. Зарегистрировано Департаментом юстиции Кызылординской области 9 сентября 2016 года № 5595. Утратило силу решением Жанакорганского районного маслихата Кызылординской области от 23 декабря 2016 года № 01-01-03/86
  title:
    rus: О внесении изменений в решение Жанакорганского районного маслихата от 24 декабря 2015 года № 343 "Об утверждении правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан"
    kaz: '"Әлеуметтік көмек көрсету, оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидаларын бекіту туралы" Жаңақорған аудандық мәслихатының 2015 жылғы 24 желтоқсандағы № 343 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/106149/rus
