act_code: '117940'
requisite: Решение Казалинского районного маслихата Кызылординской области от 22 декабря 2017 года № 149. Зарегистрировано Департаментом юстиции Кызылординской области 29 декабря 2017 года № 6108
title:
  rus: Об утврждении плана по управлению пастбищами и их использованию по Казалинскому району на 2017-2018 годы
  kaz: Қазалы ауданы бойынша 2017-2018 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-22
approved_by:
- '161004000002'
version_date:
  kaz: 2017-12-22
  rus: 2017-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/117940/kaz/22.12.2017
  rus: https://zan.gov.kz/client/#!/doc/117940/rus/22.12.2017
