act_code: '81888'
requisite: Решение Кызылординского городского маслихата от 29 июля 2014 года № 31/4. Зарегистрировано Департаментом юстиции Кызылординской области 12 августа 2014 года № 4744. Утратило силу решением Кызылординского городского маслихата от 23.06.2015 № 43/6.
title:
  rus: Об утверждении правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсету, оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-07-29
approved_by:
- '161002000002'
version_date:
  kaz: 2015-02-19
  rus: 2015-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/81888/kaz/19.02.2015
  rus: https://zan.gov.kz/client/#!/doc/81888/rus/19.02.2015
caused_by:
  code: '87310'
  requisite: Решение Кызылординского городского маслихата от 19 февраля 2015 года № 39/4. Зарегистрировано Департаментом юстиции Кызылординской области 10 марта 2015 года № 4907. Утратило силу решением Кызылординского городского маслихата от 23.06.2015 № 43/6.
  title:
    rus: О внесении изменений и дополнений в решение Кызылординского городского маслихата от 29 июля 2014 года №31/4 «Об утверждении правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: «Әлеуметтік көмек көрсету, оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидасын бекіту туралы» Қызылорда қалалық мәслихатының 2014 жылғы 29 шілдедегі №31/4 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/87310/rus
