act_code: '56928'
requisite: Қызылорда облысы Арал аудандық мәслихатының 2010 жылғы 27 желтоқсандағы N 194 шешімі. Қызылорда облысының Әділет департаменті Арал аудандық Әділет басқармасында 2011 жылы 10 қаңтарда N 10-3-175 тіркелді. Күші жойылды - Қызылорда облысы Арал аудандық мәслихатының 2012 жылғы 13 қаңтардағы N 254 шешімімен
title:
  rus: 2011-2013 жылдарға арналған аудан бюджеті туралы
  kaz: 2011-2013 жылдарға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-27
approved_by:
- '161003000002'
version_date:
  kaz: 2011-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/56928/kaz/27.06.2011
caused_by:
  code: '59618'
  requisite: Решение Аральского районного маслихата Кызылординской области от 27 июня 2011 года № 219. Зарегистрировано Департаментом юстиции Кызылординской области 15 июля 2011 года за № 10-3-186. Утратило силу решением Аральского районного маслихата Кызылординской области от 13 января 2012 года № 254
  title:
    rus: О внесении изменений и дополнений в решение Аральского районного маслихата от 27 декабря 2010 года N 194 "О районном бюджете на 2011-2013 годы"
    kaz: '"2011-2013 жылдарға арналған аудан бюджеті туралы" Арал аудандық мәслихатының 2010 жылғы 27 желтоқсандағы N 194 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/59618/rus
