act_code: '56928'
requisite: Қызылорда облысы Арал аудандық мәслихатының 2010 жылғы 27 желтоқсандағы N 194 шешімі. Қызылорда облысының Әділет департаменті Арал аудандық Әділет басқармасында 2011 жылы 10 қаңтарда N 10-3-175 тіркелді. Күші жойылды - Қызылорда облысы Арал аудандық мәслихатының 2012 жылғы 13 қаңтардағы N 254 шешімімен
title:
  rus: 2011-2013 жылдарға арналған аудан бюджеті туралы
  kaz: 2011-2013 жылдарға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-27
approved_by:
- '161003000002'
version_date:
  kaz: 2011-01-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/56928/kaz/19.01.2011
caused_by:
  code: '57307'
  requisite: Решение от 19.01.2011 №203, Маслихат Аральского района
  title:
    rus: Аудандық мәслихаттың 2010 жылғы 27 желтоқсандағы кезекті отыз бірінші сессиясының "2011-2013 жылдарға арналған аудан бюджеті туралы" N 194 шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Аудандық мәслихаттың 2010 жылғы 27 желтоқсандағы кезекті отыз бірінші сессиясының "2011-2013 жылдарға арналған аудан бюджеті туралы" N 194 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/57307/rus
