act_code: '52430'
requisite: Қызылорда облыстық мәслихатының 2010 жылғы 31 наурыздағы N 216 шешімі. Қызылорда облысының Әділет департаментінде 2010 жылғы 07 мамырдағы N 4248 тіркелді. Күші жойылды - Қызылорда облыстық мәслихатының 2013 жылғы 10 шілдедегі N 123 шешімімен
title:
  rus: Қызылорда облысының ауылдық жерлеріне жұмысқа жіберілген медицина және фармацевтика қызметкерлеріне әлеуметтік қолдау көрсетудің қағидасын бекіту туралы
  kaz: Қызылорда облысының ауылдық жерлеріне жұмысқа жіберілген медицина және фармацевтика қызметкерлеріне әлеуметтік қолдау көрсетудің қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-31
approved_by:
- '161000000002'
version_date:
  kaz: 2010-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/52430/kaz/31.03.2010
