act_code: '59226'
requisite: Решение акима аульного округа Кумжиек Казалинского района Кызылординской области от 6 мая 2011 года № 5. Зарегистрировано Управлением юстиции Казалинского района Кызылординской области 15 июня 2011 года за № 10-4-154
title:
  rus: О переименовании улицы в ауле К.Примова
  kaz: Қ.Пірімов ауылындағы көше атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-05-06
approved_by:
- '161004019001'
version_date:
  kaz: 2011-05-06
  rus: 2011-05-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/59226/kaz/06.05.2011
  rus: https://zan.gov.kz/client/#!/doc/59226/rus/06.05.2011
