act_code: '9259'
requisite: Решение от 03.02.2001 №413, Аким Кызылординской области
title:
  rus: Ауылдық елді мекендерін қолдау «Ауыл келбеті» бағдарламасы туралы
  kaz: Ауылдық елді мекендерін қолдау «Ауыл келбеті» бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-02-03
approved_by:
- '161000000003'
version_date:
  kaz: 2001-02-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/9259/kaz/03.02.2001
