act_code: '178641'
requisite: Решение Аральского районного маслихата Кызылординской области от 13 января 2023 года № 366. Зарегистрировано Департаментом юстиции Кызылординской области 13 февраля 2023 года № 8364-11
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов по Аральскому району
  kaz: Арал ауданы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-01-13
approved_by:
- '161003000002'
version_date:
  kaz: 2023-01-13
  rus: 2023-01-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/178641/kaz/13.01.2023
  rus: https://zan.gov.kz/client/#!/doc/178641/rus/13.01.2023
