act_code: '214727'
requisite: Решение акима поселка Шалхия Жанакорганского района Кызылординской области от 22 сентября 2025 года № 37
title:
  rus: О присвоении наименования безымянной улицы поселка Шалхия и село Куттыхожа
  kaz: '"Шалқия кенті және Құттықожа ауылының атауы жоқ көшелеріне атау беру туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-22
approved_by:
- '161009002001'
version_date:
  kaz: 2025-09-22
  rus: 2025-09-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/214727/kaz/22.09.2025
  rus: https://zan.gov.kz/client/#!/doc/214727/rus/22.09.2025
