act_code: '193341'
requisite: Решение акима сельского округа Райым Аральского района Кызылординской области от 5 февраля 2024 года № 02
title:
  rus: О присвоении наименования безымянной улице села Кызылжар сельского округа Райым Аральского района Кызылординской области
  kaz: Қызылорда облысы Арал ауданы Райым ауылдық округінің Қызылжар ауылының атаусыз көшесіне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-05
approved_by:
- '161003009002'
version_date:
  kaz: 2024-02-05
  rus: 2024-02-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/193341/kaz/05.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193341/rus/05.02.2024
