act_code: '137443'
requisite: Решение Кызылординского областного маслихата от 12 декабря 2019 года № 375. Зарегистрировано Департаментом юстиции Кызылординской области 23 декабря 2019 года № 7039
title:
  rus: Об объемах трансфертов общего характера между областным и районными бюджетами, бюджетом города областного значения на 2020-2022 годы
  kaz: Облыстық және аудандық бюджеттер, облыстық маңызы бар қала бюджеті арасындағы 2020-2022 жылдарға арналған жалпы сипаттағы трансферттердің көлемі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-12
approved_by:
- '161000000002'
version_date:
  kaz: 2019-12-12
  rus: 2019-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/137443/kaz/12.12.2019
  rus: https://zan.gov.kz/client/#!/doc/137443/rus/12.12.2019
