act_code: '173306'
requisite: Решение акима сельского округа Шакен Казалинского района Кызылординской области от 14 июня 2022 года №24. Утратило силу решением акима сельского округа Шакен Казалинского района Кызылординской области от 20 сентября 2022 года № 27
title:
  rus: О перименовании улицы
  kaz: Көшені қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-06-14
approved_by:
- '161004015002'
version_date:
  kaz: 2022-06-14
  rus: 2022-06-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/173306/kaz/14.06.2022
  rus: https://zan.gov.kz/client/#!/doc/173306/rus/14.06.2022
