act_code: '140082'
requisite: Решение Жалагашского районного маслихата Кызылординской области от 4 марта 2020 года № 52-3. Зарегистрировано Департаментом юстиции Кызылординской области 5 марта 2020 года № 7267
title:
  rus: О предоставлении мер социальной поддержки на 2020 год
  kaz: 2020 жылға арналған әлеуметтік қолдау шараларын көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-03-04
approved_by:
- '161006000002'
version_date:
  kaz: 2020-09-09
  rus: 2020-09-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/140082/kaz/09.09.2020
  rus: https://zan.gov.kz/client/#!/doc/140082/rus/09.09.2020
caused_by:
  code: '146270'
  requisite: Решение Жалагашского районного маслихата Кызылординской области от 9 сентября 2020 года № 62-2. Зарегистрировано Департаментом юстиции Кызылординской области 10 сентября 2020 года № 7634
  title:
    rus: О внесении изменений в решение Жалагашского районного маслихата от 4 марта 2020 года №52-3 “О предоставлении мер социальной поддержки на 2020 год”
    kaz: “2020 жылға арналған әлеуметтік қолдау шараларын көрсету туралы” Жалағаш аудандық мәслихатының 2020 жылғы 4 наурыздағы №52-3 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/146270/rus
