act_code: '109606'
requisite: Қызылорда облысы Сырдария ауданы АсқарТоқмағанбетов ауылдық округі әкімінің 2014 жылғы 21 қарашадағы № 9 шешімі
title:
  rus: '"2010 жылғы 15 қыркүйектегі № 19 А.Тоқмағанбетов ауылдық округіндегі көшеге атау беру туралы" шешімінің күшін жою туралы'
  kaz: '"2010 жылғы 15 қыркүйектегі № 19 А.Тоқмағанбетов ауылдық округіндегі көшеге атау беру туралы" шешімінің күшін жою туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-11-21
approved_by:
- '161007015002'
version_date:
  kaz: 2014-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/109606/kaz/21.11.2014
