act_code: '114938'
requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 12 сентября 2017 года № 123. Зарегистрировано Департаментом юстиции Кызылординской области 27 сентября 2017 года № 5972. Утратило силу решением Сырдарьинского районного маслихата Кызылординской области от 16 сентября 2020 года № 430
title:
  rus: «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
  kaz: «Әлеуметтік көмек көрсету,оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау Қағидаларын бекіту туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-09-12
approved_by:
- '161007000002'
version_date:
  kaz: 2018-08-15
  rus: 2018-08-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/114938/kaz/15.08.2018
  rus: https://zan.gov.kz/client/#!/doc/114938/rus/15.08.2018
caused_by:
  code: '124262'
  requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 15 августа 2018 года № 226. Зарегистрировано Департаментом юстиции Кызылординской области 25 августа 2018 года № 6417. Утратило силу решением Сырдарьинского районного маслихата Кызылординской области от 16 сентября 2020 года № 430
  title:
    rus: О внесении изменений в решение Сырдарьинского районного маслихата от 12 сентября 2017 года №123 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: «Әлеуметтік көмек көрсету, оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау Қағидаларын бекіту туралы» Сырдария аудандық мәслихатының 2017 жылғы 12 қыркүйектегі  №123 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/124262/rus
