act_code: '140046'
requisite: Решение акима города Кызылорда Кызылординской области от 5 марта 2020 года № 886. Зарегистрировано Департаментом юстиции Кызылординской области 6 марта 2020 года № 7270. Утратило силу решением акима города Кызылорда Кызылординской области от 25 марта 2021 года № 915
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерiн құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-03-05
approved_by:
- '161002000003'
version_date:
  kaz: 2020-03-05
  rus: 2020-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/140046/kaz/05.03.2020
  rus: https://zan.gov.kz/client/#!/doc/140046/rus/05.03.2020
