act_code: '218074'
requisite: Решение Кызылординского городского маслихата от 27 ноября 2025 года № 311-44/5
title:
  rus: О повышении ставок земельного налога в городе Кызылорда
  kaz: Қызылорда қаласында жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-27
approved_by:
- '161002000002'
version_date:
  kaz: 2025-11-27
  rus: 2025-11-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/218074/kaz/27.11.2025
  rus: https://zan.gov.kz/client/#!/doc/218074/rus/27.11.2025
