act_code: '49363'
requisite: Қызылорда облысы Арал аудандық мәслихатының 2009 жылғы 16 қарашадағы N 123 шешімі. Қызылорда облысының Әділет департаменті Арал ауданының Әділет басқармасында 2009 жылы 14 желтоқсанда N 10-3-145 тіркелді. Күші жойылды - Қызылорда облысы Арал аудандық мәслихатының 2011 жылғы 26 тамыздағы N 227 Шешімімен.
title:
  rus: Аудан көлеміндегі қала, елді мекендерде көгалдандыру, көріктендіру және санитарлық-тазалық сақтау жұмыстарын жүргізудің және аудан көлемінде иттер мен мысықтарды ұстау Ережесін бекіту туралы
  kaz: Аудан көлеміндегі қала, елді мекендерде көгалдандыру, көріктендіру және санитарлық-тазалық сақтау жұмыстарын жүргізудің және аудан көлемінде иттер мен мысықтарды ұстау Ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-11-16
approved_by:
- '161003000002'
version_date:
  kaz: 2009-11-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/49363/kaz/16.11.2009
