act_code: '170122'
requisite: Решение Казалинского районного маслихата Кызылординской области от 25 июля 2022 года № 253. Зарегистрировано в Министерстве юстиции Республики Казахстан 25 июля 2022 года № 28886
title:
  rus: О признании утратившим силу решения Казалинского районного маслихата
  kaz: Қазалы аудандық мәслихатының шешімінің күшін жою деп тану туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-07-25
approved_by:
- '161004000002'
version_date:
  kaz: 2022-07-25
  rus: 2022-07-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/170122/kaz/25.07.2022
  rus: https://zan.gov.kz/client/#!/doc/170122/rus/25.07.2022
