act_code: '91422'
requisite: Решение от 18.06.2015 №41/2, Маслихат Шиелийского района. Утратило силу решением Шиелийского районного маслихата Кызылординской области от 23.12.2015 N 48/8.
title:
  rus: О повышении базовых ставок земельного налога
  kaz: Жер салығының базалық мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-06-18
approved_by:
- '161008000002'
version_date:
  kaz: 2015-06-18
  rus: 2015-06-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/91422/kaz/18.06.2015
  rus: https://zan.gov.kz/client/#!/doc/91422/rus/18.06.2015
