act_code: '218969'
requisite: Решение акима сельского округа Сунаката Жанакорганского района Кызылординской области от 09 сентября 2025 года № 20
title:
  rus: О присвоении найменований улицам
  kaz: Көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-09
approved_by:
- '161009003002'
version_date:
  kaz: 2025-09-09
  rus: 2025-09-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/218969/kaz/09.09.2025
  rus: https://zan.gov.kz/client/#!/doc/218969/rus/09.09.2025
