act_code: '208131'
requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 27 февраля 2025 года № 175
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Сырдарьинскому району на 2025-2029 годы
  kaz: Сырдария ауданы бойынша 2025-2029 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-02-27
approved_by:
- '161007000002'
version_date:
  kaz: 2025-02-27
  rus: 2025-02-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/208131/kaz/27.02.2025
  rus: https://zan.gov.kz/client/#!/doc/208131/rus/27.02.2025
