act_code: '43256'
requisite: Решение от 26.12.2008 №122, Маслихат Кызылординской области
title:
  rus: Қызылорда қаласының аумағындағы жарнама объектілері бойынша ай сайынғы базалық төлемақы ставкаларының мөлшерін арттыру туралы
  kaz: Қызылорда қаласының аумағындағы жарнама объектілері бойынша ай сайынғы базалық төлемақы ставкаларының мөлшерін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-26
approved_by:
- '161000000002'
version_date:
  kaz: 2008-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/43256/kaz/26.12.2008
