act_code: '116248'
requisite: Решение Аральского районного маслихата Кызылординской области от 8 ноября 2017 года № 111. Зарегистрировано Департаментом юстиции Кызылординской области 23 ноября 2017 года № 6042
title:
  rus: Об утверждении положения о награждении Почетной грамотой Аральского района
  kaz: Арал ауданының Құрмет грамотасымен наградтау туралы ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-11-08
approved_by:
- '161003000002'
version_date:
  kaz: 2024-07-11
  rus: 2024-07-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/116248/kaz/11.07.2024
  rus: https://zan.gov.kz/client/#!/doc/116248/rus/11.07.2024
caused_by:
  code: '199056'
  requisite: Решение Аральского районного маслихата Кызылординской области от 11 июля 2024 года № 245. Зарегистрировано Департаментом юстиции Кызылординской области 24 июля 2024 года № 8532-11
  title:
    rus: О внесении изменений в решение Аральского районного маслихата от 8 ноября  2017 года № 111 «Об утверждении положения  о награждении Почетной грамотой  Аральского района»
    kaz: «Арал ауданының Құрмет грамотасымен наградтау туралы ережесін бекіту туралы» Арал аудандық мәслихатының 2017 жылғы 8 қарашадағы № 111 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/199056/rus
