act_code: '135465'
requisite: Решение Кызылординского областного маслихата от 16 октября 2019 года № 365. Зарегистрировано Департаментом юстиции Кызылординской области 17 октября 2019 года № 6938
title:
  rus: Об утверждении Правил погребения и организации дела по уходу за могилами в Кызылординской области
  kaz: Қызылорда облысында жерлеудің және зираттарды күтіп ұстау ісін ұйымдастырудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-10-16
approved_by:
- '161000000002'
version_date:
  kaz: 2022-04-15
  rus: 2022-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/135465/kaz/15.04.2022
  rus: https://zan.gov.kz/client/#!/doc/135465/rus/15.04.2022
caused_by:
  code: '167010'
  requisite: Решение Кызылординского областного маслихата от 15 апреля 2022 года № 96
  title:
    rus: О внесении изменения в решение Кызылординского областного маслихата от 16 октября 2019 года № 365 «Об утверждении Правил погребения и организации дела по уходу за могилами в Кызылординской области»
    kaz: «Қызылорда облысында жерлеудің және зираттарды күтіп ұстау ісін ұйымдастырудың қағидаларын бекіту туралы» Қызылорда облыстық мәслихатының 2019 жылғы 16 қазандағы № 365 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/167010/rus
