act_code: '55158'
requisite: Решение от 30.09.2010 №249, Маслихат Жанакорганского района
title:
  rus: Аудандық мәслихаттың 2009 жылғы 4 мамырдағы кезектен тыс XV сессиясының "Ауылдық елді мекендерде жұмыс істейтін және тұратын әлеуметтік сала мамандарына әлеуметтік көмек беру нұсқаулығын бекіту туралы" N 134 шешіміне өзгертулер енгізу туралы
  kaz: Аудандық мәслихаттың 2009 жылғы 4 мамырдағы кезектен тыс XV сессиясының "Ауылдық елді мекендерде жұмыс істейтін және тұратын әлеуметтік сала мамандарына әлеуметтік көмек беру нұсқаулығын бекіту туралы" N 134 шешіміне өзгертулер енгізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-30
approved_by:
- '161009000002'
version_date:
  kaz: 2010-09-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/55158/kaz/30.09.2010
