act_code: '74339'
requisite: Решение Жалагашского районного маслихата Кызылординской области от 14 августа 2013 года № 23-3. Зарегистрировано Департаментом юстиции Кызылординской области 9 сентября 2013 года за № 4510. Утратило силу решением Жалагашского районного маслихата Кызылординской области от 9 апреля 2014 года № 30-7
title:
  rus: Об утверждении правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсету, оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-08-14
approved_by:
- '161006000002'
version_date:
  kaz: 2014-01-23
  rus: 2014-01-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/74339/kaz/23.01.2014
  rus: https://zan.gov.kz/client/#!/doc/74339/rus/23.01.2014
caused_by:
  code: '77381'
  requisite: Решение Жалагашского районного маслихата Кызылординской области от 23 января 2014 года N 28-4. Зарегистрировано Департаментом юстиции Кызылординской области 10 февраля 2014 года за N 4590. Утратило силу решением Жалагашского районного маслихата Кызылординской области от 09 апреля 2014 года N 30-7
  title:
    rus: О внесении изменения в решение Жалагашского районного маслихата от 14 августа 2013 года N 23-3 "Об утверждении правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан"
    kaz: '"Әлеуметтік көмек көрсету, оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидасын бекіту туралы" Жалағаш аудандық мәслихатының 2013 жылғы 14 тамыздағы N 23-3 шешіміне озгеріс енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/77381/rus
