act_code: '54124'
requisite: Решение от 07.07.2010 №214, Маслихат Казалинского района
title:
  rus: Аудандық мәслихаттың 2010 жылғы 26 ақпандағы кезектен тыс XXIV сессиясының  "Тұрғын үй көмегін көрсетудің мөлшері мен тәртібін бекіту туралы" N 194 шешіміне өзгерістер еңгізу туралы
  kaz: Аудандық мәслихаттың 2010 жылғы 26 ақпандағы кезектен тыс XXIV сессиясының  "Тұрғын үй көмегін көрсетудің мөлшері мен тәртібін бекіту туралы" N 194 шешіміне өзгерістер еңгізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-07
approved_by:
- '161004000002'
version_date:
  kaz: 2010-07-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/54124/kaz/07.07.2010
