act_code: '40418'
requisite: Қызылорда облысы Қармақшы ауданы Жосалы кенті әкімінің 2006 жылғы 15 наурыздағы № 274 шешімі. Қызылорда облысының Әділет басқармасында 2006 жылғы 5 сәуірде № 10-5-50 болып тіркелді
title:
  rus: Жосалы кентінде көркейту, көгалдандыру және санитарлық тазалықтың 2-айлығын өткізу туралы.
  kaz: Жосалы кентінде көркейту, көгалдандыру және санитарлық тазалықтың 2-айлығын өткізу туралы.
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-03-15
approved_by:
- '161005001001'
version_date:
  kaz: 2006-03-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/40418/kaz/15.03.2006
