act_code: '127828'
requisite: Решение Аральского районного маслихата Кызылординской области от 21 декабря 2018 года № 208. Зарегистрировано Департаментом юстиции Кызылординской области 24 декабря 2018 года № 6578
title:
  rus: О районном бюджете на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-21
approved_by:
- '161003000002'
version_date:
  kaz: 2019-09-12
  rus: 2019-09-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/127828/kaz/12.09.2019
  rus: https://zan.gov.kz/client/#!/doc/127828/rus/12.09.2019
caused_by:
  code: '134743'
  requisite: Решение Аральского районного маслихата Кызылординской области от 12 сентября 2019 года № 269. Зарегистрировано Департаментом юстиции Кызылординской области 18 сентября 2019 года № 6918
  title:
    rus: О внесении изменений в решение Аральского районного маслихата от 21 декабря 2018 года № 208 «О районном бюджете на 2019-2021 годы»
    kaz: «2019-2021 жылдарға арналған аудандық бюджет туралы» Арал аудандық мәслихатының 2018 жылғы 21 желтоқсандағы № 208 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/134743/rus
