act_code: '72811'
requisite: Решение Аральского районного маслихата Кызылординской области от 2 мая 2013 года № 97. Зарегистрировано Департаментом юстиции Кызылординской области 29 мая 2013 года № 4459. Утратило силу решением Аральского районного маслихата Кызылординской области от 8 ноября 2017 года № 103
title:
  rus: Об определении размера и порядка оказания жилищной помощи
  kaz: Тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-05-02
approved_by:
- '161003000002'
version_date:
  kaz: 2013-05-02
  rus: 2013-05-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/72811/kaz/02.05.2013
  rus: https://zan.gov.kz/client/#!/doc/72811/rus/02.05.2013
