act_code: '72811'
requisite: Решение Аральского районного маслихата Кызылординской области от 2 мая 2013 года № 97. Зарегистрировано Департаментом юстиции Кызылординской области 29 мая 2013 года № 4459. Утратило силу решением Аральского районного маслихата Кызылординской области от 8 ноября 2017 года № 103
title:
  rus: Об определении размера и порядка оказания жилищной помощи
  kaz: Тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-05-02
approved_by:
- '161003000002'
version_date:
  kaz: 2015-05-05
  rus: 2015-05-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/72811/kaz/05.05.2015
  rus: https://zan.gov.kz/client/#!/doc/72811/rus/05.05.2015
caused_by:
  code: '90070'
  requisite: Решение Аральского районного маслихата Кызылординской области от 5 мая 2015 года № 232. Зарегистрировано Департаментом юстиции Кызылординской области 26 мая 2015 года № 4990. Утратило силу решением Аральского районного маслихата Кызылординской области от 8 ноября 2017 года № 103
  title:
    rus: О внесении изменения в решение Аральского районного маслихата от 02 мая 2013 года № 97 "Об определении размера и порядка оказания жилищной помощи"
    kaz: '"Тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы" Арал аудандық мәслихаттың 2013 жылғы 02 мамырдағы № 97 шешіміне өзгеріс енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/90070/rus
