act_code: '144365'
requisite: Решение Кармакшинского районного маслихата Кызылординской области от 24 июня 2020 года № 358. Зарегистрировано Департаментом юстиции Кызылординской области 29 июня 2020 года № 7549
title:
  rus: Об определении специализированных мест для организации и проведения мирных собраний, порядка их использования и норм их предельной заполняемости, требований к материально-техническому и организационному обеспечению специализированных мест, а также границ прилегающих территорий, в которых запрещено проведение пикетирования
  kaz: Бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, олардың пайдалану тәртібі мен шекті толу нормаларын, материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптарды, сондай-ақ пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекараларын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-24
approved_by:
- '161005000002'
version_date:
  kaz: 2020-06-24
  rus: 2020-06-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/144365/kaz/24.06.2020
  rus: https://zan.gov.kz/client/#!/doc/144365/rus/24.06.2020
