act_code: '9258'
requisite: Решение от 03.02.2001 №406, Аким Кызылординской области
title:
  rus: Қазақстан Республикасының тәуелсіздігінің 10 жылдығы - Жылын өткізуге арналған аймақтық іс-шаралар жоспары туралы
  kaz: Қазақстан Республикасының тәуелсіздігінің 10 жылдығы - Жылын өткізуге арналған аймақтық іс-шаралар жоспары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-02-03
approved_by:
- '161000000003'
version_date:
  kaz: 2001-02-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/9258/kaz/03.02.2001
