act_code: '55016'
requisite: Решение от 17.09.2010 №1, Акимат аульного округа Кыркенсе
title:
  rus: Бекзат Саттархановтың атына көше атауын беру туралы
  kaz: Бекзат Саттархановтың атына көше атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-17
approved_by:
- '161009007001'
version_date:
  kaz: 2010-09-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/55016/kaz/17.09.2010
