act_code: '122192'
requisite: Решение Жалагашского районного маслихата Кызылординской области от 14 мая 2018 года № 23-3. Зарегистрировано Департаментом юстиции Кызылординской области 24 мая 2018 года № 6297
title:
  rus: Об утверждении регламента собрания местного сообщества поселка и сельских округов Жалагашского района
  kaz: Жалағаш ауданының кент және ауылдық округтерінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-05-14
approved_by:
- '161006000002'
version_date:
  kaz: 2021-09-03
  rus: 2021-09-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/122192/kaz/03.09.2021
  rus: https://zan.gov.kz/client/#!/doc/122192/rus/03.09.2021
caused_by:
  code: '158771'
  requisite: Решение Жалагашского районного маслихата Кызылординской области от 3 сентября 2021 года № 8-6
  title:
    rus: О внесении изменений в решение Жалагашского районного маслихата от 14 мая 2018 года №23-3 «Об утверждении регламента собрания местного сообщества поселка и сельских округов Жалагашского района»
    kaz: «Жалағаш ауданының кент және ауылдық округтерінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы» Жалағаш аудандық мәслихатының 2018 жылғы 14 мамырдағы №23-3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/158771/rus
