act_code: '128206'
requisite: Решение акима сельского округа Кейден Жанакорганского района Кызылординской области от 28 декабря 2018 года № 91. Зарегистрировано Департаментом юстиции Кызылординской области 29 декабря 2018 года № 6637
title:
  rus: О переименовании переулка
  kaz: Тұйық көшені қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-28
approved_by:
- '161009016001'
version_date:
  kaz: 2018-12-28
  rus: 2018-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/128206/kaz/28.12.2018
  rus: https://zan.gov.kz/client/#!/doc/128206/rus/28.12.2018
