act_code: '28404'
requisite: Қызылорда облысы Қармақшы ауданы Алдашбай Ахун ауылдық округінің әкімінің 2006 жылғы 13 наурыздағы № 19 шешімі. Қызылорда облысының Әділет басқармасында 2006 жылғы 5 сәуірде № 10-5-49 болып тіркелді
title:
  rus: Алдашбай Ахун ауылында көркейту, көгалдандыру және санитарлық тазалықтың 2 айлығын өткізу туралы
  kaz: Алдашбай Ахун ауылында көркейту, көгалдандыру және санитарлық тазалықтың 2 айлығын өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-03-13
approved_by:
- '161005006002'
version_date:
  kaz: 2006-03-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/28404/kaz/13.03.2006
