act_code: '42719'
requisite: Решение от 06.11.2008 №76, Маслихат Кармакшинского района
title:
  rus: Жосалы кенті бойынша жер учаскелері үшін салықтық төлемақының базалық ставкаларына түзету коэффициенттерін және жерді аймақтарға бөлу жобасын (схемасын) бекіту туралы
  kaz: Жосалы кенті бойынша жер учаскелері үшін салықтық төлемақының базалық ставкаларына түзету коэффициенттерін және жерді аймақтарға бөлу жобасын (схемасын) бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-11-06
approved_by:
- '161005000002'
version_date:
  kaz: 2013-07-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/42719/kaz/26.07.2013
caused_by:
  code: '74087'
  requisite: Решение Кармакшинского районного маслихата Кызылординской области от 26 июля 2013 года № 112. Зарегистрировано Департаментом юстиции Кызылординской области 29 августа 2013 года за № 4503. Утратило силу решением Кармакшинского районного маслихата Кызылординской области от 15 июня 2017 года № 100
  title:
    rus: О внесении изменений в решение Кармакшинского районного маслихата от 6 ноября 2008 года № 76 "Об утверждении поправочных коэффициентов к налоговым бызовым ставкам платы за земельные участки и проекта (схемы) зонирования земель по поселку Жосалы"
    kaz: '"Жосалы кенті бойынша жер учаскелері үшін салықтық төлемақының базалық ставкаларына түзету коэффициенттерін және жерді аймақтарға бөлу жобасын (схемасын) бекіту туралы" Қармақшы аудандық мәслихатының 2008 жылғы 6 қарашадағы N 76 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/74087/rus
