act_code: '116845'
requisite: Решение Кызылординского областного маслихата от 12 декабря 2017 года № 157. Зарегистрировано Департаментом юстиции Кызылординской области 14 декабря 2017 года № 6074
title:
  rus: Об областном бюджете на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-12
approved_by:
- '161000000002'
version_date:
  kaz: 2018-02-12
  rus: 2018-02-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/116845/kaz/12.02.2018
  rus: https://zan.gov.kz/client/#!/doc/116845/rus/12.02.2018
caused_by:
  code: '118795'
  requisite: Решение Кызылординского областного маслихата от 12 февраля 2018 года № 176. Зарегистрировано Департаментом юстиции Кызылординской области 13 февраля 2018 года № 6166
  title:
    rus: «О внесении изменений и дополнений в решение Кызылординского областного маслихата от 12 декабря 2017 года № 157 «Об областном бюджете на 2018-2020 годы»
    kaz: «2018-2020  жылдарға арналған облыстық бюджет туралы» Қызылорда облыстық мәслихатының 2017 жылғы 12 желтоқсандағы № 157 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/118795/rus
