act_code: '178115'
requisite: Решение Жалагашского районного маслихата Кызылординской области от 27 декабря 2022 года № 31-10
title:
  rus: О бюджете сельского округа Каракеткен на 2023-2025 годы
  kaz: 2023 – 2025 жылдарға арналған Қаракеткен ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-27
approved_by:
- '161006000002'
version_date:
  kaz: 2022-12-27
  rus: 2022-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/178115/kaz/27.12.2022
  rus: https://zan.gov.kz/client/#!/doc/178115/rus/27.12.2022
