act_code: '52312'
requisite: Қызылорда облысы Қазалы аудандық мәслихатының 2010 жылғы 30 наурыздағы N 203 шешімі. Қызылорда облысының Әділет департаменті Қазалы ауданының Әділет басқармасында 2010 жылы 04 мамырда N 10-4-120 тіркелді. Күші жойылды - Қызылорда облысы Қазалы аудандық мәслихатының 2011 жылғы 04 наурыздағы N 272 шешімімен
title:
  rus: Базарларда, сауда қатарлары мен белгіленген орындарда тауар сатуға және түрлі кәсіпкерлік қызметпен айналысатын тұлғаларға құқық беретін біржолғы талондардың құнын белгілеу туралы
  kaz: Базарларда, сауда қатарлары мен белгіленген орындарда тауар сатуға және түрлі кәсіпкерлік қызметпен айналысатын тұлғаларға құқық беретін біржолғы талондардың құнын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-30
approved_by:
- '161004000002'
version_date:
  kaz: 2010-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/52312/kaz/30.03.2010
