act_code: '152058'
requisite: Решение Жалагашского районного маслихата Кызылординской области от 28 декабря 2020 года № 70-10. Зарегистрировано Департаментом юстиции Кызылординской области 6 января 2021 года № 8101
title:
  rus: О бюджете сельского округа Каракеткен на 2021-2023 годы
  kaz: 2021 – 2023 жылдарға арналған Қаракеткен ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-28
approved_by:
- '161006000002'
version_date:
  kaz: 2021-07-14
  rus: 2021-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/152058/kaz/14.07.2021
  rus: https://zan.gov.kz/client/#!/doc/152058/rus/14.07.2021
caused_by:
  code: '157210'
  requisite: Решение Жалагашского районного маслихата Кызылординской области от 14 июля 2021 года № 7-11
  title:
    rus: О внесении изменений в решение Жалагашского районного маслихата от 28 декабря 2020 года №70-10 «О бюджете сельского округа Каракеткен на 2021-2023 годы»
    kaz: «2021 – 2023 жылдарға арналған Қаракеткен ауылдық округінің бюджеті туралы» Жалағаш аудандық мәслихатының 2020 жылғы 28 желтоқсандағы №70-10 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/157210/rus
