act_code: '137992'
requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 27 декабря 2019 года № 371. Зарегистрировано Департаментом юстиции Кызылординской области 30 декабря 2019 года № 7083
title:
  rus: О бюджете поселка Теренозек на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Тереңөзек кентінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-27
approved_by:
- '161007000002'
version_date:
  kaz: 2020-06-24
  rus: 2020-06-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/137992/kaz/24.06.2020
  rus: https://zan.gov.kz/client/#!/doc/137992/rus/24.06.2020
caused_by:
  code: '144258'
  requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 24 июня 2020 года № 413. Зарегистрировано Департаментом юстиции Кызылординской области 25 июня 2020 года № 7535
  title:
    rus: О внесении изменений в решение Сырдарьинского районного маслихата от 27 декабря 2019 года №371 «О бюджете поселка Теренозек на 2020-2022 годы»
    kaz: «2020 – 2022 жылдарға арналған Тереңөзек кентінің бюджеті туралы» Сырдария аудандық мәслихаттың 2019 жылғы 27 желтоқсандағы №371 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/144258/rus
