act_code: '153845'
requisite: Решение акима сельского округа Томенарык Жанакорганского района Кызылординской области от 19 марта 2021 года № 55. Зарегистрировано Департаментом юстиции Кызылординской области 25 марта 2021 года № 8226
title:
  rus: О присвоении наименования улице
  kaz: Көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-03-19
approved_by:
- '161009004002'
version_date:
  kaz: 2021-03-19
  rus: 2021-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/153845/kaz/19.03.2021
  rus: https://zan.gov.kz/client/#!/doc/153845/rus/19.03.2021
