act_code: '151440'
requisite: Решение Шиелийского районного маслихата Кызылординской области от 29 декабря 2020 года № 65/18. Зарегистрировано Департаментом юстиции Кызылординской области 31 декабря 2020 года № 8026
title:
  rus: О бюджете сельского округа Каргалы на 2021-2023 годы
  kaz: Қарғалы ауылдық округінің 2021-2023 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-29
approved_by:
- '161008000002'
version_date:
  kaz: 2021-09-08
  rus: 2021-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/151440/kaz/08.09.2021
  rus: https://zan.gov.kz/client/#!/doc/151440/rus/08.09.2021
caused_by:
  code: '158545'
  requisite: Решение Шиелийского районного маслихата Кызылординской области от 8 сентября 2021 года № 11/18
  title:
    rus: О внесении изменений в решение Шиелийского районного маслихата «О бюджет сельского округа Каргалы на 2021-2023 годы» от 29 декабря 2020 года №65/18
    kaz: Шиелі аудандық мәслихатының 2020 жылғы 29 желтоқсандағы «Қарғалы ауылдық округінің 2021-2023 жылдарға арналған бюджеті туралы» №65/18 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/158545/rus
