act_code: '48326'
requisite: Решение от 25.09.2009 №160, Маслихат Жанакорганского района
title:
  rus: Жаңақорған ауданының "Құрметті азаматы" атағын беру Ережесін бекіту туралы
  kaz: Жаңақорған ауданының "Құрметті азаматы" атағын беру Ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-09-25
approved_by:
- '161009000002'
version_date:
  kaz: 2009-09-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/48326/kaz/25.09.2009
