act_code: '217560'
requisite: Решение акима сельского округа Амангельды Сырдарьинского района Кызылординской области от 10 сентября 2025 года № 29
title:
  rus: О присвоении наименования безымянной улице в районе нового поселения сельского округа Амангельды
  kaz: Аманкелді ауылдық округіндегі жаңа қоныстану аймағындағы атауы жоқ көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-10
approved_by:
- '161007013002'
version_date:
  kaz: 2025-09-10
  rus: 2025-09-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/217560/kaz/10.09.2025
  rus: https://zan.gov.kz/client/#!/doc/217560/rus/10.09.2025
