act_code: '28523'
requisite: Қызылорда облысы Қармақшы ауданы Ақтөбе ауылдық округінің әкімінің 2006 жылғы 13 наурыздағы № 195 шешімі. Қызылорда облысының Әділет басқармасында 2006 жылғы 5 сәуірде № 10-5-48 болып тіркелді
title:
  rus: Ауылда көркейту, көгалдандыру және санитарлық тазалықтың 2 айлығын өткізу туралы
  kaz: Ауылда көркейту, көгалдандыру және санитарлық тазалықтың 2 айлығын өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-03-13
approved_by:
- '161005009002'
version_date:
  kaz: 2006-03-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/28523/kaz/13.03.2006
