act_code: '56929'
requisite: Решение от 24.12.2010 №37-4, Маслихат Жалагашского района
title:
  rus: Жалағаш ауданының елді мекендерінде жануарларды ұстау Нұсқаулығын бекіту туралы
  kaz: Жалағаш ауданының елді мекендерінде жануарларды ұстау Нұсқаулығын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '161006000002'
version_date:
  kaz: 2010-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/56929/kaz/24.12.2010
