act_code: '137909'
requisite: Решение Шиелийского районного маслихата Кызылординской области от 27 декабря 2019 года № 49/2. Зарегистрировано Департаментом юстиции Кызылординской области 30 декабря 2019 года № 7066
title:
  rus: О бюджете поселка Шиели на 2020-2022 годы
  kaz: Шиелі кентінің 2020-2022 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-27
approved_by:
- '161008000002'
version_date:
  kaz: 2020-12-04
  rus: 2020-12-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/137909/kaz/04.12.2020
  rus: https://zan.gov.kz/client/#!/doc/137909/rus/04.12.2020
caused_by:
  code: '149631'
  requisite: Решение Шиелийского районного маслихата Кызылординской области от 4 декабря 2020 года № 63/2. Зарегистрировано Департаментом юстиции Кызылординской области 7 декабря 2020 года № 7865
  title:
    rus: О внесении изменений в решение Шиелийского районного маслихата от 27 декабря 2019 года №49/2 «О бюджете поселка Шиели на 2020-2022 годы»
    kaz: «Шиелі кентінің 2020-2022 жылдарға арналған бюджеті туралы» Шиелі аудандық мәслихатының 2019 жылғы 27 желтоқсандағы №49/2 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149631/rus
