act_code: '95884'
requisite: Решение Шиелийского районного маслихата Кызылординской области от 06 ноября 2015 года № 45/6. Зарегистрировано Департаментом юстиции Кызылординской области 25 ноября 2015 года № 5230. Утратило силу решением Шиелийского районного маслихата Кызылординской области от 11.02.2016 N 50/10
title:
  rus: Об утверждении методики ежегодной оценки деятельности административных государственных служащих корпуса "Б" государственного учреждения "Аппарата маслихата Шиелийского района"
  kaz: '"Шиелі ауданының мәслихат аппараты" мемлекеттік мекемесінің "Б" корпусы мемлекеттік әкімшілік қызметшілерінің қызметін жыл сайынғы бағалаудың әдістемесін бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-11-06
approved_by:
- '161008000002'
version_date:
  kaz: 2015-11-06
  rus: 2015-11-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/95884/kaz/06.11.2015
  rus: https://zan.gov.kz/client/#!/doc/95884/rus/06.11.2015
