act_code: '55017'
requisite: Решение от 17.09.2010 №2, Акимат аульного округа Кыркенсе
title:
  rus: Төлегетай Сүйінішұлының атына көше атауын беру туралы
  kaz: Төлегетай Сүйінішұлының атына көше атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-17
approved_by:
- '161009007001'
version_date:
  kaz: 2010-09-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/55017/kaz/17.09.2010
