act_code: '128307'
requisite: Решение Казалинского районного маслихата Кызылординской области от 25 декабря 2018 года № 255. Зарегистрировано Департаментом юстиции Кызылординской области 27 декабря 2018 года № 6598
title:
  rus: О районном бюджете на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-25
approved_by:
- '161004000002'
version_date:
  kaz: 2019-12-09
  rus: 2019-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/128307/kaz/09.12.2019
  rus: https://zan.gov.kz/client/#!/doc/128307/rus/09.12.2019
caused_by:
  code: '136946'
  requisite: Решение Казалинского районного маслихата Кызылординской области от 9 декабря 2019 года № 333. Зарегистрировано Департаментом юстиции Кызылординской области 11 декабря 2019 года № 7020
  title:
    rus: О внесении изменений и дополнений в решение Казалинского районного маслихата от 25 декабря 2018 года №255 «О районном бюджете на 2019-2021 годы»
    kaz: «2019-2021 жылдарға арналған аудандық бюджет туралы» Қазалы аудандық мәслихатының 2018 жылғы 25 желтоқсандағы №255 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/136946/rus
