act_code: '94442'
requisite: Решение от 23.09.2015 №350, Маслихат Казалинского района.Утратило силу решением Казалинского районного маслихата Кызылординской области от 19.02.2016 N 390.
title:
  rus: Об утверждении методики ежегодной оценки деятельности административных государственных служащих корпуса "Б" государственного учреждения "аппарат Казалинского районного маслихата"
  kaz: '"Қазалы аудандық мәслихат аппараты" мемлекеттік мекемесінің "Б" корпусы мемлекеттік әкімшілік қызметшілерінің қызметін жыл сайынғы бағалаудың әдістемесін бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-09-23
approved_by:
- '161004000002'
version_date:
  kaz: 2015-09-23
  rus: 2015-09-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/94442/kaz/23.09.2015
  rus: https://zan.gov.kz/client/#!/doc/94442/rus/23.09.2015
