act_code: '52423'
requisite: Қызылорда облысы Қармақшы аудандық мәслихатының 2010 жылғы 14 сәуірдегі N 178 шешімі. Қызылорда облысының Әділет департаменті Қармақшы аудандық Әділет басқармасында 2010 жылы 12 мамырда N 10-5-137 тіркелді. Күші жойылды - Қызылорда облысы Қармақшы аудандық мәслихатының 2012 жылғы 19 қарашадағы N 64 Шешімімен
title:
  rus: Қармақшы ауданында аз қамтамасыз етілген азаматтарға тұрғын үй ұстауға және коммуналдық қызметтің ақысын төлеуге арналған тұрғын үй көмегін көрсету Қағидасын бекіту туралы
  kaz: Қармақшы ауданында аз қамтамасыз етілген азаматтарға тұрғын үй ұстауға және коммуналдық қызметтің ақысын төлеуге арналған тұрғын үй көмегін көрсету Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-14
approved_by:
- '161005000002'
version_date:
  kaz: 2010-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/52423/kaz/14.04.2010
