act_code: '68176'
requisite: Решение Жалагашского районного маслихата Кызылординской области от 26 сентября 2012 года № 11-9. Зарегистрировано Департаментом юстиции Кызылординской области 22 октября 2012 года № 4326. Прекращено действие по истечении срока действия (письмо Жалагашского районного маслихата Кызылординской области от 31 января 2013 года № 331)
title:
  rus: Об оказании единовременной материальной помощи
  kaz: Бір жолғы материалдық көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-09-26
approved_by:
- '161006000002'
version_date:
  kaz: 2012-09-26
  rus: 2012-09-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/68176/kaz/26.09.2012
  rus: https://zan.gov.kz/client/#!/doc/68176/rus/26.09.2012
