act_code: '154409'
requisite: Решение Жанакорганского районного маслихата Кызылординской области от 25 марта 2021 года № 21. Зарегистрировано Департаментом юстиции Кызылординской области 2 апреля 2021 года № 8244
title:
  rus: Об утверждении проекта (схемы) зонирования земель, границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки сельских населенных пунктов Жанакорганского района
  kaz: Жаңақорған ауданының ауылдық елді мекен жерлерін аймақтарға бөлу жобасын (схемасын), бағалау аймақтарының шекараларын және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-03-25
approved_by:
- '161009000002'
version_date:
  kaz: 2021-03-25
  rus: 2021-03-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/154409/kaz/25.03.2021
  rus: https://zan.gov.kz/client/#!/doc/154409/rus/25.03.2021
