act_code: '199554'
requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 30 июля 2024 года № 130
title:
  rus: Об утверждении программы по управлению коммунальными отходами по Сырдарьинскому району на 2024-2028 годы
  kaz: Сырдария ауданының 2024-2028 жылдарға арналған коммуналдық қалдықтарды басқару жөніндегі бағдарламасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-07-30
approved_by:
- '161007000002'
version_date:
  kaz: 2024-07-30
  rus: 2024-07-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/199554/kaz/30.07.2024
  rus: https://zan.gov.kz/client/#!/doc/199554/rus/30.07.2024
