act_code: '54365'
requisite: Решение от 10.08.2010 №90, Акимат Сырдарьинского района
title:
  rus: Тереңөзек кентіндегі көшеге атау беру туралы
  kaz: Тереңөзек кентіндегі көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-08-10
approved_by:
- '161007000001'
version_date:
  kaz: 2010-08-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/54365/kaz/10.08.2010
