act_code: '163829'
requisite: Решение Казалинского районного маслихата Кызылординской области от 7 декабря 2021 года № 151. Зарегистрировано в Министерстве юстиции Республики Казахстан 11 января 2022 года № 26429
title:
  rus: Об утверждении проектов (схем) зонирования земель, границ оценочных зон и поправочных коэффициентовк базовым ставкам платыза земельные участкиКазалинского района
  kaz: Қазалы ауданының жерлерін аймақтарға бөлу жобаларын (схемаларын), бағалау аймақтарының шекараларын және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-07
approved_by:
- '161004000002'
version_date:
  kaz: 2021-12-07
  rus: 2021-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/163829/kaz/07.12.2021
  rus: https://zan.gov.kz/client/#!/doc/163829/rus/07.12.2021
