act_code: '112652'
requisite: Решение Кызылординского областного маслихата от 16 мая 2017 года № 121. Зарегистрировано Департаментом юстиции Кызылординской области 7 июня 2017 года № 5871. Утратило силу решением Кызылординского областного маслихата от 30 мая 2023 года № 29
title:
  rus: Об утверждении правил содержания и защиты зеленых насаждений, благоустройства территорий городов и населенных пунктов Кызылординской области
  kaz: Қызылорда облысындағы жасыл екпелерді күтіп-ұстау және қорғау, қалалар және елді мекендердің аумақтарын абаттандырудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-05-16
approved_by:
- '161000000002'
version_date:
  kaz: 2019-08-19
  rus: 2019-08-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/112652/kaz/19.08.2019
  rus: https://zan.gov.kz/client/#!/doc/112652/rus/19.08.2019
caused_by:
  code: '134230'
  requisite: Решение Кызылординского областного маслихата от 19 августа 2019 года № 343. Зарегистрировано Департаментом юстиции Кызылординской области 21 августа 2019 года № 6898. Утратило силу решением Кызылординского областного маслихата от 30 мая 2023 года № 29
  title:
    rus: О внесении изменений и  дополнения в решение Кызылординского областного маслихата от 16 мая 2017 года № 121 «Об утверждении правил содержания и защиты зеленых насаждений, благоустройства территорий городов и населенных пунктов Кызылординской области»
    kaz: «Қызылорда облысындағы жасыл екпелерді күтіп-ұстау және қорғау, қалалар және елді мекендердің аумақтарын абаттандырудың қағидаларын бекіту туралы» Қызылорда облыстық мәслихатының 2017 жылғы 16 мамырдағы № 121 шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/134230/rus
