act_code: '36358'
requisite: "Қызылорда облыстық Мәслихаттың 2007 жылғы 12 желтоқсандағы N 41 шешімі.\r\nҚызылорда облысы Әділет департаментінде 2007 жылы 24 желтоқсанда N 4195 тіркелді. Қолданылу мерзімінің аяқталуына байланысты күші жойылды - (Қызылорда облыстық мәслихатының 2010 жылғы 01 сәуірдегі N 1-214м хатымен)"
title:
  rus: 2008 жылға арналған облыстық бюджет туралы
  kaz: 2008 жылға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-12
approved_by:
- '161000000002'
version_date:
  kaz: 2008-10-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/36358/kaz/17.10.2008
caused_by:
  code: '42060'
  requisite: Қызылорда облыстық мәслихатының 2008 жылғы 17 қазандағы N 101 шешімі. Қызылорда облыстық Әділет департаментінде 2008 жылғы 23 қазанда N 4209 тіркелді. Қолданылу мерзімінің аяқталуына байланысты күші жойылды - (Қызылорда облыстық мәслихатының 2010 жылғы 01 сәуірдегі N 1-214м хатымен)
  title:
    rus: '"2008 жылға арналған облыстық бюджет туралы" Қызылорда облыстық мәслихатының 2007 жылғы 12 желтоқсандағы ІІІ сессиясының N 41 шешіміне өзгерістер мен толықтыру енгізу туралы'
    kaz: '"2008 жылға арналған облыстық бюджет туралы" Қызылорда облыстық мәслихатының 2007 жылғы 12 желтоқсандағы ІІІ сессиясының N 41 шешіміне өзгерістер мен толықтыру енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/42060/rus
