act_code: '125649'
requisite: Решение акима Аральского района Кызылординской области от 24 октября 2018 года № 28-ш. Зарегистрировано Департаментом юстиции Кызылординской области 25 октября 2018 года № 6480
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерiн құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-10-24
approved_by:
- '161003000003'
version_date:
  kaz: 2020-11-02
  rus: 2020-11-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/125649/kaz/02.11.2020
  rus: https://zan.gov.kz/client/#!/doc/125649/rus/02.11.2020
caused_by:
  code: '148128'
  requisite: Решение акима Аральского района Кызылординской области от 2 ноября 2020 года № 6-ш. Зарегистрировано Департаментом юстиции Кызылординской области 2 ноября 2020 года № 7774
  title:
    rus: О внесении изменений в решение акима Аральского района от 24 октября 2018 года № 28-ш "Об образовании избирательных участков"
    kaz: '"Сайлау учаскелерiн құру туралы" Арал ауданы әкімінің 2018 жылғы 24 қазандағы № 28-ш шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/148128/rus
