act_code: '125649'
requisite: Решение акима Аральского района Кызылординской области от 24 октября 2018 года № 28-ш. Зарегистрировано Департаментом юстиции Кызылординской области 25 октября 2018 года № 6480
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерiн құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-10-24
approved_by:
- '161003000003'
version_date:
  kaz: 2018-10-24
  rus: 2018-10-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/125649/kaz/24.10.2018
  rus: https://zan.gov.kz/client/#!/doc/125649/rus/24.10.2018
