act_code: '162895'
requisite: Решение Кармакшинского районного маслихата Кызылординской области от 23 декабря 2021 года № 115
title:
  rus: О бюджете поселка Торетам на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Төретам кентінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-23
approved_by:
- '161005000002'
version_date:
  kaz: 2021-12-23
  rus: 2021-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/162895/kaz/23.12.2021
  rus: https://zan.gov.kz/client/#!/doc/162895/rus/23.12.2021
