act_code: '56770'
requisite: Қызылорда облысы Қармақшы аудандық мәслихатының 2010 жылғы 22 желтоқсандағы N 224 шешімі. Қызылорда облысының Әділет департаменті Қармақшы аудандық әділет басқармасында 2011 жылы 17 қаңтарда N 10-5-154 тіркелді. Шешімнің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды (Қызылорда облысы Қармақшы аудандық мәслихатының 2012 жылғы 01 наурыздағы N 41 хаты)
title:
  rus: 2011-2013 жылдарға арналған аудандық бюджет туралы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-22
approved_by:
- '161005000002'
version_date:
  kaz: 2011-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/56770/kaz/12.12.2011
caused_by:
  code: '62035'
  requisite: Решение Кармакшинского районного маслихата Кызылординской области от 12 декабря 2011 года № 307. Зарегистрировано Департаментом юстиции Кызылординской области 20 декабря 2011 года за № 10-5-171. Утратило силу в связи с истечением срока действия (письмо Кармакшинского районного маслихата Кызылординской области от 1 марта 2012 года № 41)
  title:
    rus: О внесении изменений и дополнений в решение очередной 34 сессии Кармакшинского районного маслихата от 22 декабря 2010 года N 224 "О районном бюджете на 2011-2013 годы"
    kaz: '"2011-2013 жылдарға арналған аудандық бюджет туралы" Қармақшы аудандық мәслихатының 2010 жылғы 22 желтоқсандағы кезекті 34 сессиясының N 224 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/62035/rus
