act_code: '191930'
requisite: Решение Аральского районного маслихата Кызылординской области от 26 декабря 2023 года № 144
title:
  rus: «О бюджете города Аральск на 2024-2026 годы»
  kaz: «2024-2026 жылдарға арналған Арал қаласының бюджеті туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-26
approved_by:
- '161003000002'
version_date:
  kaz: 2024-07-22
  rus: 2024-07-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/191930/kaz/22.07.2024
  rus: https://zan.gov.kz/client/#!/doc/191930/rus/22.07.2024
caused_by:
  code: '199109'
  requisite: Решение Аральского районного маслихата Кызылординской области от 22 июля 2024 года № 247
  title:
    rus: О внесении изменений в решение Аральского районного маслихата Кызылординской области от 26 декабря 2023 года № 144 «О бюджете города Аральск на 2024-2026 годы»
    kaz: Қызылорда облысы Арал аудандық мәслихатының 2023 жылғы 26 желтоқсандағы № 144 «2024-2026 жылдарға арналған Арал қаласының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/199109/rus
