act_code: '56434'
requisite: Решение от 13.12.2010 №261, Маслихат Кызылординской области
title:
  rus: 2011-2013 жылдарға арналған облыстық бюджет туралы
  kaz: 2011-2013 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-13
approved_by:
- '161000000002'
version_date:
  kaz: 2011-02-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/56434/kaz/09.02.2011
caused_by:
  code: '57309'
  requisite: Решение маслихата Кызылординской области от 9 февраля 2011 года № 272. Зарегистрировано Департаментом юстиции Кызылординской области 16 февраля 2011 года № 4265. Утратило силу решением маслихата Кызылординской области от 6 декабря 2011 года № 330
  title:
    rus: О внесение изменений и дополнения в решение Кызылординского областного маслихата от 13 декабря 2010 года N 261 "Об областном бюджете на 2011-2013 годы"
    kaz: '"2011-2013 жылдарға арналған облыстық бюджет туралы" Қызылорда облыстық мәслихатының 2010 жылғы 13 желтоқсандағы N 261 шешіміне өзгерістер мен толықтыру енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/57309/rus
