act_code: '54066'
requisite: Решение от 15.07.2010 №26, Акимат аульного округа Тартогай
title:
  rus: Тартоғай ауылдық округіне қарасты "18 бекет" елді мекеніндегі атауы жоқ көшеге "Тәуелсіздік"  атауын беру туралы
  kaz: Тартоғай ауылдық округіне қарасты "18 бекет" елді мекеніндегі атауы жоқ көшеге "Тәуелсіздік"  атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-15
approved_by:
- '161008016001'
version_date:
  kaz: 2010-07-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/54066/kaz/15.07.2010
