act_code: '48160'
requisite: Қызылорда облысы Жалағаш аудандық мәслихатының 2009 жылғы 24 қыркүйектегі N 20-2 шешімі. Қызылорда облысының Әділет департаменті Жалағаш ауданының әділет басқармасында 2009 жылы 15 қазанда N 10-6-128 тіркелді. Күші жойылды - Қызылорда облысы Жалағаш аудандық мәслихатының 2010 жылғы 03 наурыздағы N 27-2 шешімімен
title:
  rus: Аз қамтамасыз етілген азаматтарға тұрғын үй коммуналдық қызметінің ақысын төлеуге арналған тұрғын үй көмегін беру Қағидасын бекіту туралы
  kaz: Аз қамтамасыз етілген азаматтарға тұрғын үй коммуналдық қызметінің ақысын төлеуге арналған тұрғын үй көмегін беру Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-09-24
approved_by:
- '161006000002'
version_date:
  kaz: 2009-09-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/48160/kaz/24.09.2009
