act_code: '121206'
requisite: Решение акима поселка Айтеке би Казалинского района Кызылординской области от 9 апреля 2018 года № 119. Зарегистрировано Департаментом юстиции Кызылординской области 23 апреля 2018 года № 6269
title:
  rus: О присвоении наименования улицы
  kaz: Көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-04-09
approved_by:
- '161004001001'
version_date:
  kaz: 2018-04-09
  rus: 2018-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/121206/kaz/09.04.2018
  rus: https://zan.gov.kz/client/#!/doc/121206/rus/09.04.2018
