act_code: '137900'
requisite: Решение Казалинского районного маслихата Кызылординской области от 26 декабря 2019 года № 351. Зарегистрировано Департаментом юстиции Кызылординской области 30 декабря 2019 года № 7095
title:
  rus: О бюджете поселка Айтеке би на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Әйтеке би кентінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-26
approved_by:
- '161004000002'
version_date:
  kaz: 2020-05-18
  rus: 2020-05-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/137900/kaz/18.05.2020
  rus: https://zan.gov.kz/client/#!/doc/137900/rus/18.05.2020
caused_by:
  code: '143066'
  requisite: Решение Казалинского районного маслихата Кызылординской области от 18 мая 2020 года № 411. Зарегистрировано Департаментом юстиции Кызылординской области 20 мая 2020 года № 7436
  title:
    rus: О внесении изменений и дополнений в решение Казалинского районного маслихата от 26 декабря 2019 года №351 «О бюджете поселка Айтеке би на 2020-2022 годы»
    kaz: «2020-2022 жылдарға арналған Әйтеке би кентінің бюджеті туралы» Қазалы аудандық мәслихатының 2019 жылғы 26 желтоқсандағы №351 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/143066/rus
