act_code: '151485'
requisite: Решение Шиелийского районного маслихата Кызылординской области от 29 декабря 2020 года № 65/11. Зарегистрировано Департаментом юстиции Кызылординской области 31 декабря 2020 года № 8029
title:
  rus: О бюджете сельского округа Кердели на 2021-2023 годы
  kaz: Керделі ауылдық округінің 2021-2023 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-29
approved_by:
- '161008000002'
version_date:
  kaz: 2021-07-23
  rus: 2021-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/151485/kaz/23.07.2021
  rus: https://zan.gov.kz/client/#!/doc/151485/rus/23.07.2021
caused_by:
  code: '157376'
  requisite: Решение Шиелийского районного маслихата Кызылординской области от 23 июля 2021 года № 9/13
  title:
    rus: О внесении изменений в решение Шиелийского районного маслихата от 29 декабря 2020 года №65/11 «О бюджете сельского округа Кердели на 2021-2023 годы»
    kaz: Шиелі аудандық мәслихатының 2020 жылғы 29 желтоқсандағы №65/11 «Керделі ауылдық округінің 2021-2023 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/157376/rus
