act_code: '151741'
requisite: Решение Шиелийского районного маслихата Кызылординской области от 29 декабря 2020 года № 65/6. Зарегистрировано Департаментом юстиции Кызылординской области 5 января 2021 года № 8037
title:
  rus: О бюджете сельского округа Бестам на 2021-2023 годы
  kaz: Бестам ауылдық округінің 2021-2023 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-29
approved_by:
- '161008000002'
version_date:
  kaz: 2021-04-15
  rus: 2021-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/151741/kaz/15.04.2021
  rus: https://zan.gov.kz/client/#!/doc/151741/rus/15.04.2021
caused_by:
  code: '154900'
  requisite: Решение Шиелийского районного маслихата Кызылординской области от 15 апреля 2021 года № 5/5. Зарегистрировано Департаментом юстиции Кызылординской области 16 апреля 2021 года № 8298
  title:
    rus: О внесении изменений в решение Шиелийского районного маслихата от 29 декабря 2020 года №65/6 «О бюджете сельского округа Бестам на 2021-2023 годы»
    kaz: «Бестам ауылдық округінің 2021-2023 жылдарға арналған бюджеті туралы» Шиелі аудандық мәслихатының 2020 жылғы 29 желтоқсандағы №65/6 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/154900/rus
