act_code: '109377'
requisite: Решение акима сельского округа Озгент Жанакорганского района Кызылординской области от 27 декабря 2016 года № 38. Зарегистрировано Департаментом юстиции Кызылординской области 20 января 2017 года № 5703. Утратило силу решением акима сельского округа Озгент Жанакорганского района Кызылординской области от 28 апреля 2017 года № 49
title:
  rus: Об определении мест выпаса животных
  kaz: Мал жаятын орындарды айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-27
approved_by:
- '161009015002'
version_date:
  kaz: 2016-12-27
  rus: 2016-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/109377/kaz/27.12.2016
  rus: https://zan.gov.kz/client/#!/doc/109377/rus/27.12.2016
