act_code: '179066'
requisite: Решение акима поселка Жосалы Кармакшинского района Кызылординской области от 14 марта 2023 года N 1628. Зарегистрировано Департаментом юстиции Кызылординской области 15 марта 2023 года № 8374-11
title:
  rus: О присвоении наименования и переименовании улиц поселка Жосалы
  kaz: Жосалы кентінің көшелеріне атау беру және қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-03-14
approved_by:
- '161005001001'
version_date:
  kaz: 2023-03-14
  rus: 2023-03-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/179066/kaz/14.03.2023
  rus: https://zan.gov.kz/client/#!/doc/179066/rus/14.03.2023
