act_code: '144532'
requisite: Решение Казалинского районного маслихата Кызылординской области от 25 июня 2020 года № 444. Зарегистрировано Департаментом юстиции Кызылординской области 1 июля 2020 года № 7557
title:
  rus: Об определении специализированных мест для организации и проведения мирных собраний, порядка их использования и норм их предельной заполняемости, требований к материально-техническому и организационному обеспечению, а также границ прилегающих территорий, в которых запрещено проведение пикетирования
  kaz: Бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, олардың пайдалану тәртібі мен шекті толу нормаларын, материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптарды, сондай-ақ пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекараларын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-25
approved_by:
- '161004000002'
version_date:
  kaz: 2020-06-25
  rus: 2020-06-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/144532/kaz/25.06.2020
  rus: https://zan.gov.kz/client/#!/doc/144532/rus/25.06.2020
