act_code: '35327'
requisite: Қызылорда облысы Қазалы аудандық мәслихатының 2007 жылғы 26 сәуірдегі № 258 шешімі. Қызылорда облысының Әділет басқармасында 2007 жылғы 18 мамырда № 10-4-63 болып тіркелді
title:
  rus: ¥лы Отан соғысына қатысушылары мен мүгедектеріне, соғыста қаза тапқан (хабар-ошарсыз кеткен) жауынгерлердің екінші рет некеге тұрмаған жесірлеріне коммуналдық және байланыс қызметтері үшін жеңілдіктер беру мен бір жолғы материалдық көмек көрсету Ережесін бекіту туралы
  kaz: ¥лы Отан соғысына қатысушылары мен мүгедектеріне, соғыста қаза тапқан (хабар-ошарсыз кеткен) жауынгерлердің екінші рет некеге тұрмаған жесірлеріне коммуналдық және байланыс қызметтері үшін жеңілдіктер беру мен бір жолғы материалдық көмек көрсету Ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-04-26
approved_by:
- '161004000002'
version_date:
  kaz: 2007-04-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/35327/kaz/26.04.2007
