act_code: '143512'
requisite: Решение акима сельского округа Кумжиек Казалинского района Кызылординской области от 28 мая 2020 года № 33. Зарегистрировано Департаментом юстиции Кызылординской области 29 мая 2020 года № 7498
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-05-28
approved_by:
- '161004019002'
version_date:
  kaz: 2020-05-28
  rus: 2020-05-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/143512/kaz/28.05.2020
  rus: https://zan.gov.kz/client/#!/doc/143512/rus/28.05.2020
