act_code: '137432'
requisite: Решение Кармакшинского районного маслихата Кызылординской области от 20 декабря 2019 года № 280. Зарегистрировано Департаментом юстиции Кызылординской области 24 декабря 2019 года № 7041
title:
  rus: О районном бюджете на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-20
approved_by:
- '161005000002'
version_date:
  kaz: 2020-12-23
  rus: 2020-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/137432/kaz/23.12.2020
  rus: https://zan.gov.kz/client/#!/doc/137432/rus/23.12.2020
caused_by:
  code: '150553'
  requisite: Решение Кармакшинского районного маслихата Кызылординской области от 23 декабря 2020 года № 403. Зарегистрировано Департаментом юстиции Кызылординской области 24 декабря 2020 года № 7951
  title:
    rus: О внесении изменений в решение Кармакшинского районного маслихата от 20 декабря 2019 года №280 «О районном бюджете на 2020-2022 годы»
    kaz: «2020-2022 жылдарға арналған аудандық бюджет туралы» Қармақшы аудандық мәслихатының 2019 жылғы 20 желтоқсандағы №280 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/150553/rus
