act_code: '206430'
requisite: Решение Аральского районного маслихата Кызылординской области от 27 декабря 2024 года № 334
title:
  rus: «О бюджете сельского округа Камыстыбас на 2025-2027 годы»
  kaz: «2025-2027 жылдарға арналған Қамыстыбас ауылдық округінің бюджеті туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '161003000002'
version_date:
  kaz: 2025-12-02
  rus: 2025-12-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/206430/kaz/02.12.2025
  rus: https://zan.gov.kz/client/#!/doc/206430/rus/02.12.2025
caused_by:
  code: '218811'
  requisite: Решение Аральского районного маслихата Кызылординской области от 2 декабря 2025 года № 453
  title:
    rus: О внесении изменений в решение Аральского районного маслихата Кызылординской области от 27 декабря 2024 года № 334 «О бюджете сельского округа Камыстыбас на 2025-2027 годы»
    kaz: Қызылорда облысы Арал аудандық мәслихатының 2024 жылғы 27 желтоқсандағы № 334 «2025-2027 жылдарға арналған Қамыстыбас ауылдық округі бюджеті туралы» шешіміне өзгерістер  енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/218811/rus
