act_code: '121526'
requisite: Решение Казалинского районного маслихата Кызылординской области от 10 апреля 2018 года № 189. Зарегистрировано Департаментом юстиции Кызылординской области 27 апреля 2018 года № 6276. Утратило силу решением Казалинского районного маслихата Кызылординской области от 25 июля 2022 года № 253
title:
  rus: О повышении базовых ставок земельного налога
  kaz: Жер салығының базалық мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-04-10
approved_by:
- '161004000002'
version_date:
  kaz: 2018-04-10
  rus: 2018-04-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/121526/kaz/10.04.2018
  rus: https://zan.gov.kz/client/#!/doc/121526/rus/10.04.2018
