act_code: '56585'
requisite: Қызылорда қалалық мәслихатының 2010 жылғы 23 желтоқсандағы N 37/2 шешімі. Қызылорда облысының Әділет департаментінде 2011 жылы 06 қаңтарда N 10-1-160 тіркелді. Қолданылу мерзімінің аяқталуына байланысты күші жойылды - (Қызылорда қалалық мәслихатының 2012 жылғы 13 қаңтардағы N 15 хатымен)
title:
  rus: 2011-2013 жылдарға арналған қалалық бюджет туралы
  kaz: 2011-2013 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-23
approved_by:
- '161002000002'
version_date:
  kaz: 2011-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/56585/kaz/25.02.2011
caused_by:
  code: '57549'
  requisite: Решение Кызылординского городского маслихата от 25 февраля 2011 года № 40/1. Зарегистрировано Департаментом юстиции Кызылординской области 2 марта 2011 года за № 10-1-169. Утратило силу в связи с истечением срока применения - (письмо Кызылординского городского маслихата от 13 января 2012 года № 15)
  title:
    rus: О внесении изменений и дополнений в решение Кызылординского городского маслихата от 23 декабря 2010 года N 37/2 "О городском бюджете на 2011-2013 годы"
    kaz: '"2011-2013 жылдарға арналған қалалық бюджет туралы" Қызылорда қалалық мәслихатының 2010 жылғы 23 желтоқсандағы N 37/2 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/57549/rus
