act_code: '39876'
requisite: Решение от 26.05.2008 №292, Акимат аульного округа Кожакент
title:
  rus: '"Көше атауын өзгерту туралы"'
  kaz: '"Көше атауын өзгерту туралы"'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-05-26
approved_by:
- '161009008001'
version_date:
  kaz: 2008-05-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/39876/kaz/26.05.2008
