act_code: '9492'
requisite: Решение от 26.10.2000 №337, Аким Кызылординской области
title:
  rus: Облыстық өнеркәсіп және көлік департаментінің Ережесі мен құрылымын бекіту туралы
  kaz: Облыстық өнеркәсіп және көлік департаментінің Ережесі мен құрылымын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-10-25
approved_by:
- '161000000003'
version_date:
  kaz: 2000-10-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/9492/kaz/25.10.2000
