act_code: '2642'
requisite: Решение акима Кызылординской области от 24 декабря 1998 года № 853. Зарегистрировано Управлением юстиции Кызылординской области 20 марта 1999 года № 80
title:
  rus: О ходе выполнения плана мероприятий по реализации Стратегического плана развития области на 1998 - 2000 годы
  kaz: Облыстық 1998 - 2000 жылдарға арналған Стратегиялық даму жоспарын жүзеге асыружөніндегі шаралар жоспарының орындалу барысы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-12-24
approved_by:
- '161000000003'
version_date:
  kaz: 1998-12-24
  rus: 1998-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/2642/kaz/24.12.1998
  rus: https://zan.gov.kz/client/#!/doc/2642/rus/24.12.1998
