act_code: '45334'
requisite: Решение от 27.03.2009 №146, Маслихат Кызылординской области
title:
  rus: '"Облыстың (қаланың, ауданның) құрметті азаматы" атағын беру ережесін бекіту туралы'
  kaz: '"Облыстың (қаланың, ауданның) құрметті азаматы" атағын беру ережесін бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-03-27
approved_by:
- '161000000002'
version_date:
  kaz: 2009-06-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/45334/kaz/26.06.2009
caused_by:
  code: '47087'
  requisite: Қызылорда облыстық мәслихатының 2009 жылғы 26 маусымдағы N 162 шешімі. Қызылорда облысының Әділет департаментінде 2009 жылы 28 шілдеде N 4233 тіркелді. Күші жойылды - Қызылорда облыстық мәслихатының 2012 жылғы 06 желтоқсандағы N 63 шешімімен
  title:
    rus: '"Қызылорда облысының құрметті азаматы" атағын беру ережесін бекіту туралы" Қызылорда облыстық мәслихатының 2009 жылғы 27 наурыздағы N 146 шешіміне өзгерістер енгізу туралы'
    kaz: '"Қызылорда облысының құрметті азаматы" атағын беру ережесін бекіту туралы" Қызылорда облыстық мәслихатының 2009 жылғы 27 наурыздағы N 146 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/47087/rus
