act_code: '163722'
requisite: Решение Шиелийского районного маслихата Кызылординской области от 30 декабря 2021 года № 18/23
title:
  rus: О бюджете сельского округа Жанатурмыс на 2022-2024 годы
  kaz: Жаңатұрмыс ауылдық округінің 2022-2024 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '161008000002'
version_date:
  kaz: 2022-12-13
  rus: 2022-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/163722/kaz/13.12.2022
  rus: https://zan.gov.kz/client/#!/doc/163722/rus/13.12.2022
caused_by:
  code: '175661'
  requisite: Решение Шиелийского районного маслихата Кызылординской области от 13 декабря 2022 года № 32/14
  title:
    rus: О внесении изменений в решение Шиелийского районного маслихата «О бюджете сельского округа Жанатурмыс на 2022-2024 годы» от 30 декабря 2021 года №18/23
    kaz: Шиелі аудандық мәслихатының 2021 жылғы 30 желтоқсандағы «Жаңатұрмыс ауылдық округінің 2022-2024 жылдарға арналған бюджеті туралы» №18/23 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/175661/rus
