act_code: '52487'
requisite: Решение от 14.04.2010 №30/9, Маслихат Шиелийского района
title:
  rus: Шиелі ауданының аумағында иттер мен мысықтар ұстау ережесін бекіту туралы
  kaz: Шиелі ауданының аумағында иттер мен мысықтар ұстау ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-14
approved_by:
- '161008000002'
version_date:
  kaz: 2010-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/52487/kaz/14.04.2010
