act_code: '123378'
requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 15 июля 2018 года № 206. Зарегистрировано Департаментом юстиции Кызылординской области 4 июля 2018 года № 6371. Утратило силу решением Сырдарьинского районного маслихата Кызылординской области от 18 марта 2020 года № 400
title:
  rus: Об установлении единых ставок фиксированного налога
  kaz: Бірыңғай тiркелген салық мөлшерлемелерiн белгiлеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-06-15
approved_by:
- '161007000002'
version_date:
  kaz: 2018-06-15
  rus: 2018-06-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/123378/kaz/15.06.2018
  rus: https://zan.gov.kz/client/#!/doc/123378/rus/15.06.2018
