act_code: '144374'
requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 24 июня 2020 года № 414. Зарегистрировано Департаментом юстиции Кызылординской области 29 июня 2020 года № 7550
title:
  rus: Об определении специализированных мест для организации и проведения мирных собраний, порядка их использования и норм их предельной заполняемости, требований к материально-техническому и организационному обеспечению специализированных мест, а также границ прилегающих территорий, в которых запрещено проведение пикетирования
  kaz: Бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, олардың пайдалану тәртібі мен шекті толу нормаларын, материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптарды, сондай-ақ пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекараларын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-24
approved_by:
- '161007000002'
version_date:
  kaz: 2024-06-26
  rus: 2024-06-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/144374/kaz/26.06.2024
  rus: https://zan.gov.kz/client/#!/doc/144374/rus/26.06.2024
caused_by:
  code: '198476'
  requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 26 июня 2024 года № 115. Зарегистрировано Департаментом юстиции Кызылординской области 3 июля 2024 года № 8527-11
  title:
    rus: О внесении изменений в решение Сырдарьинского районного маслихата от 24 июня 2020 года № 414 «Об определении специализированных мест для организации и проведения мирных собраний, порядка их использования и норм их предельной заполняемости, требований к материально-техническому и организационному обеспечению специализированных мест, а также границ прилегающих территорий,  в которых запрещено проведение пикетирования»
    kaz: «Бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, олардың пайдалану тәртібі мен шекті толу нормаларын, материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптарды, сондай-ақ пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекараларын айқындау туралы» Сырдария аудандық мәслихатының 2020 жылғы 24 маусымдағы № 414 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/198476/rus
