act_code: '214099'
requisite: Решение акима сельского округа Шакен Казалинского района Кызылординской области от 09 сентября 2025 года № 5
title:
  rus: О присвоении наименования безымянной улице
  kaz: Атауы жоқ көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-09
approved_by:
- '161004015002'
version_date:
  kaz: 2025-09-09
  rus: 2025-09-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/214099/kaz/09.09.2025
  rus: https://zan.gov.kz/client/#!/doc/214099/rus/09.09.2025
