act_code: '163242'
requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 28 декабря 2021 года № 108. Зарегистрировано в Министерстве юстиции Республики Казахстан 30 декабря 2021 года № 26239
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Сырдарьинском районе
  kaz: Сырдария ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсалған шығындарды өтеу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-28
approved_by:
- '161007000002'
version_date:
  kaz: 2022-10-20
  rus: 2022-10-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/163242/kaz/20.10.2022
  rus: https://zan.gov.kz/client/#!/doc/163242/rus/20.10.2022
caused_by:
  code: '173242'
  requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 20 октября 2022 года № 166. Зарегистрирован в Министерстве юстиции Республики Казахстан 22 октября 2022 года № 30304
  title:
    rus: О внесении изменений в решение Сырдарьинского районного маслихата от 28 декабря 2021 года №108 «Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану в Сырдарьинском районе»
    kaz: Сырдария аудандық мәслихатының 2021 жылғы 28 желтоқсандағы №108 «Сырдария ауданында мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсалған шығындарды өтеу тәртібін және мөлшерін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/173242/rus
