act_code: '183707'
requisite: Решение Жанакорганского районного маслихата Кызылординской области от 27 июня 2023 года № 50. Зарегистрировано Департаментом юстиции Кызылординской области 4 июля 2023 года № 8440-11
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Жанакорганском районе
  kaz: Жаңақорған ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өтеу тәртiбі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-06-27
approved_by:
- '161009000002'
version_date:
  kaz: 2024-12-20
  rus: 2024-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/183707/kaz/20.12.2024
  rus: https://zan.gov.kz/client/#!/doc/183707/rus/20.12.2024
caused_by:
  code: '204805'
  requisite: Решение Жанакорганского районного маслихата Кызылординской области от 20 декабря 2024 года № 299. Зарегистрировано Департаментом юстиции Кызылординской области 24 декабря 2024 года № 8573-11
  title:
    rus: О внесении изменений в решение маслихата Жанакорганского района от 27 июня 2023 года № 50 «Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Жанакорганском районе»
    kaz: «Жаңақорған ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өтеу тәртiбі мен мөлшерін айқындау туралы» Жаңақорған ауданы мәслихатының 2023 жылғы 27 маусымдағы № 50 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/204805/rus
