act_code: '183707'
requisite: Решение Жанакорганского районного маслихата Кызылординской области от 27 июня 2023 года № 50. Зарегистрировано Департаментом юстиции Кызылординской области 4 июля 2023 года № 8440-11
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Жанакорганском районе
  kaz: Жаңақорған ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өтеу тәртiбі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-06-27
approved_by:
- '161009000002'
version_date:
  kaz: 2023-06-27
  rus: 2023-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/183707/kaz/27.06.2023
  rus: https://zan.gov.kz/client/#!/doc/183707/rus/27.06.2023
