act_code: '56630'
requisite: Қызылорда облысы Шиелі аудандық мәслихатының 2010 жылғы 24 желтоқсандағы N 41/2 шешімі. Қызылорда облысының Әділет департаментінде 2011 жылы 06 қаңтарда N 10-9-182 тіркелді. Күші жойылды - Қызылорда облысы Шиелі аудандық мәслихатының 2012 жылғы 12 сәуірдегі N 3/4 Шешімімен
title:
  rus: Шиелі ауданының 2011-2013 жылдарға арналған бюджеті туралы
  kaz: Шиелі ауданының 2011-2013 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '161008000002'
version_date:
  kaz: 2011-01-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/56630/kaz/28.01.2011
caused_by:
  code: '57298'
  requisite: Решение Шиелийского районного маслихата Кызылординской области от 28 января 2011 года N 42/2. Зарегистрировано Департаментом юстиции Кызылординской области 09 февраля 2011 года за N 10-9-192. Утратилу силу решением Шиелийского районного маслихата Кызылординской области от 12 апреля 2012 года N 3/4
  title:
    rus: О внесении изменений и дополнений в решение районного маслихата от 24 декабря 2010 года N 41/2 "Об бюджете Шиелийского района на 2011-2013 годы"
    kaz: '"Шиелі ауданының 2011-2013 жылдарға арналған бюджеті туралы" аудандық мәслихаттың 2010 жылғы 24 желтоқсандағы N 41/2 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/57298/rus
