act_code: '56630'
requisite: Қызылорда облысы Шиелі аудандық мәслихатының 2010 жылғы 24 желтоқсандағы N 41/2 шешімі. Қызылорда облысының Әділет департаментінде 2011 жылы 06 қаңтарда N 10-9-182 тіркелді. Күші жойылды - Қызылорда облысы Шиелі аудандық мәслихатының 2012 жылғы 12 сәуірдегі N 3/4 Шешімімен
title:
  rus: Шиелі ауданының 2011-2013 жылдарға арналған бюджеті туралы
  kaz: Шиелі ауданының 2011-2013 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '161008000002'
version_date:
  kaz: 2010-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/56630/kaz/24.12.2010
