act_code: '163191'
requisite: Решение Кармакшинского районного маслихата Кызылординской области от 23 декабря 2021 года № 117
title:
  rus: О бюджете сельского округа ІІІ Интернационал на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған ІІІ Интернационал ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-23
approved_by:
- '161005000002'
version_date:
  kaz: 2022-11-08
  rus: 2022-11-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/163191/kaz/08.11.2022
  rus: https://zan.gov.kz/client/#!/doc/163191/rus/08.11.2022
caused_by:
  code: '173505'
  requisite: Решение Кармакшинского районного маслихата Кызылординской области от 08 ноября 2022 года № 232
  title:
    rus: О внесении изменений в решение Кармакшинского районного маслихата Кызылординской области от 23 декабря 2021 года №117 «О бюджете сельского округа ІІІ Интернационал на 2022-2024 годы»
    kaz: Қызылорда облысы Қармақшы аудандық мәслихатының 2021 жылғы 23 желтоқсандағы №117 «2022-2024 жылдарға арналған ІІІ Интернационал ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/173505/rus
