act_code: '1220'
requisite: Решение акима Кызылординской области от 10 апреля 1998 года № 709. Зарегистрировано Управлением юстиции Кызылординской области 29 мая 1998 года № 23
title:
  rus: О призыве граждан 1972-1980 годов рождения на срочную военную службу весной 1998 года
  kaz: 1972-1980 жылдары туылған азаматтарды 1998 жылғы көктемгі мерзімді әскери қызметке шақыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-04-09
approved_by:
- '161000000003'
version_date:
  kaz: 1998-04-09
  rus: 1998-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/1220/kaz/09.04.1998
  rus: https://zan.gov.kz/client/#!/doc/1220/rus/09.04.1998
