act_code: '66137'
requisite: Решение Кармакшинского районного маслихата Кызылординской области от 27 апреля 2012 года № 26. Зарегистрировано Департаментом юстиции Кызылординской области 25 мая 2012 года № 10-5-183. Утратило силу решением Кармакшинского районного маслихата Кызылординской области от 1 октября 2018 года № 202
title:
  rus: Об установлении единых ставок фиксированного налога на единицу объекта налогообложения
  kaz: Салық салу объектісінің бірлігіне тіркелген салықтың базалық ставкаларының мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-04-27
approved_by:
- '161005000002'
version_date:
  kaz: 2012-04-27
  rus: 2012-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/66137/kaz/27.04.2012
  rus: https://zan.gov.kz/client/#!/doc/66137/rus/27.04.2012
