act_code: '47066'
requisite: Қызылорда облысы Қызылорда қалалық мәслихатының 2009 жылғы 13 шілдедегі N 20/4 шешімі. Қызылорда облысының Әділет департаменті Қызылорда қалалық Әділет басқармасында 2009 жылы 30 шілдеде N 10-1-115 тіркелді. Күші жойылды - Қызылорда облысы Қызылорда қалалық мәслихатының 2012 жылғы 29 наурыздағы N 3/5 Шешімімен
title:
  rus: Ауылдық елді мекендерде тұратын және жұмыс істейтін денсаулық сақтау, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына, ауылдық жерде жұмыс істейтін білім беру мамандарына отын сатып алу үшін әлеуметтік көмек беру туралы Қағидасын бекіту туралы
  kaz: Ауылдық елді мекендерде тұратын және жұмыс істейтін денсаулық сақтау, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына, ауылдық жерде жұмыс істейтін білім беру мамандарына отын сатып алу үшін әлеуметтік көмек беру туралы Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-07-13
approved_by:
- '161002000002'
version_date:
  kaz: 2010-03-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/47066/kaz/03.03.2010
caused_by:
  code: '51546'
  requisite: Қызылорда облысы Қызылорда қалалық мәслихатының 2010 жылғы 03 наурыздағы N 28/7 шешімі. Қызылорда облысының Әділет департаменті Қызылорда қалалық әділет басқармасында 2010 жылы 30 наурызда N 10-1-131 тіркелді. Күші жойылды - Қызылорда облысы Қызылорда қалалық мәслихатының 2012 жылғы 29 наурыздағы N 3/5 Шешімімен
  title:
    rus: Қызылорда қалалық мәслихатының 2009 жылғы 13 шілдедегі N 20/4 "Ауылдық елді мекендерде тұратын және жұмыс істейтін денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет және спорт салалары мамандарына отын сатып алу үшін әлеуметтік көмек беру туралы Қағидасын бекіту туралы" шешіміне өзгеріс енгізу туралы
    kaz: Қызылорда қалалық мәслихатының 2009 жылғы 13 шілдедегі N 20/4 "Ауылдық елді мекендерде тұратын және жұмыс істейтін денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет және спорт салалары мамандарына отын сатып алу үшін әлеуметтік көмек беру туралы Қағидасын бекіту туралы" шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/51546/rus
