act_code: '87153'
requisite: Решение от 23.02.2015 №52, Акимат Кармакшинского района. Утратило силу решением акима Кармакшинского района Кызылординской области от 24 февраля 2025 года № 1
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-02-23
approved_by:
- '161005000001'
version_date:
  kaz: 2015-02-23
  rus: 2015-02-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/87153/kaz/23.02.2015
  rus: https://zan.gov.kz/client/#!/doc/87153/rus/23.02.2015
