act_code: '73995'
requisite: Решение Казалинского районного маслихата Кызылординской области от 26 июля 2013 года № 126. Зарегистрировано Департаментом юстиции Кызылординской области 16 августа 2013 года за № 4500. Утратило силу решением Казалинского районного маслихата Кызылординской области от 28 марта 2014 года № 198
title:
  rus: Об утверждении правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсету, оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-07-26
approved_by:
- '161004000002'
version_date:
  kaz: 2013-07-26
  rus: 2013-07-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/73995/kaz/26.07.2013
  rus: https://zan.gov.kz/client/#!/doc/73995/rus/26.07.2013
