act_code: '96502'
requisite: Решение Сырдарьинского районного маслихата Кызылординской области от 26 ноября 2015 года № 343. Зарегистрировано Департаментом юстиции Кызылординской области 10 декабря 2015 года № 5259. Утратило силу решением Сырдарьинского районного маслихата Кызылординской области от 29.02.2016 № 383
title:
  rus: О ставках земельного налога
  kaz: Жер салығының мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-11-26
approved_by:
- '161007000002'
version_date:
  kaz: 2015-11-26
  rus: 2015-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/96502/kaz/26.11.2015
  rus: https://zan.gov.kz/client/#!/doc/96502/rus/26.11.2015
