act_code: '80631'
requisite: Решение Жанакорганского районного маслихата Кызылординской области от 6 июня 2014 года № 212. Зарегистрировано Департаментом юстиции Кызылординской области 11 июня 2014 года № 4700. Утратило силу решением Жанакорганского районного маслихата Кызылординской области от 24 декабря 2015 года № 343
title:
  rus: Об утверждении правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсету, оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-06-06
approved_by:
- '161009000002'
version_date:
  kaz: 2015-03-31
  rus: 2015-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/80631/kaz/31.03.2015
  rus: https://zan.gov.kz/client/#!/doc/80631/rus/31.03.2015
caused_by:
  code: '88429'
  requisite: Решение Жанакорганского районного маслихата Кызылординской области от 31 марта 2015 года № 275. Зарегистрировано Департаментом юстиции Кызылординской области 9 апреля 2015 года № 4941
  title:
    rus: О внесении изменений и дополнений в решение маслихата Жанакорганского района от 6 июня 2014 года № 212 "Об утверждении правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан"
    kaz: «Әлеуметтік көмек көрсету, оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидасын бекіту туралы» Жаңақорған ауданы мәслихатының 2014 жылғы 6 маусымдағы №212 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/88429/rus
