act_code: '205598'
requisite: Решение Кызылординского городского маслихата от 24 декабря 2024 года № 232-33/4
title:
  rus: Об утверждении бюджета сельского округа Аксуат на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Ақсуат ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-24
approved_by:
- '161002000002'
version_date:
  kaz: 2025-03-06
  rus: 2025-03-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/205598/kaz/06.03.2025
  rus: https://zan.gov.kz/client/#!/doc/205598/rus/06.03.2025
caused_by:
  code: '208263'
  requisite: Решение Кызылординского городского маслихата от 6 марта 2025 года № 248-35/4
  title:
    rus: О внесении изменений в решение Кызылординского городского маслихата от 24 декабря 2024 года №232-33/4 «Об утверждении бюджета сельского округа Аксуат на 2025-2027 годы»
    kaz: «2025-2027 жылдарға арналған Ақсуат ауылдық округінің бюджетін бекіту туралы» Қызылорда қалалық мәслихатының 2024 жылғы 24 желтоқсандағы №232-33/4 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/208263/rus
