act_code: '122384'
requisite: Решение Аральского районного маслихата Кызылординской области от 23 мая 2018 года № 154. Зарегистрировано Департаментом юстиции Кызылординской области 5 июня 2018 года № 6306
title:
  rus: Об утверждении Регламента собрания местного сообщества поселка Саксаульск Аральского района
  kaz: Арал ауданы Сексеуіл кентінің жергілікті қоғамдастық жиналысының Регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-05-23
approved_by:
- '161003000002'
version_date:
  kaz: 2021-08-19
  rus: 2021-08-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/122384/kaz/19.08.2021
  rus: https://zan.gov.kz/client/#!/doc/122384/rus/19.08.2021
caused_by:
  code: '158096'
  requisite: Решение Аральского районного маслихата Кызылординской области от 19 августа 2021 года № 96
  title:
    rus: «О внесении изменений в решение Аральского районного маслихата от 23 мая 2018 года №154 «Об утверждении Регламента собрания местного сообщества поселка Саксаульск Аральского района»
    kaz: «Арал ауданы Сексеуіл кентінің жергілікті қоғамдастық жиналысының Регламентін бекіту туралы» Арал аудандық мәслихатының 2018 жылғы 23 мамырдағы №154 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/158096/rus
