act_code: '2606'
requisite: Решение акима Кызылординской области от 23 октября 1998 года № 823. Зарегистрировано Управлением юстиции Кызылординской области 28 декабря 1998 года № 71. Утратило силу постановлением акимата Кызылординской области от 20 декабря 2004 года № 247
title:
  rus: О введении «Журнала посещения и проверок должностными лицами контролирующих органов»
  kaz: Басқарушы органдар лауазымды адамдарының болу және тексеру журналын» енгізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-10-22
approved_by:
- '161000000003'
version_date:
  kaz: 1998-10-22
  rus: 1998-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/2606/kaz/22.10.1998
  rus: https://zan.gov.kz/client/#!/doc/2606/rus/22.10.1998
