act_code: '78883'
requisite: Решение от 10.04.2014 №224, Маслихат Сырдарьинского района. Утратило силу решением Сырдарьинского районного маслихата Кызылординской области от 26.11.2015 N 344
title:
  rus: Об утверждении правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсету, оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-10
approved_by:
- '161007000002'
version_date:
  kaz: 2014-04-10
  rus: 2014-04-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/78883/kaz/10.04.2014
  rus: https://zan.gov.kz/client/#!/doc/78883/rus/10.04.2014
