act_code: '9178'
requisite: Решение от 29.11.2000 №356, Аким Кызылординской области
title:
  rus: Экономикасы тоқырауға айналған округтерге көмектесу жайлы
  kaz: Экономикасы тоқырауға айналған округтерге көмектесу жайлы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-11-29
approved_by:
- '161000000003'
version_date:
  kaz: 2000-11-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/9178/kaz/29.11.2000
